// Code generated by go generate ./internal/targetinfo; DO NOT EDIT.

package targetinfo

const DefaultName = "linux/amd64"
const AdvertisedHelp = "linux/amd64 linux/386 linux/aarch64 linux/arm windows/amd64 windows/386 windows/arm64 darwin/arm64 wasi/wasm32 browser/wasm32 vm/vm32 freebsd/amd64 openbsd/amd64 netbsd/amd64\n"
const descriptorCount = 15

func All() []Descriptor {
	out := make([]Descriptor, descriptorCount)
	for i := 0; i < len(out); i++ {
		out[i] = descriptorAt(i)
	}
	return out
}

func Lookup(name string) (Descriptor, bool) {
	if name == "linux/amd64" {
		return descriptorAt(0), true
	}
	if name == "linux/386" {
		return descriptorAt(1), true
	}
	if name == "linux/aarch64" {
		return descriptorAt(2), true
	}
	if name == "linux/arm" {
		return descriptorAt(3), true
	}
	if name == "windows/amd64" {
		return descriptorAt(4), true
	}
	if name == "windows/386" {
		return descriptorAt(5), true
	}
	if name == "windows/arm64" {
		return descriptorAt(6), true
	}
	if name == "darwin/arm64" {
		return descriptorAt(7), true
	}
	if name == "wasi/wasm32" {
		return descriptorAt(8), true
	}
	if name == "browser/wasm32" {
		return descriptorAt(9), true
	}
	if name == "vm/vm32" {
		return descriptorAt(10), true
	}
	if name == "linux-kernel/amd64" {
		return descriptorAt(11), true
	}
	if name == "freebsd/amd64" {
		return descriptorAt(12), true
	}
	if name == "openbsd/amd64" {
		return descriptorAt(13), true
	}
	if name == "netbsd/amd64" {
		return descriptorAt(14), true
	}
	return Descriptor{}, false
}

func descriptorAt(index int) Descriptor {
	if index == 0 {
		return Descriptor{Name: "linux/amd64", Backend: "linux/amd64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf", Runtime: []string{"read", "write", "open", "close", "read_at", "write_at", "chmod", "print", "exit", "hosted"}, Tags: []string{"amd64", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "linkstatic", "object"}, Definition: [32]uint8{0x77, 0xd3, 0xb7, 0x55, 0x41, 0x36, 0x35, 0xb, 0xa9, 0x5f, 0xf6, 0xe3, 0x86, 0x67, 0xd6, 0x55, 0x4a, 0x70, 0x1c, 0xc3, 0xbe, 0x18, 0x1f, 0xb3, 0xe9, 0x22, 0x37, 0x54, 0xce, 0x80, 0x23, 0x2f}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-amd64", IDE: false}
	}
	if index == 1 {
		return Descriptor{Name: "linux/386", Backend: "linux/386", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "386", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "cdecl32", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"386", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x1e, 0xd2, 0x41, 0xf1, 0x2b, 0x26, 0x63, 0x63, 0xf9, 0xb3, 0x28, 0x30, 0xa2, 0xb5, 0xb9, 0x6a, 0x3c, 0x1, 0xe4, 0xe, 0x4c, 0x64, 0x8c, 0x68, 0x99, 0xf2, 0x58, 0x5f, 0x6f, 0x9a, 0xe7, 0x94}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-386", IDE: false}
	}
	if index == 2 {
		return Descriptor{Name: "linux/aarch64", Backend: "linux/aarch64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "aapcs64", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"aarch64", "arm64", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x4a, 0xb4, 0x21, 0x5b, 0xa0, 0xc6, 0x47, 0xa0, 0xb8, 0xc4, 0x78, 0x62, 0x6d, 0xca, 0x7a, 0x29, 0x18, 0xd6, 0xe0, 0x0, 0xb0, 0x90, 0xaf, 0x28, 0x23, 0xd6, 0x9, 0x20, 0xfb, 0x9a, 0x36, 0x7c}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-arm64", IDE: false}
	}
	if index == 3 {
		return Descriptor{Name: "linux/arm", Backend: "linux/arm", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "arm", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "aapcs32", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"arm", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xc6, 0xce, 0x91, 0x28, 0x6, 0x36, 0xf1, 0x45, 0x15, 0xf2, 0x5d, 0x56, 0xb5, 0x72, 0x7c, 0x67, 0x46, 0x63, 0xf9, 0xad, 0x76, 0xbe, 0xa8, 0x7d, 0x99, 0x74, 0xce, 0x1f, 0xd1, 0x2b, 0x65, 0x66}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-arm", IDE: false}
	}
	if index == 4 {
		return Descriptor{Name: "windows/amd64", Backend: "windows/amd64", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "windows_x86_64", Image: "pe", Runtime: []string{"open", "close", "read", "write", "read_at", "write_at", "seek", "print", "chmod", "exit", "hosted"}, Tags: []string{"amd64", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "imports", "linkstatic", "object", "windows_gui"}, Definition: [32]uint8{0x8, 0x72, 0x6c, 0x8f, 0x58, 0xa0, 0xb, 0x4f, 0x46, 0x61, 0xb4, 0x6e, 0xc2, 0xac, 0xa7, 0x1d, 0x53, 0x64, 0xc4, 0xc7, 0xa, 0x60, 0xde, 0x9a, 0x70, 0x19, 0x47, 0x68, 0x5, 0xa2, 0x95, 0x44}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-amd64.exe", IDE: true}
	}
	if index == 5 {
		return Descriptor{Name: "windows/386", Backend: "windows/386", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "386", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "win32", Image: "pe", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"386", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x2c, 0xd4, 0x7, 0xe0, 0xe9, 0x28, 0xa, 0xdb, 0x2, 0xf5, 0x37, 0x89, 0x97, 0x59, 0x5a, 0xf9, 0x97, 0xf, 0xb9, 0xfb, 0x68, 0x9a, 0xf2, 0x92, 0x1d, 0xf0, 0x10, 0xda, 0xc3, 0x12, 0x57, 0x7f}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-386.exe", IDE: true}
	}
	if index == 6 {
		return Descriptor{Name: "windows/arm64", Backend: "windows/arm64", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "windows_arm64", Image: "pe", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"aarch64", "arm64", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "windows_gui"}, Definition: [32]uint8{0x8d, 0xd, 0xe8, 0xa0, 0xd7, 0xaa, 0x3e, 0xa4, 0x43, 0x36, 0x4e, 0xde, 0x38, 0x58, 0xdb, 0xc0, 0x81, 0x3e, 0x2b, 0xa5, 0xdb, 0xcc, 0x33, 0x4b, 0xb1, 0x9a, 0xaf, 0xb1, 0x85, 0x7e, 0x18, 0x6a}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-arm64.exe", IDE: true}
	}
	if index == 7 {
		return Descriptor{Name: "darwin/arm64", Backend: "darwin/arm64", Aliases: []string(nil), Family: "native_v1", OS: "darwin", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "aapcs64", Image: "mach-o", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"aarch64", "arm64", "darwin", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xe8, 0x21, 0x29, 0x66, 0x95, 0xf1, 0x33, 0xc6, 0x8e, 0xf4, 0x81, 0xc1, 0x60, 0x6b, 0xb6, 0xd3, 0x7b, 0x43, 0xba, 0xd9, 0xf1, 0x75, 0xcc, 0x61, 0x1c, 0x7b, 0x34, 0xeb, 0x0, 0x80, 0xd6, 0x3b}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-darwin-arm64", IDE: true}
	}
	if index == 8 {
		return Descriptor{Name: "wasi/wasm32", Backend: "wasi/wasm32", Aliases: []string(nil), Family: "structured32", OS: "wasi", ISA: "wasm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "wasm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"wasi", "wasip1", "wasm", "wasm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xaa, 0x4, 0x4a, 0xab, 0x7d, 0x23, 0x99, 0xa, 0x44, 0x93, 0x7e, 0xd0, 0x12, 0xd, 0xb2, 0xdf, 0x51, 0xcd, 0xd5, 0x5b, 0x28, 0xd, 0xda, 0x5f, 0xfe, 0x97, 0x8f, 0x88, 0x4e, 0x8f, 0x1a, 0x6c}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-wasi-wasm32.wasm", IDE: false}
	}
	if index == 9 {
		return Descriptor{Name: "browser/wasm32", Backend: "wasi/wasm32", Aliases: []string(nil), Family: "structured32", OS: "browser", ISA: "wasm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "html-wasm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"browser", "wasi", "wasip1", "wasm", "wasm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xcd, 0x2f, 0x75, 0xab, 0x9, 0x65, 0xa2, 0x84, 0xb8, 0xf0, 0xf9, 0xd7, 0x2d, 0x3b, 0xbd, 0x29, 0x67, 0xdf, 0x6f, 0xb3, 0xe9, 0x33, 0x49, 0xbc, 0x15, 0xe5, 0x98, 0xea, 0x4e, 0x74, 0x4b, 0x60}, DescriptorVersion: 3, Advertised: true, Virtual: true, DefaultArena: 134217728, ReleaseArtifact: "", IDE: true}
	}
	if index == 10 {
		return Descriptor{Name: "vm/vm32", Backend: "vm/vm32", Aliases: []string(nil), Family: "structured32", OS: "vm", ISA: "vm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "rnvm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"vm", "vm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xd1, 0x34, 0xe6, 0x10, 0x45, 0x15, 0x88, 0xc6, 0xc5, 0x46, 0x15, 0x44, 0x8d, 0x86, 0x52, 0x4e, 0x6f, 0x7b, 0x4b, 0x65, 0x0, 0xa6, 0x7f, 0x8f, 0xdc, 0x74, 0x17, 0x28, 0x95, 0xdb, 0xea, 0xc7}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-vm32.rnvb", IDE: false}
	}
	if index == 11 {
		return Descriptor{Name: "linux-kernel/amd64", Backend: "linux-kernel/amd64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf-relocatable", Runtime: []string{"print", "open", "close", "read", "write", "chmod"}, Tags: []string{"amd64", "linux", "renvo_kernel", "unix"}, Capabilities: []string{"freestanding", "imports", "kernel_module", "linkstatic", "object"}, Definition: [32]uint8{0x3a, 0x3, 0x91, 0xe9, 0x2c, 0xa4, 0x2, 0x7, 0x5, 0x75, 0x89, 0x75, 0x49, 0x30, 0x9d, 0x43, 0xab, 0x8b, 0xf2, 0xc7, 0x2f, 0xd0, 0x48, 0x6c, 0xc4, 0xb4, 0xbd, 0x19, 0xfa, 0x24, 0xbd, 0xf2}, DescriptorVersion: 3, Advertised: false, Virtual: false, DefaultArena: 0, ReleaseArtifact: "", IDE: false}
	}
	if index == 12 {
		return Descriptor{Name: "freebsd/amd64", Backend: "freebsd/amd64", Aliases: []string(nil), Family: "native_v1", OS: "freebsd", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf", Runtime: []string{"read", "write", "open", "close", "read_at", "write_at", "chmod", "print", "exit", "hosted"}, Tags: []string{"amd64", "freebsd", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x26, 0xf6, 0x49, 0x52, 0xf8, 0x27, 0x6b, 0x34, 0x65, 0xa4, 0x8a, 0x8c, 0x81, 0x57, 0x4d, 0x93, 0x29, 0x34, 0xc0, 0xce, 0xa4, 0x1b, 0xa2, 0x26, 0x52, 0x76, 0x44, 0xa3, 0xdd, 0x4b, 0x6d, 0x6a}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-freebsd-amd64", IDE: false}
	}
	if index == 13 {
		return Descriptor{Name: "openbsd/amd64", Backend: "openbsd/amd64", Aliases: []string(nil), Family: "native_v1", OS: "openbsd", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf", Runtime: []string{"read", "write", "open", "close", "read_at", "write_at", "chmod", "print", "exit", "hosted"}, Tags: []string{"amd64", "openbsd", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x9e, 0x10, 0x6c, 0x4d, 0x5f, 0xf2, 0x22, 0x79, 0x29, 0x7b, 0xbc, 0xb8, 0x90, 0x3d, 0x3d, 0xf0, 0x87, 0xe0, 0xbf, 0x2b, 0x1e, 0x27, 0x7e, 0xe5, 0x5d, 0xdd, 0x36, 0xb6, 0x7f, 0xd3, 0xd0, 0xf3}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-openbsd-amd64", IDE: false}
	}
	if index == 14 {
		return Descriptor{Name: "netbsd/amd64", Backend: "netbsd/amd64", Aliases: []string(nil), Family: "native_v1", OS: "netbsd", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf", Runtime: []string{"read", "write", "open", "close", "read_at", "write_at", "chmod", "print", "exit", "hosted"}, Tags: []string{"amd64", "netbsd", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x74, 0xf4, 0x9b, 0x4, 0x97, 0x39, 0x61, 0xfc, 0x68, 0x11, 0x82, 0x5b, 0xda, 0x4a, 0x81, 0xcf, 0x81, 0x9d, 0x17, 0x7, 0xef, 0x8f, 0x5, 0xf9, 0xf2, 0x12, 0xf2, 0x2f, 0x75, 0x4c, 0xcf, 0x59}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-netbsd-amd64", IDE: false}
	}
	return Descriptor{}
}

func Binding(name string) (string, string, int, bool) {
	if name == "linux/amd64" {
		return "linux/amd64", "wӷUA65\v\xa9_\xf6\xe3\x86g\xd6UJp\x1cþ\x18\x1f\xb3\xe9\"7T\u0380#/", 3, true
	}
	if name == "linux/386" {
		return "linux/386", "\x1e\xd2A\xf1+&cc\xf9\xb3(0\xa2\xb5\xb9j<\x01\xe4\x0eLd\x8ch\x99\xf2X_o\x9a\xe7\x94", 3, true
	}
	if name == "linux/aarch64" {
		return "linux/aarch64", "J\xb4![\xa0\xc6G\xa0\xb8\xc4xbm\xcaz)\x18\xd6\xe0\x00\xb0\x90\xaf(#\xd6\t \xfb\x9a6|", 3, true
	}
	if name == "linux/arm" {
		return "linux/arm", "\xc6Α(\x066\xf1E\x15\xf2]V\xb5r|gFc\xf9\xadv\xbe\xa8}\x99t\xce\x1f\xd1+ef", 3, true
	}
	if name == "windows/amd64" {
		return "windows/amd64", "\brl\x8fX\xa0\vOFa\xb4n¬\xa7\x1dSd\xc4\xc7\n`ޚp\x19Gh\x05\xa2\x95D", 3, true
	}
	if name == "windows/386" {
		return "windows/386", ",\xd4\a\xe0\xe9(\n\xdb\x02\xf57\x89\x97YZ\xf9\x97\x0f\xb9\xfbh\x9a\xf2\x92\x1d\xf0\x10\xda\xc3\x12W\x7f", 3, true
	}
	if name == "windows/arm64" {
		return "windows/arm64", "\x8d\r\xe8\xa0ת>\xa4C6N\xde8X\xdb\xc0\x81>+\xa5\xdb\xcc3K\xb1\x9a\xaf\xb1\x85~\x18j", 3, true
	}
	if name == "darwin/arm64" {
		return "darwin/arm64", "\xe8!)f\x95\xf13Ǝ\xf4\x81\xc1`k\xb6\xd3{C\xba\xd9\xf1u\xcca\x1c{4\xeb\x00\x80\xd6;", 3, true
	}
	if name == "wasi/wasm32" {
		return "wasi/wasm32", "\xaa\x04J\xab}#\x99\nD\x93~\xd0\x12\r\xb2\xdfQ\xcd\xd5[(\r\xda_\xfe\x97\x8f\x88N\x8f\x1al", 3, true
	}
	if name == "browser/wasm32" {
		return "browser/wasm32", "\xcd/u\xab\te\xa2\x84\xb8\xf0\xf9\xd7-;\xbd)g\xdfo\xb3\xe93I\xbc\x15\xe5\x98\xeaNtK`", 3, true
	}
	if name == "vm/vm32" {
		return "vm/vm32", "\xd14\xe6\x10E\x15\x88\xc6\xc5F\x15D\x8d\x86RNo{Ke\x00\xa6\x7f\x8f\xdct\x17(\x95\xdb\xea\xc7", 3, true
	}
	if name == "linux-kernel/amd64" {
		return "linux-kernel/amd64", ":\x03\x91\xe9,\xa4\x02\a\x05u\x89uI0\x9dC\xab\x8b\xf2\xc7/\xd0HlĴ\xbd\x19\xfa$\xbd\xf2", 3, true
	}
	if name == "freebsd/amd64" {
		return "freebsd/amd64", "&\xf6IR\xf8'k4e\xa4\x8a\x8c\x81WM\x93)4\xc0Τ\x1b\xa2&RvD\xa3\xddKmj", 3, true
	}
	if name == "openbsd/amd64" {
		return "openbsd/amd64", "\x9e\x10lM_\xf2\"y){\xbc\xb8\x90==\xf0\x87\xe0\xbf+\x1e'~\xe5]\xdd6\xb6\x7f\xd3\xd0\xf3", 3, true
	}
	if name == "netbsd/amd64" {
		return "netbsd/amd64", "t\xf4\x9b\x04\x979a\xfch\x11\x82[\xdaJ\x81ρ\x9d\x17\a\xef\x8f\x05\xf9\xf2\x12\xf2/uL\xcfY", 3, true
	}
	return "", "", 0, false
}

func IsAdvertised(name string) bool {
	return name == "linux/amd64" || name == "linux/386" || name == "linux/aarch64" || name == "linux/arm" || name == "windows/amd64" || name == "windows/386" || name == "windows/arm64" || name == "darwin/arm64" || name == "wasi/wasm32" || name == "browser/wasm32" || name == "vm/vm32" || name == "freebsd/amd64" || name == "openbsd/amd64" || name == "netbsd/amd64"
}

func Backend(name string) string {
	if name == "browser/wasm32" {
		return "wasi/wasm32"
	}
	return name
}

func HasBuildTag(name string, tag string) bool {
	if name == "linux/amd64" {
		return tag == "amd64" || tag == "linux" || tag == "unix"
	}
	if name == "linux/386" {
		return tag == "386" || tag == "linux" || tag == "unix"
	}
	if name == "linux/aarch64" {
		return tag == "aarch64" || tag == "arm64" || tag == "linux" || tag == "unix"
	}
	if name == "linux/arm" {
		return tag == "arm" || tag == "linux" || tag == "unix"
	}
	if name == "windows/amd64" {
		return tag == "amd64" || tag == "windows"
	}
	if name == "windows/386" {
		return tag == "386" || tag == "windows"
	}
	if name == "windows/arm64" {
		return tag == "aarch64" || tag == "arm64" || tag == "windows"
	}
	if name == "darwin/arm64" {
		return tag == "aarch64" || tag == "arm64" || tag == "darwin" || tag == "unix"
	}
	if name == "wasi/wasm32" {
		return tag == "wasi" || tag == "wasip1" || tag == "wasm" || tag == "wasm32"
	}
	if name == "browser/wasm32" {
		return tag == "browser" || tag == "wasi" || tag == "wasip1" || tag == "wasm" || tag == "wasm32"
	}
	if name == "vm/vm32" {
		return tag == "vm" || tag == "vm32"
	}
	if name == "linux-kernel/amd64" {
		return tag == "amd64" || tag == "linux" || tag == "renvo_kernel" || tag == "unix"
	}
	if name == "freebsd/amd64" {
		return tag == "amd64" || tag == "freebsd" || tag == "unix"
	}
	if name == "openbsd/amd64" {
		return tag == "amd64" || tag == "openbsd" || tag == "unix"
	}
	if name == "netbsd/amd64" {
		return tag == "amd64" || tag == "netbsd" || tag == "unix"
	}
	return false
}

func HasCapability(name string, capability string) bool {
	if name == "linux/amd64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted" || capability == "linkstatic" || capability == "object"
	}
	if name == "linux/386" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "linux/aarch64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "linux/arm" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "windows/amd64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted" || capability == "imports" || capability == "linkstatic" || capability == "object" || capability == "windows_gui"
	}
	if name == "windows/386" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "windows/arm64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted" || capability == "windows_gui"
	}
	if name == "darwin/arm64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "wasi/wasm32" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "browser/wasm32" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "vm/vm32" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "linux-kernel/amd64" {
		return capability == "freestanding" || capability == "imports" || capability == "kernel_module" || capability == "linkstatic" || capability == "object"
	}
	if name == "freebsd/amd64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "openbsd/amd64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	if name == "netbsd/amd64" {
		return capability == "argv" || capability == "environment" || capability == "executable" || capability == "filesystem" || capability == "heap" || capability == "hosted"
	}
	return false
}

func SupportsInPlaceEntry(name string) bool { return false }

func DefaultArena(name string) int {
	if name == "browser/wasm32" {
		return 134217728
	}
	return 0
}

func IDETargets() []string {
	return []string{"windows/amd64", "windows/386", "windows/arm64", "darwin/arm64", "browser/wasm32"}
}
