// Code generated by go generate ./internal/targetinfo; DO NOT EDIT.

package targetinfo

const DefaultName = "linux/amd64"
const AdvertisedHelp = "linux/amd64 linux/386 linux/aarch64 linux/arm windows/amd64 windows/386 windows/arm64 darwin/arm64 wasi/wasm32 browser/wasm32 vm/vm32\n"
const descriptorCount = 12

func All() []Descriptor {
	out := make([]Descriptor, descriptorCount)
	for i := 0; i < len(out); i++ {
		out[i] = descriptorAt(i)
	}
	return out
}

func Lookup(name string) (Descriptor, bool) {
	if name == "linux/amd64" {
		return descriptorAt(0), true
	}
	if name == "linux/386" {
		return descriptorAt(1), true
	}
	if name == "linux/aarch64" {
		return descriptorAt(2), true
	}
	if name == "linux/arm" {
		return descriptorAt(3), true
	}
	if name == "windows/amd64" {
		return descriptorAt(4), true
	}
	if name == "windows/386" {
		return descriptorAt(5), true
	}
	if name == "windows/arm64" {
		return descriptorAt(6), true
	}
	if name == "darwin/arm64" {
		return descriptorAt(7), true
	}
	if name == "wasi/wasm32" {
		return descriptorAt(8), true
	}
	if name == "browser/wasm32" {
		return descriptorAt(9), true
	}
	if name == "vm/vm32" {
		return descriptorAt(10), true
	}
	if name == "linux-kernel/amd64" {
		return descriptorAt(11), true
	}
	return Descriptor{}, false
}

func descriptorAt(index int) Descriptor {
	if index == 0 {
		return Descriptor{Name: "linux/amd64", Backend: "linux/amd64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf", Runtime: []string{"read", "write", "open", "close", "read_at", "write_at", "chmod", "print", "exit", "hosted"}, Tags: []string{"amd64", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "linkstatic", "object"}, Definition: [32]uint8{0x2a, 0x2f, 0x7b, 0x5, 0x37, 0x7b, 0x16, 0x74, 0xbd, 0x66, 0x46, 0xa1, 0x51, 0xd2, 0x59, 0xf9, 0x19, 0xa7, 0x4a, 0xb2, 0x7c, 0x15, 0x7c, 0x67, 0xf, 0xdd, 0xbf, 0x2, 0x43, 0x72, 0x9b, 0x2f}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-amd64", IDE: false}
	}
	if index == 1 {
		return Descriptor{Name: "linux/386", Backend: "linux/386", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "386", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "cdecl32", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"386", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x7, 0x65, 0x8f, 0x1e, 0xab, 0x54, 0x8b, 0x57, 0x3d, 0x3a, 0xec, 0x7b, 0x9e, 0x74, 0x9f, 0x7c, 0x63, 0xd1, 0x70, 0x3a, 0x63, 0xf, 0x4, 0x6, 0x54, 0xdc, 0xfa, 0x5f, 0xaa, 0x25, 0x1e, 0x3c}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-386", IDE: false}
	}
	if index == 2 {
		return Descriptor{Name: "linux/aarch64", Backend: "linux/aarch64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "aapcs64", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"aarch64", "arm64", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x95, 0xc8, 0x81, 0x87, 0xcb, 0xe5, 0xf1, 0x93, 0x8c, 0x11, 0x79, 0xd6, 0xd, 0xa7, 0x50, 0x9f, 0x1b, 0xd1, 0x89, 0xf, 0x30, 0xe, 0x99, 0xa6, 0xf5, 0x2, 0x86, 0xa6, 0xc4, 0x6a, 0xd9, 0x6e}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-arm64", IDE: false}
	}
	if index == 3 {
		return Descriptor{Name: "linux/arm", Backend: "linux/arm", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "arm", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "aapcs32", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"arm", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x50, 0x9b, 0x2d, 0x3a, 0x1, 0xf3, 0x5e, 0x8, 0x7b, 0x43, 0xcc, 0x6, 0x29, 0x39, 0x6b, 0xaf, 0xa, 0xd1, 0xa7, 0x2f, 0xa3, 0xbd, 0xa7, 0xc1, 0x8a, 0x89, 0xd5, 0xfd, 0x77, 0x5c, 0x4f, 0x2a}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-arm", IDE: false}
	}
	if index == 4 {
		return Descriptor{Name: "windows/amd64", Backend: "windows/amd64", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "windows_x86_64", Image: "pe", Runtime: []string{"open", "close", "read", "write", "read_at", "write_at", "seek", "print", "chmod", "exit", "hosted"}, Tags: []string{"amd64", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "imports", "linkstatic", "object", "windows_gui"}, Definition: [32]uint8{0xa9, 0xe5, 0x21, 0x3e, 0x51, 0xf6, 0xf8, 0x56, 0x19, 0x5a, 0x91, 0x43, 0x5f, 0x9d, 0x58, 0x1f, 0xcb, 0x45, 0xec, 0x7, 0xde, 0x5, 0xd3, 0xeb, 0x98, 0xdc, 0xb0, 0x5b, 0xff, 0xcd, 0x8, 0x8d}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-amd64.exe", IDE: true}
	}
	if index == 5 {
		return Descriptor{Name: "windows/386", Backend: "windows/386", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "386", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "win32", Image: "pe", Runtime: []string{"print", "open", "close", "read", "write", "read_at", "write_at", "chmod", "hosted"}, Tags: []string{"386", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x7f, 0xae, 0x76, 0x95, 0xb7, 0xa3, 0xa1, 0x4c, 0xca, 0x2a, 0x41, 0xa4, 0x18, 0x25, 0x44, 0x70, 0x65, 0xb7, 0x85, 0x9a, 0x6c, 0x5d, 0xdf, 0xbc, 0x53, 0xfa, 0xbc, 0xc7, 0xf3, 0x44, 0x22, 0x20}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-386.exe", IDE: true}
	}
	if index == 6 {
		return Descriptor{Name: "windows/arm64", Backend: "windows/arm64", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "windows_arm64", Image: "pe", Runtime: []string{"print", "open", "close", "read", "write", "read_at", "write_at", "chmod", "hosted"}, Tags: []string{"aarch64", "arm64", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "windows_gui"}, Definition: [32]uint8{0x61, 0xcb, 0x1, 0xc, 0x86, 0xad, 0x3c, 0x71, 0x6, 0x7, 0x68, 0x86, 0x28, 0x14, 0xf8, 0x8d, 0xcb, 0x1a, 0x57, 0x78, 0x1f, 0x6c, 0x39, 0xf4, 0x62, 0xab, 0x4d, 0x5d, 0xc1, 0x52, 0x89, 0xac}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-arm64.exe", IDE: true}
	}
	if index == 7 {
		return Descriptor{Name: "darwin/arm64", Backend: "darwin/arm64", Aliases: []string(nil), Family: "native_v1", OS: "darwin", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "aapcs64", Image: "mach-o", Runtime: []string{"print", "open", "close", "read", "write", "read_at", "write_at", "chmod", "hosted"}, Tags: []string{"aarch64", "arm64", "darwin", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xad, 0xfe, 0xe6, 0x8f, 0x3d, 0x32, 0x2b, 0xbe, 0xc2, 0x80, 0x7e, 0xd0, 0xf, 0xb3, 0xde, 0x1b, 0xc5, 0x14, 0x9d, 0x4e, 0x24, 0xee, 0x22, 0x79, 0xed, 0x9b, 0x73, 0x60, 0x2b, 0x8f, 0xc0, 0x88}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-darwin-arm64", IDE: true}
	}
	if index == 8 {
		return Descriptor{Name: "wasi/wasm32", Backend: "wasi/wasm32", Aliases: []string(nil), Family: "structured32", OS: "wasi", ISA: "wasm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "wasm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"wasi", "wasip1", "wasm", "wasm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x91, 0x4d, 0xcb, 0x5a, 0x2b, 0xec, 0x10, 0xcd, 0xe4, 0x45, 0x7f, 0x7c, 0x40, 0x1, 0x95, 0xd7, 0x32, 0x98, 0x1f, 0xaf, 0xb4, 0xc8, 0x28, 0x9f, 0x9d, 0xae, 0x39, 0x84, 0xb0, 0xc3, 0xd1, 0x8b}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-wasi-wasm32.wasm", IDE: false}
	}
	if index == 9 {
		return Descriptor{Name: "browser/wasm32", Backend: "wasi/wasm32", Aliases: []string(nil), Family: "structured32", OS: "browser", ISA: "wasm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "html-wasm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"browser", "wasi", "wasip1", "wasm", "wasm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x6, 0xc6, 0x7, 0xa7, 0x29, 0x9c, 0xa0, 0x16, 0x7a, 0x84, 0x90, 0xfa, 0x40, 0xf1, 0x91, 0x1a, 0xd4, 0xe, 0x2b, 0x71, 0x68, 0xf0, 0x22, 0xac, 0x82, 0x70, 0x11, 0xf7, 0xfe, 0x70, 0xcd, 0x12}, DescriptorVersion: 3, Advertised: true, Virtual: true, DefaultArena: 134217728, ReleaseArtifact: "", IDE: true}
	}
	if index == 10 {
		return Descriptor{Name: "vm/vm32", Backend: "vm/vm32", Aliases: []string(nil), Family: "structured32", OS: "vm", ISA: "vm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "rnvm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"vm", "vm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xa1, 0xf9, 0x2a, 0xb6, 0x91, 0x10, 0xf5, 0x9, 0xdd, 0x6b, 0xc6, 0xbd, 0x24, 0xa4, 0x8f, 0x7c, 0x0, 0xdc, 0x96, 0xa8, 0xe2, 0x68, 0xd2, 0x60, 0xf5, 0xba, 0x87, 0x55, 0x52, 0x24, 0xab, 0x21}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-vm32.rnvb", IDE: false}
	}
	if index == 11 {
		return Descriptor{Name: "linux-kernel/amd64", Backend: "linux-kernel/amd64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf-relocatable", Runtime: []string{"print", "open", "close", "read", "write", "chmod"}, Tags: []string{"amd64", "linux", "renvo_kernel", "unix"}, Capabilities: []string{"freestanding", "imports", "kernel_module", "linkstatic", "object"}, Definition: [32]uint8{0x31, 0xdc, 0x8b, 0xa2, 0xba, 0x24, 0xfd, 0xd1, 0x62, 0xf3, 0x91, 0x12, 0xa1, 0x8e, 0xe, 0x1f, 0xc6, 0xb4, 0x9f, 0xb8, 0xae, 0x93, 0x2e, 0x64, 0xde, 0xaf, 0xdf, 0x2e, 0x35, 0x1e, 0x92, 0x7c}, DescriptorVersion: 3, Advertised: false, Virtual: false, DefaultArena: 0, ReleaseArtifact: "", IDE: false}
	}
	return Descriptor{}
}

func Binding(name string) (string, string, int, bool) {
	if name == "linux/amd64" {
		return "linux/amd64", "*/{\x057{\x16t\xbdfF\xa1Q\xd2Y\xf9\x19\xa7J\xb2|\x15|g\x0fݿ\x02Cr\x9b/", 3, true
	}
	if name == "linux/386" {
		return "linux/386", "\ae\x8f\x1e\xabT\x8bW=:\xec{\x9et\x9f|c\xd1p:c\x0f\x04\x06T\xdc\xfa_\xaa%\x1e<", 3, true
	}
	if name == "linux/aarch64" {
		return "linux/aarch64", "\x95ȁ\x87\xcb\xe5\xf1\x93\x8c\x11y\xd6\r\xa7P\x9f\x1bщ\x0f0\x0e\x99\xa6\xf5\x02\x86\xa6\xc4j\xd9n", 3, true
	}
	if name == "linux/arm" {
		return "linux/arm", "P\x9b-:\x01\xf3^\b{C\xcc\x06)9k\xaf\nѧ/\xa3\xbd\xa7\xc1\x8a\x89\xd5\xfdw\\O*", 3, true
	}
	if name == "windows/amd64" {
		return "windows/amd64", "\xa9\xe5!>Q\xf6\xf8V\x19Z\x91C_\x9dX\x1f\xcbE\xec\a\xde\x05\xd3\xeb\x98ܰ[\xff\xcd\b\x8d", 3, true
	}
	if name == "windows/386" {
		return "windows/386", "\x7f\xaev\x95\xb7\xa3\xa1L\xca*A\xa4\x18%Dpe\xb7\x85\x9al]\u07fcS\xfa\xbc\xc7\xf3D\" ", 3, true
	}
	if name == "windows/arm64" {
		return "windows/arm64", "a\xcb\x01\f\x86\xad<q\x06\ah\x86(\x14\xf8\x8d\xcb\x1aWx\x1fl9\xf4b\xabM]\xc1R\x89\xac", 3, true
	}
	if name == "darwin/arm64" {
		return "darwin/arm64", "\xad\xfe\xe6\x8f=2+\xbe\u0080~\xd0\x0f\xb3\xde\x1b\xc5\x14\x9dN$\xee\"y\xed\x9bs`+\x8f\xc0\x88", 3, true
	}
	if name == "wasi/wasm32" {
		return "wasi/wasm32", "\x91M\xcbZ+\xec\x10\xcd\xe4E\x7f|@\x01\x95\xd72\x98\x1f\xaf\xb4\xc8(\x9f\x9d\xae9\x84\xb0\xc3ы", 3, true
	}
	if name == "browser/wasm32" {
		return "browser/wasm32", "\x06\xc6\a\xa7)\x9c\xa0\x16z\x84\x90\xfa@\xf1\x91\x1a\xd4\x0e+qh\xf0\"\xac\x82p\x11\xf7\xfep\xcd\x12", 3, true
	}
	if name == "vm/vm32" {
		return "vm/vm32", "\xa1\xf9*\xb6\x91\x10\xf5\t\xddkƽ$\xa4\x8f|\x00ܖ\xa8\xe2h\xd2`\xf5\xba\x87UR$\xab!", 3, true
	}
	if name == "linux-kernel/amd64" {
		return "linux-kernel/amd64", "1܋\xa2\xba$\xfd\xd1b\xf3\x91\x12\xa1\x8e\x0e\x1fƴ\x9f\xb8\xae\x93.dޯ\xdf.5\x1e\x92|", 3, true
	}
	return "", "", 0, false
}

func IsAdvertised(name string) bool {
	return name == "linux/amd64" || name == "linux/386" || name == "linux/aarch64" || name == "linux/arm" || name == "windows/amd64" || name == "windows/386" || name == "windows/arm64" || name == "darwin/arm64" || name == "wasi/wasm32" || name == "browser/wasm32" || name == "vm/vm32"
}

func Backend(name string) string {
	if name == "browser/wasm32" {
		return "wasi/wasm32"
	}
	return name
}

func HasBuildTag(name string, tag string) bool {
	if name == "linux/amd64" {
		return tag == "amd64" || tag == "linux" || tag == "unix"
	}
	if name == "linux/386" {
		return tag == "386" || tag == "linux" || tag == "unix"
	}
	if name == "linux/aarch64" {
		return tag == "aarch64" || tag == "arm64" || tag == "linux" || tag == "unix"
	}
	if name == "linux/arm" {
		return tag == "arm" || tag == "linux" || tag == "unix"
	}
	if name == "windows/amd64" {
		return tag == "amd64" || tag == "windows"
	}
	if name == "windows/386" {
		return tag == "386" || tag == "windows"
	}
	if name == "windows/arm64" {
		return tag == "aarch64" || tag == "arm64" || tag == "windows"
	}
	if name == "darwin/arm64" {
		return tag == "aarch64" || tag == "arm64" || tag == "darwin" || tag == "unix"
	}
	if name == "wasi/wasm32" {
		return tag == "wasi" || tag == "wasip1" || tag == "wasm" || tag == "wasm32"
	}
	if name == "browser/wasm32" {
		return tag == "browser" || tag == "wasi" || tag == "wasip1" || tag == "wasm" || tag == "wasm32"
	}
	if name == "vm/vm32" {
		return tag == "vm" || tag == "vm32"
	}
	if name == "linux-kernel/amd64" {
		return tag == "amd64" || tag == "linux" || tag == "renvo_kernel" || tag == "unix"
	}
	return false
}

func DefaultArena(name string) int {
	if name == "browser/wasm32" {
		return 134217728
	}
	return 0
}

func IDETargets() []string {
	return []string{"windows/amd64", "windows/386", "windows/arm64", "darwin/arm64", "browser/wasm32"}
}
