// Code generated by go generate ./internal/targetinfo; DO NOT EDIT.

package targetinfo

const DefaultName = "linux/amd64"
const AdvertisedHelp = "linux/amd64 linux/386 linux/aarch64 linux/arm windows/amd64 windows/386 windows/arm64 darwin/arm64 wasi/wasm32 browser/wasm32 vm/vm32\n"
const descriptorCount = 12

func All() []Descriptor {
	out := make([]Descriptor, descriptorCount)
	for i := 0; i < len(out); i++ {
		out[i] = descriptorAt(i)
	}
	return out
}

func Lookup(name string) (Descriptor, bool) {
	if name == "linux/amd64" {
		return descriptorAt(0), true
	}
	if name == "linux/386" {
		return descriptorAt(1), true
	}
	if name == "linux/aarch64" {
		return descriptorAt(2), true
	}
	if name == "linux/arm" {
		return descriptorAt(3), true
	}
	if name == "windows/amd64" {
		return descriptorAt(4), true
	}
	if name == "windows/386" {
		return descriptorAt(5), true
	}
	if name == "windows/arm64" {
		return descriptorAt(6), true
	}
	if name == "darwin/arm64" {
		return descriptorAt(7), true
	}
	if name == "wasi/wasm32" {
		return descriptorAt(8), true
	}
	if name == "browser/wasm32" {
		return descriptorAt(9), true
	}
	if name == "vm/vm32" {
		return descriptorAt(10), true
	}
	if name == "linux-kernel/amd64" {
		return descriptorAt(11), true
	}
	return Descriptor{}, false
}

func descriptorAt(index int) Descriptor {
	if index == 0 {
		return Descriptor{Name: "linux/amd64", Backend: "linux/amd64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf", Runtime: []string{"read", "write", "open", "close", "read_at", "write_at", "chmod", "print", "exit", "hosted"}, Tags: []string{"amd64", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "linkstatic", "object"}, Definition: [32]uint8{0xff, 0xa2, 0x22, 0xc0, 0xcf, 0x9, 0x4, 0xac, 0x1b, 0x67, 0x92, 0xe9, 0x3c, 0xbf, 0xef, 0xa1, 0x12, 0x57, 0x85, 0x2f, 0x18, 0x5e, 0x9d, 0x6a, 0xfa, 0x81, 0x6d, 0xfc, 0x62, 0x6a, 0x4e, 0xfc}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-amd64", IDE: false}
	}
	if index == 1 {
		return Descriptor{Name: "linux/386", Backend: "linux/386", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "386", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "cdecl32", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"386", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xec, 0x4a, 0x23, 0x58, 0x99, 0xe5, 0xd9, 0x21, 0xf4, 0x32, 0x95, 0x20, 0xbf, 0x63, 0xd9, 0xde, 0xaa, 0x4a, 0x25, 0xaf, 0x62, 0xc4, 0xe7, 0xa9, 0x6e, 0x9f, 0xdf, 0xac, 0x7, 0x44, 0x46, 0x77}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-386", IDE: false}
	}
	if index == 2 {
		return Descriptor{Name: "linux/aarch64", Backend: "linux/aarch64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "aapcs64", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"aarch64", "arm64", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xab, 0x83, 0xbf, 0x3e, 0x21, 0xc, 0xf2, 0x42, 0xe3, 0x23, 0x3e, 0xba, 0x6e, 0x8e, 0xfe, 0x4, 0x6e, 0x1b, 0x5d, 0x7b, 0xa4, 0x1a, 0xf6, 0x9f, 0x43, 0xed, 0xd, 0xf3, 0x18, 0xee, 0x33, 0xe6}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-arm64", IDE: false}
	}
	if index == 3 {
		return Descriptor{Name: "linux/arm", Backend: "linux/arm", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "arm", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "aapcs32", Image: "elf", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "exit", "hosted"}, Tags: []string{"arm", "linux", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x97, 0x68, 0x56, 0x9e, 0x2a, 0xc3, 0xfb, 0xad, 0x84, 0xb, 0xb6, 0xb3, 0x25, 0xf4, 0xe1, 0xbe, 0x73, 0x7e, 0xd9, 0x7e, 0x45, 0x9b, 0x51, 0x90, 0x49, 0x18, 0xd1, 0x25, 0x3d, 0xfd, 0x2e, 0x93}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-linux-arm", IDE: false}
	}
	if index == 4 {
		return Descriptor{Name: "windows/amd64", Backend: "windows/amd64", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "windows_x86_64", Image: "pe", Runtime: []string{"open", "close", "read", "write", "read_at", "write_at", "seek", "print", "chmod", "exit", "hosted"}, Tags: []string{"amd64", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "imports", "linkstatic", "object", "windows_gui"}, Definition: [32]uint8{0xb0, 0xd6, 0xc2, 0x66, 0x62, 0x12, 0x3d, 0xed, 0x73, 0x5b, 0x49, 0x5a, 0xae, 0xfe, 0x65, 0x9d, 0x34, 0x72, 0xde, 0xdb, 0xf2, 0x82, 0x39, 0x51, 0xae, 0x70, 0x37, 0x21, 0x4d, 0x99, 0x42, 0x2a}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-amd64.exe", IDE: true}
	}
	if index == 5 {
		return Descriptor{Name: "windows/386", Backend: "windows/386", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "386", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 4, Endian: "little", ABI: "win32", Image: "pe", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"386", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x5, 0x6b, 0xa4, 0x99, 0x32, 0xa6, 0xaf, 0xe9, 0x2e, 0x7a, 0x98, 0x98, 0x6c, 0x4f, 0x7f, 0xab, 0xfe, 0xd5, 0x6c, 0xe7, 0x2f, 0x8d, 0x87, 0x33, 0x9f, 0x1d, 0xa1, 0xf7, 0x64, 0x1f, 0x24, 0x1c}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-386.exe", IDE: true}
	}
	if index == 6 {
		return Descriptor{Name: "windows/arm64", Backend: "windows/arm64", Aliases: []string(nil), Family: "native_v1", OS: "windows", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "windows_arm64", Image: "pe", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"aarch64", "arm64", "windows"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted", "windows_gui"}, Definition: [32]uint8{0xdb, 0x94, 0x51, 0xf7, 0x8e, 0x2e, 0xe3, 0xe5, 0x91, 0xe8, 0xca, 0xbb, 0x4b, 0x35, 0x60, 0x1b, 0xf7, 0xec, 0xd0, 0xdd, 0xee, 0xb, 0x67, 0x49, 0x86, 0x94, 0xfd, 0xff, 0x95, 0x41, 0x13, 0x23}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-windows-arm64.exe", IDE: true}
	}
	if index == 7 {
		return Descriptor{Name: "darwin/arm64", Backend: "darwin/arm64", Aliases: []string(nil), Family: "native_v1", OS: "darwin", ISA: "aarch64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "aapcs64", Image: "mach-o", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"aarch64", "arm64", "darwin", "unix"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x9c, 0xeb, 0x31, 0x8d, 0xf7, 0x45, 0x2f, 0x90, 0x7e, 0xff, 0x9a, 0x88, 0x11, 0xef, 0x7f, 0x14, 0x2b, 0xf0, 0xd7, 0xe4, 0xed, 0x66, 0xe3, 0xb9, 0x9d, 0x69, 0x12, 0xf0, 0xf0, 0x30, 0x9f, 0xdf}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-darwin-arm64", IDE: true}
	}
	if index == 8 {
		return Descriptor{Name: "wasi/wasm32", Backend: "wasi/wasm32", Aliases: []string(nil), Family: "structured32", OS: "wasi", ISA: "wasm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "wasm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"wasi", "wasip1", "wasm", "wasm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x9e, 0xcd, 0x63, 0x86, 0x32, 0xfb, 0x98, 0xe7, 0xfb, 0xf8, 0x16, 0xdc, 0x94, 0xc4, 0x3e, 0xf2, 0x4, 0x65, 0xf5, 0xb5, 0xad, 0x1c, 0x28, 0xe4, 0x72, 0x15, 0x74, 0xf7, 0x55, 0x48, 0x6c, 0x29}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-wasi-wasm32.wasm", IDE: false}
	}
	if index == 9 {
		return Descriptor{Name: "browser/wasm32", Backend: "wasi/wasm32", Aliases: []string(nil), Family: "structured32", OS: "browser", ISA: "wasm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "html-wasm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"browser", "wasi", "wasip1", "wasm", "wasm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0xfb, 0x9e, 0x81, 0xaf, 0x3c, 0xfb, 0x70, 0x50, 0xd6, 0x8e, 0xf0, 0xec, 0x87, 0x8e, 0x65, 0x72, 0x79, 0x43, 0x8c, 0x3, 0xe0, 0xaa, 0xb5, 0xff, 0x37, 0xad, 0xb2, 0xa5, 0x30, 0x75, 0x63, 0x4b}, DescriptorVersion: 3, Advertised: true, Virtual: true, DefaultArena: 134217728, ReleaseArtifact: "", IDE: true}
	}
	if index == 10 {
		return Descriptor{Name: "vm/vm32", Backend: "vm/vm32", Aliases: []string(nil), Family: "structured32", OS: "vm", ISA: "vm32", WordBits: 32, PointerBits: 32, CodePointerBits: 32, FunctionPointerBits: 32, MaxAlign: 8, Endian: "little", ABI: "vm32_internal", Image: "rnvm", Runtime: []string{"read", "write", "read_at", "write_at", "open", "close", "chmod", "print", "hosted"}, Tags: []string{"vm", "vm32"}, Capabilities: []string{"argv", "environment", "executable", "filesystem", "heap", "hosted"}, Definition: [32]uint8{0x37, 0x9c, 0xd7, 0x21, 0x3b, 0xcc, 0xc1, 0xa9, 0xb8, 0xb7, 0xe1, 0x5, 0xc3, 0xbf, 0xcc, 0xf0, 0x52, 0xd2, 0x1f, 0xf, 0xf9, 0x40, 0x34, 0x2d, 0xfd, 0x11, 0xf1, 0x66, 0xc, 0xd7, 0x67, 0xc5}, DescriptorVersion: 3, Advertised: true, Virtual: false, DefaultArena: 0, ReleaseArtifact: "renvo-vm32.rnvb", IDE: false}
	}
	if index == 11 {
		return Descriptor{Name: "linux-kernel/amd64", Backend: "linux-kernel/amd64", Aliases: []string(nil), Family: "native_v1", OS: "linux", ISA: "amd64", WordBits: 64, PointerBits: 64, CodePointerBits: 64, FunctionPointerBits: 64, MaxAlign: 8, Endian: "little", ABI: "sysv_x86_64", Image: "elf-relocatable", Runtime: []string{"print", "open", "close", "read", "write", "chmod"}, Tags: []string{"amd64", "linux", "renvo_kernel", "unix"}, Capabilities: []string{"freestanding", "imports", "kernel_module", "linkstatic", "object"}, Definition: [32]uint8{0x14, 0x43, 0xa8, 0x17, 0x49, 0x4e, 0xf4, 0x6f, 0x9d, 0x8c, 0x8, 0x53, 0x3b, 0x31, 0xc1, 0x1f, 0x8e, 0xe6, 0xf9, 0x51, 0xc, 0x34, 0xe8, 0x71, 0x17, 0x81, 0x4, 0x6e, 0x2c, 0x13, 0x99, 0xaa}, DescriptorVersion: 3, Advertised: false, Virtual: false, DefaultArena: 0, ReleaseArtifact: "", IDE: false}
	}
	return Descriptor{}
}

func Binding(name string) (string, string, int, bool) {
	if name == "linux/amd64" {
		return "linux/amd64", "\xff\xa2\"\xc0\xcf\t\x04\xac\x1bg\x92\xe9<\xbf\xef\xa1\x12W\x85/\x18^\x9dj\xfa\x81m\xfcbjN\xfc", 3, true
	}
	if name == "linux/386" {
		return "linux/386", "\xecJ#X\x99\xe5\xd9!\xf42\x95 \xbfc\xd9ުJ%\xafb\xc4\xe7\xa9n\x9f߬\aDFw", 3, true
	}
	if name == "linux/aarch64" {
		return "linux/aarch64", "\xab\x83\xbf>!\f\xf2B\xe3#>\xban\x8e\xfe\x04n\x1b]{\xa4\x1a\xf6\x9fC\xed\r\xf3\x18\xee3\xe6", 3, true
	}
	if name == "linux/arm" {
		return "linux/arm", "\x97hV\x9e*\xc3\xfb\xad\x84\v\xb6\xb3%\xf4\xe1\xbes~\xd9~E\x9bQ\x90I\x18\xd1%=\xfd.\x93", 3, true
	}
	if name == "windows/amd64" {
		return "windows/amd64", "\xb0\xd6\xc2fb\x12=\xeds[IZ\xae\xfee\x9d4r\xde\xdb\xf2\x829Q\xaep7!M\x99B*", 3, true
	}
	if name == "windows/386" {
		return "windows/386", "\x05k\xa4\x992\xa6\xaf\xe9.z\x98\x98lO\x7f\xab\xfe\xd5l\xe7/\x8d\x873\x9f\x1d\xa1\xf7d\x1f$\x1c", 3, true
	}
	if name == "windows/arm64" {
		return "windows/arm64", "۔Q\xf7\x8e.\xe3\xe5\x91\xe8ʻK5`\x1b\xf7\xec\xd0\xdd\xee\vgI\x86\x94\xfd\xff\x95A\x13#", 3, true
	}
	if name == "darwin/arm64" {
		return "darwin/arm64", "\x9c\xeb1\x8d\xf7E/\x90~\xff\x9a\x88\x11\xef\x7f\x14+\xf0\xd7\xe4\xedf㹝i\x12\xf0\xf00\x9f\xdf", 3, true
	}
	if name == "wasi/wasm32" {
		return "wasi/wasm32", "\x9e\xcdc\x862\xfb\x98\xe7\xfb\xf8\x16ܔ\xc4>\xf2\x04e\xf5\xb5\xad\x1c(\xe4r\x15t\xf7UHl)", 3, true
	}
	if name == "browser/wasm32" {
		return "browser/wasm32", "\xfb\x9e\x81\xaf<\xfbpP֎\xf0쇎eryC\x8c\x03વ\xff7\xad\xb2\xa50ucK", 3, true
	}
	if name == "vm/vm32" {
		return "vm/vm32", "7\x9c\xd7!;\xcc\xc1\xa9\xb8\xb7\xe1\x05ÿ\xcc\xf0R\xd2\x1f\x0f\xf9@4-\xfd\x11\xf1f\f\xd7g\xc5", 3, true
	}
	if name == "linux-kernel/amd64" {
		return "linux-kernel/amd64", "\x14C\xa8\x17IN\xf4o\x9d\x8c\bS;1\xc1\x1f\x8e\xe6\xf9Q\f4\xe8q\x17\x81\x04n,\x13\x99\xaa", 3, true
	}
	return "", "", 0, false
}

func IsAdvertised(name string) bool {
	return name == "linux/amd64" || name == "linux/386" || name == "linux/aarch64" || name == "linux/arm" || name == "windows/amd64" || name == "windows/386" || name == "windows/arm64" || name == "darwin/arm64" || name == "wasi/wasm32" || name == "browser/wasm32" || name == "vm/vm32"
}

func Backend(name string) string {
	if name == "browser/wasm32" {
		return "wasi/wasm32"
	}
	return name
}

func HasBuildTag(name string, tag string) bool {
	if name == "linux/amd64" {
		return tag == "amd64" || tag == "linux" || tag == "unix"
	}
	if name == "linux/386" {
		return tag == "386" || tag == "linux" || tag == "unix"
	}
	if name == "linux/aarch64" {
		return tag == "aarch64" || tag == "arm64" || tag == "linux" || tag == "unix"
	}
	if name == "linux/arm" {
		return tag == "arm" || tag == "linux" || tag == "unix"
	}
	if name == "windows/amd64" {
		return tag == "amd64" || tag == "windows"
	}
	if name == "windows/386" {
		return tag == "386" || tag == "windows"
	}
	if name == "windows/arm64" {
		return tag == "aarch64" || tag == "arm64" || tag == "windows"
	}
	if name == "darwin/arm64" {
		return tag == "aarch64" || tag == "arm64" || tag == "darwin" || tag == "unix"
	}
	if name == "wasi/wasm32" {
		return tag == "wasi" || tag == "wasip1" || tag == "wasm" || tag == "wasm32"
	}
	if name == "browser/wasm32" {
		return tag == "browser" || tag == "wasi" || tag == "wasip1" || tag == "wasm" || tag == "wasm32"
	}
	if name == "vm/vm32" {
		return tag == "vm" || tag == "vm32"
	}
	if name == "linux-kernel/amd64" {
		return tag == "amd64" || tag == "linux" || tag == "renvo_kernel" || tag == "unix"
	}
	return false
}

func DefaultArena(name string) int {
	if name == "browser/wasm32" {
		return 134217728
	}
	return 0
}

func IDETargets() []string {
	return []string{"windows/amd64", "windows/386", "windows/arm64", "darwin/arm64", "browser/wasm32"}
}
