// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: windows/amd64
// unit: amd64 0654e78bb5756db6c20069943cc3d3b0afb801942fe303215fa8e12ace4c51b5
package main


func compileWindowsAmd64(input []int, output int) int {
	return compileWindowsAmd64Arena(input, output, 0)
}

func compileWindowsAmd64Arena(input []int, output int, arenaSize int) int {
	renvoSetTarget(renvoTargetWindowsAmd64)
	return renvoCompileAmd64(input, output, arenaSize)
}

func renvoAsmBuildWindowsArgvEnvSlicesAmd64(a *renvoAsm, bssOff int, argsTextOff int, argsLenOff int, envOff int, envLenOff int) {
	renvoNonNil(a)
	// This pre-relaxed instruction template is invariant except for its import
	// and BSS operands, whose relocations are recorded immediately after it.
	base := len(a.code)
	renvoAsmEmitText(a, "\x48\x83\xec\x28\xff\x15\x00\x00\x00\x00\x48\x83\xc4\x28\x48\x89\xc6\x4c\x8d\x15\x00\x00\x00\x00\x48\x8d\x05\x00\x00\x00\x00\x50\x5a\x4d\x31\xdb\x80\x3e\x00\x0f\x84\x62\x00\x00\x00\x80\x3e\x20\x74\x05\x80\x3e\x09\x75\x05\x48\xff\xc6\xeb\xe8\x49\x89\x12\x31\xc9\x45\x31\xc0\x8a\x06\x3c\x00\x74\x28\x3c\x22\x75\x09\x41\x83\xf0\x01\x48\xff\xc6\xeb\xed\x41\x83\xf8\x00\x75\x08\x3c\x20\x74\x11\x3c\x09\x74\x0d\x88\x02\x48\xff\xc6\x48\xff\xc2\x48\xff\xc1\xeb\xd2\xc6\x02\x00\x48\xff\xc2\x49\x89\x4a\x08\x49\x83\xc2\x10\x49\xff\xc3\x3c\x00\x74\x08\x48\xff\xc6\xe9\x95\xff\xff\xff\x4c\x89\xd8\x48\x89\x05\x00\x00\x00\x00\x48\x83\xec\x28\xff\x15\x00\x00\x00\x00\x48\x83\xc4\x28\x48\x89\xc6\x4c\x8d\x15\x00\x00\x00\x00\x4d\x31\xdb\x80\x3e\x00\x74\x23\x49\x89\x32\x31\xc9\x80\x3c\x0e\x00\x74\x05\x48\xff\xc1\xeb\xf5\x49\x89\x4a\x08\x48\x01\xce\x48\xff\xc6\x49\x83\xc2\x10\x49\xff\xc3\xeb\xd8\x4c\x89\xd8\x48\x89\x05\x00\x00\x00\x00\x48\x8d\x05\x00\x00\x00\x00\x50\x5f\x48\x8b\x05\x00\x00\x00\x00\x50\x5e\x50\x5a\x48\x8d\x05\x00\x00\x00\x00\x50\x59\x48\x8b\x05\x00\x00\x00\x00\x49\x89\xc0\x49\x89\xc1")
	renvoAsmAddWinImportReloc(a, base+6, renvoWinImportGetCommandLineA)
	renvoAsmAddAbsReloc(a, base+20, bssOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+27, argsTextOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+149, argsLenOff, renvoAbsBssReloc)
	renvoAsmAddWinImportReloc(a, base+159, renvoWinImportGetEnvironmentStringsA)
	renvoAsmAddAbsReloc(a, base+173, envOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+226, envLenOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+233, bssOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+242, argsLenOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+253, envOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+262, envLenOff, renvoAbsBssReloc)
}

func renvoAsmImageWindowsAmd64(a *renvoAsm) []byte {
	renvoNonNil(a)
	for (a.codeOffset+len(a.code))%8 != 0 {
		a.code = append(a.code, 0)
	}
	textVirtualSize := len(a.code)
	textRawSize := renvoAlignValue(textVirtualSize, renvoWinFileAlign)
	dataRVA := renvoAlignValue(a.codeOffset+textVirtualSize, renvoWinSectionAlign)
	a.dataOffset = dataRVA
	var imports renvoWinImportLayout
	if renvoAsmHasWinImportRelocs(a) {
		renvoAppendWinImports(a, &imports)
	}
	renvoAsmPatchWindows(a, imports)
	dataRawSize := renvoAlignValue(len(a.data), renvoWinFileAlign)
	dataVirtualSize := len(a.data) + a.bssSize
	iatSize := 0
	if imports.kernelIATRVA != 0 {
		iatSize = (renvoWinImportFixedCount + 1) * imports.thunkSize
	}
	var out []byte
	out = renvoAppendPEHeader64WithContext(a.c, out, textRawSize, textVirtualSize, dataRVA, dataRawSize, dataVirtualSize, imports.importRVA, imports.importSize, imports.kernelIATRVA, iatSize)
	for i := 0; i < len(a.code); i++ {
		out = append(out, a.code[i])
	}
	out = renvoAppendUntil(out, renvoWinHeadersSize+textRawSize)
	for i := 0; i < len(a.data); i++ {
		out = append(out, a.data[i])
	}
	out = renvoAppendUntil(out, renvoWinHeadersSize+textRawSize+dataRawSize)
	if renvoFixedTarget == 0 && a.c.emitImage {
		return renvoAppendReplLinkTable(out, a)
	}
	return out
}
