// Code generated by renvoschemagen; DO NOT EDIT.
// schema-sha256: 2893bcdeda6eb5183eeaa5a8211136e37cd450da4f60e021e17f3dffcad0c81c

package main

const (
	renvoUnitMagic              = "RNVO"
	renvoUnitVersion            = 1
	renvoUnitTagUnit            = 1
	renvoUnitTagPackage         = 2
	renvoUnitTagImportPath      = 3
	renvoUnitTagText            = 7
	renvoUnitTagTokens          = 8
	renvoUnitTagDecls           = 9
	renvoUnitTagFuncs           = 10
	renvoUnitTagIndexes         = 11
	renvoUnitTagComps           = 12
	renvoUnitTagAssigns         = 13
	renvoUnitTagReturns         = 14
	renvoUnitTagCalls           = 15
	renvoUnitTagRefs            = 16
	renvoUnitTagSels            = 17
	renvoUnitTagTypes           = 18
	renvoUnitTagTypeRefs        = 19
	renvoUnitTagLocals          = 20
	renvoUnitTagSigs            = 21
	renvoUnitTagDeclMeta        = 22
	renvoUnitTagImports         = 23
	renvoUnitTagSymbols         = 24
	renvoUnitTagInitOrder       = 25
	renvoUnitTagConsts          = 26
	renvoUnitTagTypeFields      = 27
	renvoUnitTagTypeIfaces      = 28
	renvoUnitTagMethods         = 29
	renvoUnitTagTypeFuncs       = 30
	renvoUnitTagStmts           = 31
	renvoUnitTagPackages        = 32
	renvoUnitTagRTGAssembly     = 33
	renvoUnitTagEntrypoint      = 34
	renvoUnitTagForeignPrograms = 35
)

func renvoUnitChildTagIndex(tag int) int {
	if tag >= renvoUnitTagPackage && tag <= renvoUnitTagImportPath {
		return tag - 2
	}
	if tag >= renvoUnitTagText && tag <= renvoUnitTagForeignPrograms {
		return tag - 5
	}
	return -1
}

const renvoUnitRequiredChildMaskLow = 63
const renvoUnitRequiredChildMaskHigh = 0
