// Code generated by go generate ./internal/targetinfo; DO NOT EDIT.

package main

const renvoSupportedTargets = "linux/amd64, linux/386, linux/aarch64, linux/arm, windows/amd64, windows/386, windows/arm64, darwin/arm64, wasi/wasm32, vm/vm32, freebsd/amd64, openbsd/amd64, netbsd/amd64"

func renvoParseTargetArg(target string) int {
	if target == "linux/amd64" {
		return renvoTargetLinuxAmd64
	}
	if target == "linux/386" {
		return renvoTargetLinux386
	}
	if target == "linux/aarch64" {
		return renvoTargetLinuxAarch64
	}
	if target == "linux/arm" {
		return renvoTargetLinuxArm
	}
	if target == "windows/amd64" {
		return renvoTargetWindowsAmd64
	}
	if target == "windows/386" {
		return renvoTargetWindows386
	}
	if target == "wasi/wasm32" {
		return renvoTargetWasiWasm32
	}
	if target == "darwin/arm64" {
		return renvoTargetDarwinArm64
	}
	if target == "linux-kernel/amd64" {
		return renvoTargetLinuxKernelAmd64
	}
	if target == "windows/arm64" {
		return renvoTargetWindowsArm64
	}
	if target == "vm/vm32" {
		return renvoTargetVM32
	}
	if target == "freebsd/amd64" {
		return renvoTargetFreeBSDAmd64
	}
	if target == "openbsd/amd64" {
		return renvoTargetOpenBSDAmd64
	}
	if target == "netbsd/amd64" {
		return renvoTargetNetBSDAmd64
	}
	return renvoRTGParseTargetArg(target)
}

func renvoBuiltInTargetBinding(target int) (string, string, int, bool) {
	if target == renvoTargetLinuxAmd64 {
		return "linux/amd64", "wӷUA65\v\xa9_\xf6\xe3\x86g\xd6UJp\x1cþ\x18\x1f\xb3\xe9\"7T\u0380#/", 3, true
	}
	if target == renvoTargetLinux386 {
		return "linux/386", "\x1e\xd2A\xf1+&cc\xf9\xb3(0\xa2\xb5\xb9j<\x01\xe4\x0eLd\x8ch\x99\xf2X_o\x9a\xe7\x94", 3, true
	}
	if target == renvoTargetLinuxAarch64 {
		return "linux/aarch64", "J\xb4![\xa0\xc6G\xa0\xb8\xc4xbm\xcaz)\x18\xd6\xe0\x00\xb0\x90\xaf(#\xd6\t \xfb\x9a6|", 3, true
	}
	if target == renvoTargetLinuxArm {
		return "linux/arm", "\xc6Α(\x066\xf1E\x15\xf2]V\xb5r|gFc\xf9\xadv\xbe\xa8}\x99t\xce\x1f\xd1+ef", 3, true
	}
	if target == renvoTargetWindowsAmd64 {
		return "windows/amd64", "\brl\x8fX\xa0\vOFa\xb4n¬\xa7\x1dSd\xc4\xc7\n`ޚp\x19Gh\x05\xa2\x95D", 3, true
	}
	if target == renvoTargetWindows386 {
		return "windows/386", ",\xd4\a\xe0\xe9(\n\xdb\x02\xf57\x89\x97YZ\xf9\x97\x0f\xb9\xfbh\x9a\xf2\x92\x1d\xf0\x10\xda\xc3\x12W\x7f", 3, true
	}
	if target == renvoTargetWasiWasm32 {
		return "wasi/wasm32", "\xaa\x04J\xab}#\x99\nD\x93~\xd0\x12\r\xb2\xdfQ\xcd\xd5[(\r\xda_\xfe\x97\x8f\x88N\x8f\x1al", 3, true
	}
	if target == renvoTargetDarwinArm64 {
		return "darwin/arm64", "\xe8!)f\x95\xf13Ǝ\xf4\x81\xc1`k\xb6\xd3{C\xba\xd9\xf1u\xcca\x1c{4\xeb\x00\x80\xd6;", 3, true
	}
	if target == renvoTargetLinuxKernelAmd64 {
		return "linux-kernel/amd64", ":\x03\x91\xe9,\xa4\x02\a\x05u\x89uI0\x9dC\xab\x8b\xf2\xc7/\xd0HlĴ\xbd\x19\xfa$\xbd\xf2", 3, true
	}
	if target == renvoTargetWindowsArm64 {
		return "windows/arm64", "\x8d\r\xe8\xa0ת>\xa4C6N\xde8X\xdb\xc0\x81>+\xa5\xdb\xcc3K\xb1\x9a\xaf\xb1\x85~\x18j", 3, true
	}
	if target == renvoTargetVM32 {
		return "vm/vm32", "\xd14\xe6\x10E\x15\x88\xc6\xc5F\x15D\x8d\x86RNo{Ke\x00\xa6\x7f\x8f\xdct\x17(\x95\xdb\xea\xc7", 3, true
	}
	if target == renvoTargetFreeBSDAmd64 {
		return "freebsd/amd64", "&\xf6IR\xf8'k4e\xa4\x8a\x8c\x81WM\x93)4\xc0Τ\x1b\xa2&RvD\xa3\xddKmj", 3, true
	}
	if target == renvoTargetOpenBSDAmd64 {
		return "openbsd/amd64", "\x9e\x10lM_\xf2\"y){\xbc\xb8\x90==\xf0\x87\xe0\xbf+\x1e'~\xe5]\xdd6\xb6\x7f\xd3\xd0\xf3", 3, true
	}
	if target == renvoTargetNetBSDAmd64 {
		return "netbsd/amd64", "t\xf4\x9b\x04\x979a\xfch\x11\x82[\xdaJ\x81ρ\x9d\x17\a\xef\x8f\x05\xf9\xf2\x12\xf2/uL\xcfY", 3, true
	}
	return "", "", 0, false
}
