// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: linux/386
// unit: x86 282798d9be4048cee74c9e1ba286fd83ec9f4aed8a890288f105296624c37471
package main


const renvoLinux386SysReadSeq = 3
const renvoLinux386SysWriteSeq = 4
const renvoLinux386SysOpen = 5
const renvoLinux386SysClose = 6
const renvoLinux386SysFchmod = 94
const renvoLinux386SysReadAt = 180
const renvoLinux386SysWriteAt = 181

func renvo386AsmPrepareReadWriteBuf(a *renvoAsm) {
	renvoAsmPushTertiary(a)
	renvoAsmCopyPrimaryToCallWord1(a)
	renvoAsmPopSecondary(a)
}

func renvo386AsmMoveOffsetArg(a *renvoAsm) {
	renvoAsmEmit16(a, 0xc689)
	renvoAsmPrimaryImm(a, 0)
	renvoAsmEmit16(a, 0xc789)
}

func compileLinux386(input []int, output int) int {
	return compileLinux386Arena(input, output, 0)
}

func compileLinux386Arena(input []int, output int, arenaSize int) int {
	renvoSetTarget(renvoTargetLinux386)
	src := renvoMakeByteScratch(589824)
	for i := 0; i < len(input); i++ {
		src = renvoReadAll(input[i], src)
		src = append(src, '\n')
	}
	var prog renvoProgram
	prog = renvoParseProgram(src)
	if !prog.ok {
		return 1
	}
	var meta renvoMeta
	renvoBuildMetaInto(&prog, &meta)
	if !meta.ok {
		return 1
	}
	meta.arenaSize = renvoResolveArenaSize(renvoTarget, arenaSize)
	var result renvoCompileResult
	result = renvoTryCompileScalarProgram386Scratch(&prog, &meta)
	if result.ok {
		data := result.data
		if renvoFixedTarget == 0 {
			data = renvoCompileOutputData(data, renvoTarget)
		}
		write(output, data, -1)
		return 0
	}
	renvoPrintErr("renvo: compilation failed\n")
	return 1
}

func renvoAsmBuildArgvEnvSlices386(a *renvoAsm, bssOff int, envOff int, envLenOff int) {
	loopLabel := renvoAsmNewLabel(a)
	strlenLabel := renvoAsmNewLabel(a)
	afterLenLabel := renvoAsmNewLabel(a)
	doneLabel := renvoAsmNewLabel(a)
	envLoopLabel := renvoAsmNewLabel(a)
	envStrlenLabel := renvoAsmNewLabel(a)
	envAfterLenLabel := renvoAsmNewLabel(a)
	envDoneLabel := renvoAsmNewLabel(a)

	// Stack walking is invariant; keep fixed instruction runs together and
	// leave relocations and branch labels explicit below.
	renvoAsmEmitText(a, "\x8b\x04\x24\x89\xe6\x83\xc6\x04")
	renvo386AsmMovRegPCRel(a, 7, bssOff, renvoAbsBssReloc)
	renvoAsmEmitText(a, "\x31\xc9")
	renvoAsmMarkLabel(a, loopLabel)
	renvoAsmEmitText(a, "\x39\xc1\x0f\x8d")
	at := len(a.code)
	renvoAsmEmit32(a, 0)
	renvoAsmAddReloc(a, at, doneLabel)
	renvoAsmEmitText(a, "\x8b\x14\x8e\x89\x17\x31\xdb")
	renvoAsmMarkLabel(a, strlenLabel)
	renvoAsmEmitText(a, "\x80\x3c\x1a\x00")
	renvoAsmJzLabel(a, afterLenLabel)
	renvoAsmEmitText(a, "\x43")
	renvoAsmJmpMarkLabel(a, strlenLabel, afterLenLabel)
	renvoAsmEmitText(a, "\x89\x5f\x08\x83\xc7\x10\x41")
	renvoAsmJmpMarkLabel(a, loopLabel, doneLabel)

	renvoAsmEmitText(a, "\x8d\x74\x86\x08")
	renvo386AsmMovRegPCRel(a, 7, envOff, renvoAbsBssReloc)
	renvoAsmEmitText(a, "\x31\xc9")
	renvoAsmMarkLabel(a, envLoopLabel)
	renvoAsmEmitText(a, "\x8b\x14\x8e\x85\xd2")
	renvoAsmJzLabel(a, envDoneLabel)
	renvoAsmEmitText(a, "\x89\x17\x31\xdb")
	renvoAsmMarkLabel(a, envStrlenLabel)
	renvoAsmEmitText(a, "\x80\x3c\x1a\x00")
	renvoAsmJzLabel(a, envAfterLenLabel)
	renvoAsmEmitText(a, "\x43")
	renvoAsmJmpMarkLabel(a, envStrlenLabel, envAfterLenLabel)
	renvoAsmEmitText(a, "\x89\x5f\x08\x83\xc7\x10\x41")
	renvoAsmJmpMarkLabel(a, envLoopLabel, envDoneLabel)
	renvo386AsmMovRegPCRel(a, 6, envLenOff, renvoAbsBssReloc)
	renvoAsmEmit16(a, 0x0e89)

	renvo386AsmMovRegPCRel(a, 3, bssOff, renvoAbsBssReloc)
	renvoAsmEmitText(a, "\x89\xc6\x89\xc2")
	renvo386AsmMovRegPCRel(a, 1, envOff, renvoAbsBssReloc)
	renvo386AsmMovRegPCRel(a, 0, envLenOff, renvoAbsBssReloc)
	renvoAsmEmit16(a, 0x008b)
	renvoAsmEmitText(a, "\x89\xc7")
}

func renvoAsmImage386(a *renvoAsm) []byte {
	renvoAsmPatch386(a)
	loadFileSize := a.codeOffset + len(a.code) + len(a.data)
	bssOffset := renvoAsmBssOffset(a)
	if a.c.stripSymbols {
		out := make([]byte, 0, loadFileSize)
		out = renvoAppendElfHeader386(out, a.codeOffset, loadFileSize, bssOffset, a.bssSize, 0)
		for i := 0; i < len(a.code); i++ {
			out = append(out, a.code[i])
		}
		for i := 0; i < len(a.data); i++ {
			out = append(out, a.data[i])
		}
		if renvoFixedTarget == 0 {
			return renvoAppendReplLinkTable(out, a)
		}
		return out
	}
	var sec renvoElfSymbolSections
	renvoBuildElfSymbolSections(a, 0, a.codeOffset, loadFileSize, &sec)
	out := make([]byte, 0, sec.shoff+280)
	out = renvoAppendElfHeader386(out, a.codeOffset, loadFileSize, bssOffset, a.bssSize, sec.shoff)
	for i := 0; i < len(a.code); i++ {
		out = append(out, a.code[i])
	}
	for i := 0; i < len(a.data); i++ {
		out = append(out, a.data[i])
	}
	out = renvoAppendUntil(out, sec.symtabOff)
	for i := 0; i < len(sec.symtab); i++ {
		out = append(out, sec.symtab[i])
	}
	out = renvoAppendUntil(out, sec.strtabOff)
	for i := 0; i < len(sec.strtab); i++ {
		out = append(out, sec.strtab[i])
	}
	out = renvoAppendUntil(out, sec.shstrOff)
	for i := 0; i < len(sec.shstrtab); i++ {
		out = append(out, sec.shstrtab[i])
	}
	out = renvoAppendUntil(out, sec.shoff)
	out = renvoAppendElfSectionHeaders(out, &sec, a, 0)
	if renvoFixedTarget == 0 {
		return renvoAppendReplLinkTable(out, a)
	}
	return out
}

func renvoAsmPatch386(a *renvoAsm) {
	renvoAsmPatch(a)
	for i := 0; i+2 < len(a.absRelocs); i += 3 {
		at := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i))
		off := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i+1))
		kind := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i+2))
		target := a.dataOffset + off
		if kind == renvoAbsBssReloc {
			target = renvoAsmBssOffset(a) + off
		}
		renvoPut32At(a.code, at, target-(a.codeOffset+at-3))
	}
}

func renvoAppendElfHeader386(out []byte, entryOff int, fileSize int, bssOffset int, bssSize int, shoff int) []byte {
	base := 0

	out = append(out, 0x7f)
	out = append(out, 'E')
	out = append(out, 'L')
	out = append(out, 'F')
	out = append(out, 1)
	out = append(out, 1)
	out = append(out, 1)
	out = append(out, 0)
	for i := 0; i < 8; i++ {
		out = append(out, 0)
	}
	out = renvoAppend16(out, 3)
	out = renvoAppend16(out, 3)
	out = renvoAppend32(out, 1)
	out = renvoAppend32(out, base+entryOff)
	out = renvoAppend32(out, 52)
	out = renvoAppend32(out, shoff)
	out = renvoAppend32(out, 0)
	out = renvoAppend16(out, 52)
	out = renvoAppend16(out, 32)
	out = renvoAppend16(out, 2)
	if shoff == 0 {
		out = renvoAppend16(out, 0)
		out = renvoAppend16(out, 0)
		out = renvoAppend16(out, 0)
	} else {
		out = renvoAppend16(out, 40)
		out = renvoAppend16(out, 7)
		out = renvoAppend16(out, 6)
	}

	out = renvoAppend32(out, 1)
	out = renvoAppend32(out, 0)
	out = renvoAppend32(out, base)
	out = renvoAppend32(out, base)
	out = renvoAppend32(out, fileSize)
	out = renvoAppend32(out, fileSize)
	out = renvoAppend32(out, 5)
	out = renvoAppend32(out, 0x1000)
	out = renvoAppendElf32LoadProgram(out, 6, bssOffset, base+bssOffset, 0, bssSize)
	return out
}
