// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: target-projection/netbsd/amd64
// unit: native 84f927a3931b639e701b2dff1ca4e0afd4bf512c6f0e7aa432f23c5a8745a9bc
package main


const renvoNetBSDAmd64SysReadAt = 173
const renvoNetBSDAmd64SysWriteAt = 174


const renvoNetBSDAmd64ELFCodeOffset = 256
const renvoNetBSDAmd64ImageBase = 0x400000

func renvoAppendNetBSDElfHeaderAmd64(out []byte, entryOff int, fileSize int, bssOffset int, bssSize int, shoff int) []byte {
	start := len(out)
	header := "\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00\x01\x00\x00\x00"
	for i := 0; i < len(header); i++ {
		out = append(out, header[i])
	}
	out = renvoAppendUntil(out, start+64)
	renvoPut32At(out, start+24, renvoNetBSDAmd64ImageBase+entryOff)
	renvoPut32At(out, start+32, 64)
	renvoPut32At(out, start+40, shoff)
	out[start+52] = 64
	out[start+54] = 56
	out[start+56] = 3
	if shoff != 0 {
		out[start+58] = 64
		out[start+60] = 7
		out[start+62] = 6
	}
	out = renvoAppendElf64Program(out, 1, 5, 0, renvoNetBSDAmd64ImageBase, fileSize, fileSize, 0x1000)
	out = renvoAppendElf64Program(out, 1, 6, bssOffset, renvoNetBSDAmd64ImageBase+bssOffset, 0, bssSize, 0x1000)
	out = renvoAppendElf64Program(out, 4, 4, 232, renvoNetBSDAmd64ImageBase+232, 24, 24, 4)
	out = renvoAppend32(out, 7)
	out = renvoAppend32(out, 4)
	out = renvoAppend32(out, 1)
	out = append(out, 'N', 'e', 't', 'B', 'S', 'D', 0, 0)
	return renvoAppend32(out, 1100000000)
}
