// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: arch/x86_64
// unit: x86_64 3f94149aff879baa570804c3403e28a5f70ada9592141b1300e63f1dcc4d94e5
package main


var rtgX8664RAX = RTGRegister{Code:0, Valid:true}

var rtgX8664RCX = RTGRegister{Code:1, Valid:true}

var rtgX8664RDX = RTGRegister{Code:2, Valid:true}

var rtgX8664RBX = RTGRegister{Code:3, Valid:true}

var rtgX8664RSP = RTGRegister{Code:4, Valid:true}

var rtgX8664RBP = RTGRegister{Code:5, Valid:true}

var rtgX8664RSI = RTGRegister{Code:6, Valid:true}

var rtgX8664RDI = RTGRegister{Code:7, Valid:true}

var rtgX8664R8 = RTGRegister{Code:8, Valid:true}

var rtgX8664R9 = RTGRegister{Code:9, Valid:true}

var rtgX8664R10 = RTGRegister{Code:10, Valid:true}

var rtgX8664R11 = RTGRegister{Code:11, Valid:true}

var rtgX8664R12 = RTGRegister{Code:12, Valid:true}

var rtgX8664R13 = RTGRegister{Code:13, Valid:true}

var rtgX8664R14 = RTGRegister{Code:14, Valid:true}

var rtgX8664R15 = RTGRegister{Code:15, Valid:true}
var rtgX8664Primary = rtgX8664RAX
var rtgX8664Secondary = rtgX8664RDX
var rtgX8664Tertiary = rtgX8664RCX
var rtgX8664Scratch = rtgX8664R10
var rtgX8664DivisionScratch = rtgX8664RBX
var rtgX8664CopyDestination = rtgX8664RDI
var rtgX8664CopySource = rtgX8664RSI
var rtgX8664CopyCount = rtgX8664RCX
var rtgX8664Stack = rtgX8664RSP
var rtgX8664Frame = rtgX8664RBP

var rtgX8664EQ = RTGCondition{Code:0x94, SetOpcode:0x94, JumpOpcode:0x84}

var rtgX8664NE = RTGCondition{Code:0x95, SetOpcode:0x95, JumpOpcode:0x85}

var rtgX8664SLT = RTGCondition{Code:0x9c, SetOpcode:0x9c, JumpOpcode:0x8c}

var rtgX8664SGE = RTGCondition{Code:0x9d, SetOpcode:0x9d, JumpOpcode:0x8d}

var rtgX8664SLE = RTGCondition{Code:0x9e, SetOpcode:0x9e, JumpOpcode:0x8e}

var rtgX8664SGT = RTGCondition{Code:0x9f, SetOpcode:0x9f, JumpOpcode:0x8f}

var rtgX8664ULT = RTGCondition{Code:0x92, SetOpcode:0x92, JumpOpcode:0x82}

var rtgX8664UGE = RTGCondition{Code:0x93, SetOpcode:0x93, JumpOpcode:0x83}

var rtgX8664ULE = RTGCondition{Code:0x96, SetOpcode:0x96, JumpOpcode:0x86}

var rtgX8664UGT = RTGCondition{Code:0x97, SetOpcode:0x97, JumpOpcode:0x87}

func rtgX8664X86Low3(reg RTGRegister) byte {
    return byte(reg.Code & 7)
}

func rtgX8664X86High(reg RTGRegister) byte {
    return byte(reg.Code>>3) & 1
}

func rtgX8664X86Opcode(out *RTGEmitter, opcode uint32) {
    if opcode > 0xff {
        out.Byte(byte(opcode >> 8))
    }
    out.Byte(byte(opcode))
}

func rtgX8664X86REX(
    out *RTGEmitter,
    wide bool,
    reg RTGRegister,
    index RTGRegister,
    base RTGRegister,
    byteRegister RTGRegister,
) {
    w := byte(0)
    if wide {
        w = 1
    }
    r := rtgX8664X86High(reg)
    x := byte(0)
    if index.Valid {
        x = rtgX8664X86High(index)
    }
    b := byte(0)
    if base.Valid {
        b = rtgX8664X86High(base)
    }
    needsByteREX := byteRegister.Valid && byteRegister.Code >= 4
    if w != 0 || r != 0 || x != 0 || b != 0 || needsByteREX {
        out.Byte(0x40 | w<<3 | r<<2 | x<<1 | b)
    }
}

func rtgX8664X86ModRM(out *RTGEmitter, mode byte, reg byte, rm byte) {
    out.Byte(mode<<6 | (reg&7)<<3 | rm&7)
}

func rtgX8664X86Memory(out *RTGEmitter, reg byte, address RTGAddress) {
    if address.Target.Valid {
        rtgX8664X86ModRM(out, 0, reg, 5)
        out.Rel32Addend(address.Target, address.Addend)
        return
    }

    base := address.Base
    index := address.Index
    displacement := address.Displacement
    needsSIB := index.Valid || rtgX8664X86Low3(base) == 4
    mode := byte(0)
    if displacement != 0 || rtgX8664X86Low3(base) == 5 {
        mode = 2
        if RTGSignedFits(int64(displacement), 8) {
            mode = 1
        }
    }

    if needsSIB {
        rtgX8664X86ModRM(out, mode, reg, 4)
        indexCode := byte(4)
        if index.Valid {
            indexCode = rtgX8664X86Low3(index)
        }
        out.Byte(byte(RTGLog2(address.Scale))<<6 |
            indexCode<<3 | rtgX8664X86Low3(base))
    } else {
        rtgX8664X86ModRM(out, mode, reg, rtgX8664X86Low3(base))
    }

    if mode == 1 {
        out.Byte(byte(displacement))
    } else if mode == 2 {
        out.Uint32(uint32(displacement))
    }
}

func rtgX8664X86RRRM(
    out *RTGEmitter,
    opcode uint32,
    destination RTGRegister,
    source RTGRegister,
    width int,
) {
    if width == 16 {
        out.Byte(0x66)
    }
    byteRegister := RTGNoRegister
    if width == 8 {
        byteRegister = source
    }
    rtgX8664X86REX(out, width == 64, source, RTGNoRegister, destination, byteRegister)
    rtgX8664X86Opcode(out, opcode)
    rtgX8664X86ModRM(out, 3, rtgX8664X86Low3(source), rtgX8664X86Low3(destination))
}

func rtgX8664X86RR(
    out *RTGEmitter,
    opcode uint32,
    destination RTGRegister,
    source RTGRegister,
    width int,
) {
    rtgX8664X86REX(out, width == 64, destination, RTGNoRegister, source, RTGNoRegister)
    rtgX8664X86Opcode(out, opcode)
    rtgX8664X86ModRM(out, 3, rtgX8664X86Low3(destination), rtgX8664X86Low3(source))
}

func rtgX8664X86RMR(
    out *RTGEmitter,
    opcode uint32,
    destination RTGRegister,
    address RTGAddress,
    width int,
) {
    if width == 16 {
        out.Byte(0x66)
    }
    rtgX8664X86REX(out, width == 64, destination, address.Index, address.Base, RTGNoRegister)
    rtgX8664X86Opcode(out, opcode)
    rtgX8664X86Memory(out, rtgX8664X86Low3(destination), address)
}

func rtgX8664X86RRM(
    out *RTGEmitter,
    opcode uint32,
    address RTGAddress,
    source RTGRegister,
    width int,
) {
    if width == 16 {
        out.Byte(0x66)
    }
    byteRegister := RTGNoRegister
    if width == 8 {
        byteRegister = source
    }
    rtgX8664X86REX(out, width == 64, source, address.Index, address.Base, byteRegister)
    rtgX8664X86Opcode(out, opcode)
    rtgX8664X86Memory(out, rtgX8664X86Low3(source), address)
}

func rtgX8664X86Group(
    out *RTGEmitter,
    opcode uint32,
    selector byte,
    operand RTGRegister,
    width int,
) {
    rtgX8664X86REX(out, width == 64, RTGNoRegister, RTGNoRegister, operand, RTGNoRegister)
    rtgX8664X86Opcode(out, opcode)
    rtgX8664X86ModRM(out, 3, selector, rtgX8664X86Low3(operand))
}

func rtgX8664X86GroupImmediate(
    out *RTGEmitter,
    opcode uint32,
    selector byte,
    operand RTGRegister,
    value int64,
    width int,
) {
    rtgX8664X86REX(out, width == 64, RTGNoRegister, RTGNoRegister, operand, RTGNoRegister)
    if RTGSignedFits(value, 8) {
        out.Byte(0x83)
        rtgX8664X86ModRM(out, 3, selector, rtgX8664X86Low3(operand))
        out.Byte(byte(value))
        return
    }
    rtgX8664X86Opcode(out, opcode)
    rtgX8664X86ModRM(out, 3, selector, rtgX8664X86Low3(operand))
    out.Uint32(uint32(value))
}

func rtgX8664X86GroupImmediate8(
    out *RTGEmitter,
    opcode uint32,
    selector byte,
    operand RTGRegister,
    value byte,
    width int,
) {
    rtgX8664X86Group(out, opcode, selector, operand, width)
    out.Byte(value)
}

func rtgX8664X86GroupMemoryImmediate(
    out *RTGEmitter,
    opcode uint32,
    selector byte,
    address RTGAddress,
    value int64,
    width int,
) {
    rtgX8664X86REX(out, width == 64, RTGNoRegister, address.Index, address.Base, RTGNoRegister)
    if RTGSignedFits(value, 8) {
        out.Byte(0x83)
    } else {
        rtgX8664X86Opcode(out, opcode)
    }
    rtgX8664X86Memory(out, selector, address)
    if RTGSignedFits(value, 8) {
        out.Byte(byte(value))
    } else {
        out.Uint32(uint32(value))
    }
}

func rtgX8664X86MultiplyImmediate(
    out *RTGEmitter,
    opcode uint32,
    destination RTGRegister,
    source RTGRegister,
    value int64,
    width int,
) {
    rtgX8664X86REX(out, width == 64, destination, RTGNoRegister, source, RTGNoRegister)
    if RTGSignedFits(value, 8) {
        out.Byte(0x6b)
    } else {
        rtgX8664X86Opcode(out, opcode)
    }
    rtgX8664X86ModRM(out, 3, rtgX8664X86Low3(destination), rtgX8664X86Low3(source))
    if RTGSignedFits(value, 8) {
        out.Byte(byte(value))
    } else {
        out.Uint32(uint32(value))
    }
}

func rtgX8664X86OpcodeRegister(out *RTGEmitter, opcode byte, operand RTGRegister) {
    if rtgX8664X86High(operand) != 0 {
        out.Byte(0x41)
    }
    out.Byte(opcode + rtgX8664X86Low3(operand))
}

func rtgX8664X86Immediate(out *RTGEmitter, opcode byte, value uint64, width int) {
    out.Byte(opcode)
    if width == 8 {
        out.Byte(byte(value))
    } else if width == 32 {
        out.Uint32(uint32(value))
    } else {
        out.Uint64(value)
    }
}

func rtgX8664X86Relative(out *RTGEmitter, opcode uint32, label RTGLabel) {
    rtgX8664X86Opcode(out, opcode)
    out.Rel32(label)
}

func rtgX8664X86SetCondition(
    out *RTGEmitter,
    condition RTGCondition,
    destination RTGRegister,
) {
    rtgX8664X86REX(out, false, RTGNoRegister, RTGNoRegister, destination, destination)
    out.Byte(0x0f)
    out.Byte(condition.SetOpcode)
    rtgX8664X86ModRM(out, 3, 0, rtgX8664X86Low3(destination))
}

func rtgX8664X86JumpCondition(
    out *RTGEmitter,
    condition RTGCondition,
    label RTGLabel,
) {
    out.Byte(0x0f)
    out.Byte(condition.JumpOpcode)
    out.Rel32(label)
}

func rtgX8664X86MoveImmediate(out *RTGEmitter, destination RTGRegister, value int64) {
    if destination == rtgX8664RAX && value == 0 {
        out.Byte(0x31)
        out.Byte(0xc0)
    } else if destination != rtgX8664RSP && RTGSignedFits(value, 8) {
        rtgX8664X86Immediate(out, 0x6a, uint64(value), 8)
        rtgX8664X86OpcodeRegister(out, 0x58, destination)
    } else if RTGUnsignedFits(uint64(value), 32) {
        rtgX8664X86OpcodeRegister(out, 0xb8, destination)
        out.Uint32(uint32(value))
    } else if RTGSignedFits(value, 32) {
        rtgX8664X86Immediate(out, 0x68, uint64(value), 32)
        rtgX8664X86OpcodeRegister(out, 0x58, destination)
    } else {
        rtgX8664X86REX(out, true, RTGNoRegister, RTGNoRegister, destination, RTGNoRegister)
        out.Byte(0xb8 + rtgX8664X86Low3(destination))
        out.Uint64(uint64(value))
    }
}

func rtgX8664X86RelaxJump(displacement int64) (byte, bool) {
    return 0xeb, RTGSignedFits(displacement, 8)
}

func rtgX8664X86RelaxCondition(condition RTGCondition, displacement int64) (byte, bool) {
    return condition.JumpOpcode - 0x10, RTGSignedFits(displacement, 8)
}

func rtgX8664X86VariableShift(
    out *RTGEmitter,
    direction RTGShiftDirection,
    signed bool,
) {
    rtgX8664Xchg64(out, rtgX8664Primary, rtgX8664Tertiary)
    if direction == RTGShiftLeft {
        rtgX8664ShlCL64(out, rtgX8664Primary)
    } else if signed {
        rtgX8664SarCL64(out, rtgX8664Primary)
    } else {
        rtgX8664ShrCL64(out, rtgX8664Primary)
    }
}

func rtgX8664X86SignedDivide(out *RTGEmitter, remainder bool) {
    ordinary := out.NewLabel()
    done := out.NewLabel()
    rtgX8664CmpImmediate64(out, rtgX8664Primary, -1)
    rtgX8664X86JumpCondition(out, rtgX8664NE, ordinary)
    rtgX8664X86MoveImmediate(out, rtgX8664Secondary, 1)
    rtgX8664ShlImmediate64(out, rtgX8664Secondary, 63)
    rtgX8664Cmp64(out, rtgX8664Tertiary, rtgX8664Secondary)
    rtgX8664X86JumpCondition(out, rtgX8664NE, ordinary)
    if remainder {
        rtgX8664X86MoveImmediate(out, rtgX8664Primary, 0)
    } else {
        rtgX8664Mov64(out, rtgX8664Primary, rtgX8664Tertiary)
    }
    rtgX8664X86Relative(out, 0xe9, done)
    out.Mark(ordinary)
    rtgX8664PushRegister(out, rtgX8664DivisionScratch)
    rtgX8664Mov64(out, rtgX8664DivisionScratch, rtgX8664Primary)
    rtgX8664Mov64(out, rtgX8664Primary, rtgX8664Tertiary)
    out.Byte(0x48)
    out.Byte(0x99)
    rtgX8664X86Group(out, 0xf7, 7, rtgX8664DivisionScratch, 64)
    if remainder {
        rtgX8664Mov64(out, rtgX8664Primary, rtgX8664Secondary)
    }
    rtgX8664PopRegister(out, rtgX8664DivisionScratch)
    out.Mark(done)
}

func rtgX8664X86CopyBytes(out *RTGEmitter) {
    destination := rtgX8664CopyDestination
    source := rtgX8664CopySource
    count := rtgX8664CopyCount
    forward := out.NewLabel()
    done := out.NewLabel()
    rtgX8664Cmp64(out, destination, source)
    rtgX8664X86JumpCondition(out, rtgX8664ULE, forward)
    rtgX8664Lea64(out, rtgX8664Scratch, RTGAddress{Base: source, Index: count, Scale: 1})
    rtgX8664Cmp64(out, destination, rtgX8664Scratch)
    rtgX8664X86JumpCondition(out, rtgX8664UGE, forward)
    rtgX8664Lea64(out, source, RTGAddress{
        Base: source, Index: count, Scale: 1, Displacement: -1,
    })
    rtgX8664Lea64(out, destination, RTGAddress{
        Base: destination, Index: count, Scale: 1, Displacement: -1,
    })
    out.Byte(0xfd)
    out.Byte(0xf3)
    out.Byte(0xa4)
    out.Byte(0xfc)
    rtgX8664X86Relative(out, 0xe9, done)
    out.Mark(forward)
    out.Byte(0xfc)
    out.Byte(0xf3)
    out.Byte(0xa4)
    out.Mark(done)
}

func rtgX8664WindowsCommandLine(command []byte) [][]byte {
    arguments := make([][]byte, 0, 8)
    offset := 0
    for offset < len(command) {
        for offset < len(command) &&
            (command[offset] == ' ' || command[offset] == '\t') {
            offset++
        }
        if offset == len(command) {
            break
        }

        argument := make([]byte, 0, 32)
        quoted := false
        for offset < len(command) {
            if !quoted &&
                (command[offset] == ' ' || command[offset] == '\t') {
                break
            }
            if command[offset] == '"' {
                quoted = !quoted
                offset++
                continue
            }
            if command[offset] != '\\' {
                argument = append(argument, command[offset])
                offset++
                continue
            }

            slashStart := offset
            for offset < len(command) && command[offset] == '\\' {
                offset++
            }
            slashCount := offset - slashStart
            if offset == len(command) || command[offset] != '"' {
                for slashCount > 0 {
                    argument = append(argument, '\\')
                    slashCount--
                }
                continue
            }

            for slashCount >= 2 {
                argument = append(argument, '\\')
                slashCount -= 2
            }
            if slashCount == 1 {
                argument = append(argument, '"')
                offset++
            } else {
                quoted = !quoted
                offset++
            }
        }
        arguments = append(arguments, argument)
    }
    return arguments
}

// Generated from instruction mov64.
func rtgX8664Mov64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x89, destination, source, 64)
}

// Generated from instruction load64.
func rtgX8664Load64(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x8b, destination, address, 64)
}

// Generated from instruction lea64.
func rtgX8664Lea64(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x8d, destination, address, 64)
}

// Generated from instruction load_i32.
func rtgX8664LoadI32(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x63, destination, address, 32)
}

// Generated from instruction load_u32.
func rtgX8664LoadU32(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x8b, destination, address, 32)
}

// Generated from instruction load_i16.
func rtgX8664LoadI16(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x0fbf, destination, address, 16)
}

// Generated from instruction load_u16.
func rtgX8664LoadU16(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x0fb7, destination, address, 16)
}

// Generated from instruction load_i8.
func rtgX8664LoadI8(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x0fbe, destination, address, 8)
}

// Generated from instruction load_u8.
func rtgX8664LoadU8(out *RTGEmitter, destination RTGRegister, address RTGAddress) {
	rtgX8664X86RMR(out, 0x0fb6, destination, address, 8)
}

// Generated from instruction store64.
func rtgX8664Store64(out *RTGEmitter, address RTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x89, address, source, 64)
}

// Generated from instruction store32.
func rtgX8664Store32(out *RTGEmitter, address RTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x89, address, source, 32)
}

// Generated from instruction store16.
func rtgX8664Store16(out *RTGEmitter, address RTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x89, address, source, 16)
}

// Generated from instruction store8.
func rtgX8664Store8(out *RTGEmitter, address RTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x88, address, source, 8)
}

// Generated from instruction add64.
func rtgX8664Add64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x01, destination, source, 64)
}

// Generated from instruction sub64.
func rtgX8664Sub64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x29, destination, source, 64)
}

// Generated from instruction and64.
func rtgX8664And64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x21, destination, source, 64)
}

// Generated from instruction or64.
func rtgX8664Or64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x09, destination, source, 64)
}

// Generated from instruction xor64.
func rtgX8664Xor64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x31, destination, source, 64)
}

// Generated from instruction cmp64.
func rtgX8664Cmp64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x39, destination, source, 64)
}

// Generated from instruction test64.
func rtgX8664Test64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x85, destination, source, 64)
}

// Generated from instruction imul64.
func rtgX8664Imul64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RR(out, 0x0faf, destination, source, 64)
}

// Generated from instruction xchg64.
func rtgX8664Xchg64(out *RTGEmitter, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x87, destination, source, 64)
}

// Generated from instruction add_imm64.
func rtgX8664AddImmediate64(out *RTGEmitter, operand RTGRegister, value int64) {
	rtgX8664X86GroupImmediate(out, 0x81, 0, operand, value, 64)
}

// Generated from instruction or_imm64.
func rtgX8664OrImmediate64(out *RTGEmitter, operand RTGRegister, value int64) {
	rtgX8664X86GroupImmediate(out, 0x81, 1, operand, value, 64)
}

// Generated from instruction and_imm64.
func rtgX8664AndImmediate64(out *RTGEmitter, operand RTGRegister, value int64) {
	rtgX8664X86GroupImmediate(out, 0x81, 4, operand, value, 64)
}

// Generated from instruction sub_imm64.
func rtgX8664SubImmediate64(out *RTGEmitter, operand RTGRegister, value int64) {
	rtgX8664X86GroupImmediate(out, 0x81, 5, operand, value, 64)
}

// Generated from instruction xor_imm64.
func rtgX8664XorImmediate64(out *RTGEmitter, operand RTGRegister, value int64) {
	rtgX8664X86GroupImmediate(out, 0x81, 6, operand, value, 64)
}

// Generated from instruction cmp_imm64.
func rtgX8664CmpImmediate64(out *RTGEmitter, operand RTGRegister, value int64) {
	rtgX8664X86GroupImmediate(out, 0x81, 7, operand, value, 64)
}

// Generated from instruction cmp_mem_imm64.
func rtgX8664CmpMemoryImmediate64(out *RTGEmitter, address RTGAddress, value int64) {
	rtgX8664X86GroupMemoryImmediate(out, 0x81, 7, address, value, 64)
}

// Generated from instruction imul_imm64.
func rtgX8664ImulImmediate64(out *RTGEmitter, destination RTGRegister, source RTGRegister, value int64) {
	rtgX8664X86MultiplyImmediate(out, 0x69, destination, source, value, 64)
}

// Generated from instruction inc64.
func rtgX8664Inc64(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86Group(out, 0xff, 0, operand, 64)
}

// Generated from instruction dec64.
func rtgX8664Dec64(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86Group(out, 0xff, 1, operand, 64)
}

// Generated from instruction shl_imm64.
func rtgX8664ShlImmediate64(out *RTGEmitter, operand RTGRegister, value byte) {
	rtgX8664X86GroupImmediate8(out, 0xc1, 4, operand, value, 64)
}

// Generated from instruction shr_imm64.
func rtgX8664ShrImmediate64(out *RTGEmitter, operand RTGRegister, value byte) {
	rtgX8664X86GroupImmediate8(out, 0xc1, 5, operand, value, 64)
}

// Generated from instruction sar_imm64.
func rtgX8664SarImmediate64(out *RTGEmitter, operand RTGRegister, value byte) {
	rtgX8664X86GroupImmediate8(out, 0xc1, 7, operand, value, 64)
}

// Generated from instruction shl_cl64.
func rtgX8664ShlCL64(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86Group(out, 0xd3, 4, operand, 64)
}

// Generated from instruction shr_cl64.
func rtgX8664ShrCL64(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86Group(out, 0xd3, 5, operand, 64)
}

// Generated from instruction sar_cl64.
func rtgX8664SarCL64(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86Group(out, 0xd3, 7, operand, 64)
}

// Generated from instruction call_reg.
func rtgX8664CallRegister(out *RTGEmitter, operand RTGRegister, width int) {
	rtgX8664X86Group(out, 0xff, 2, operand, width)
}

// Generated from instruction idiv64.
func rtgX8664Idiv64(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86Group(out, 0xf7, 7, operand, 64)
}

// Generated from instruction push_reg.
func rtgX8664PushRegister(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86OpcodeRegister(out, 0x50, operand)
}

// Generated from instruction pop_reg.
func rtgX8664PopRegister(out *RTGEmitter, operand RTGRegister) {
	rtgX8664X86OpcodeRegister(out, 0x58, operand)
}

// Generated from instruction push_imm8.
func rtgX8664PushImmediate8(out *RTGEmitter, value uint64) {
	rtgX8664X86Immediate(out, 0x6a, value, 8)
}

// Generated from instruction push_imm32.
func rtgX8664PushImmediate32(out *RTGEmitter, value uint64) {
	rtgX8664X86Immediate(out, 0x68, value, 32)
}

// Generated from instruction setcc.
func rtgX8664Setcc(out *RTGEmitter, condition RTGCondition, destination RTGRegister) {
	rtgX8664X86SetCondition(out, condition, destination)
}

// Generated from instruction jcc_rel32.
func rtgX8664JccRel32(out *RTGEmitter, condition RTGCondition, label RTGLabel) {
	rtgX8664X86JumpCondition(out, condition, label)
}

// Generated from instruction call_rel32.
func rtgX8664CallRel32(out *RTGEmitter, label RTGLabel) {
	rtgX8664X86Relative(out, 0xe8, label)
}

// Generated from instruction jump_rel32.
func rtgX8664JumpRel32(out *RTGEmitter, label RTGLabel) {
	rtgX8664X86Relative(out, 0xe9, label)
}

// Generated from instruction ret.
func rtgX8664Ret(out *RTGEmitter) {
	RTGByte(out, 0xc3)
}

// Generated from instruction leave.
func rtgX8664Leave(out *RTGEmitter) {
	RTGByte(out, 0xc9)
}

// Generated from instruction syscall.
func rtgX8664Syscall(out *RTGEmitter) {
	RTGByte(out, 0x0f)
	RTGByte(out, 0x05)
}

// Generated from instruction cqo.
func rtgX8664Cqo(out *RTGEmitter) {
	RTGByte(out, 0x48)
	RTGByte(out, 0x99)
}

// Generated from instruction cld.
func rtgX8664Cld(out *RTGEmitter) {
	RTGByte(out, 0xfc)
}

// Generated from instruction std.
func rtgX8664Std(out *RTGEmitter) {
	RTGByte(out, 0xfd)
}

// Generated from instruction rep_movsb.
func rtgX8664RepMovsb(out *RTGEmitter) {
	RTGByte(out, 0xf3)
	RTGByte(out, 0xa4)
}
