// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: target-projection/freebsd/amd64
// unit: native 84b99774bd7d0ddeafacbff7910d999c2d6fbd23da29a18e4d79f800abecf493
package main


const renvoBSDAmd64SysReadSeq = 3
const renvoBSDAmd64SysWriteSeq = 4
const renvoBSDAmd64SysOpen = 5
const renvoBSDAmd64SysClose = 6
const renvoFreeBSDAmd64SysReadAt = 475
const renvoFreeBSDAmd64SysWriteAt = 476
const renvoBSDAmd64SysFchmod = 124
const renvoBSDAmd64SysExit = 1
