// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: algorithms/arm
// unit: native b661234cab34da762446186096434d3cf0a048a5ceed7d3fc700896c400e9925
package main


func renvoArmAsmAlign(a *renvoAsm) {
	for len(a.code)%4 != 0 {
		renvoAsmEmit8(a, 0)
	}
}
func renvoArmAsmMovRegReg(a *renvoAsm, dst int, src int) {
	if dst == src {
		return
	}
	renvoArmAsmEmit(a, 0xe1a00000|(dst<<12)|src)
}
func renvoArmAsmMovRegImm(a *renvoAsm, reg int, imm int) {
	part := imm & 65535
	renvoArmAsmEmit(a, 0xe3000000|((part&0xf000)<<4)|(reg<<12)|(part&0x0fff))
	part = (imm >> 16) & 65535
	if part != 0 {
		renvoArmAsmEmit(a, 0xe3400000|((part&0xf000)<<4)|(reg<<12)|(part&0x0fff))
	}
}
func renvoArmAsmAddRegImm(a *renvoAsm, dst int, src int, imm int) {
	if imm == 0 {
		renvoArmAsmMovRegReg(a, dst, src)
		return
	}
	tmp := 9
	if dst == tmp || src == tmp {
		tmp = 10
	}
	if imm < 0 {
		renvoArmAsmMovRegImm(a, tmp, -imm)
		renvoArmAsmSubRegReg(a, dst, src, tmp)
		return
	}
	renvoArmAsmMovRegImm(a, tmp, imm)
	renvoArmAsmAddRegReg(a, dst, src, tmp)
}
func renvoArmAsmFrameStart(a *renvoAsm) int {
	at := len(a.code)
	renvoArmAsmEmit(a, 0xe3009000) // movw r9, #0
	renvoArmAsmEmit(a, 0xe04dd009) // sub sp, sp, r9
	return at
}
func renvoArmAsmPatchFrame(a *renvoAsm, at int, stackUsed int) {
	frame := (stackUsed + 7) & -8
	if frame > 65528 {
		frame = 65528
	}
	renvoPut32At(a.code, at, 0xe3009000|((frame&0xf000)<<4)|(frame&0x0fff))
}
func renvoArmAsmAddRegSmallImm(a *renvoAsm, dst int, src int, imm int) {
	if imm < 0 {
		renvoArmAsmEmit(a, 0xe2400000|(src<<16)|(dst<<12)|(-imm))
		return
	}
	renvoArmAsmEmit(a, 0xe2800000|(src<<16)|(dst<<12)|imm)
}
func renvoArmAsmAddr(a *renvoAsm, base int, disp int) int {
	if disp == 0 {
		return base
	}
	renvoArmAsmAddRegImm(a, 12, base, disp)
	return 12
}
func renvoArmAsmLoadStoreAddr(a *renvoAsm, base int, disp int, size int) int {
	if size == 2 && (disp < 0 || disp > 255) {
		return renvoArmAsmAddr(a, base, disp)
	}
	if size != 2 && (disp < -4095 || disp > 4095) {
		return renvoArmAsmAddr(a, base, disp)
	}
	return base
}
func renvoArmAsmLoadRegMem(a *renvoAsm, dst int, base int, disp int, size int) {
	addr := renvoArmAsmLoadStoreAddr(a, base, disp, size)
	if addr != base {
		disp = 0
	}
	up := 0x00800000
	if disp < 0 {
		up = 0
		disp = -disp
	}
	if size == 1 {
		renvoArmAsmEmit(a, 0xe5500000|up|(addr<<16)|(dst<<12)|disp)
		return
	}
	if size == 2 {
		renvoArmAsmEmit(a, 0xe15000f0|up|(addr<<16)|(dst<<12)|((disp&0xf0)<<4)|(disp&0x0f))
		return
	}
	renvoArmAsmEmit(a, 0xe5100000|up|(addr<<16)|(dst<<12)|disp)
}
func renvoArmAsmStoreRegMem(a *renvoAsm, src int, base int, disp int, size int) {
	addr := renvoArmAsmLoadStoreAddr(a, base, disp, size)
	if addr != base {
		disp = 0
	}
	up := 0x00800000
	if disp < 0 {
		up = 0
		disp = -disp
	}
	if size == 1 {
		renvoArmAsmEmit(a, 0xe5400000|up|(addr<<16)|(src<<12)|disp)
		return
	}
	if size == 2 {
		renvoArmAsmEmit(a, 0xe14000b0|up|(addr<<16)|(src<<12)|((disp&0xf0)<<4)|(disp&0x0f))
		return
	}
	renvoArmAsmEmit(a, 0xe5000000|up|(addr<<16)|(src<<12)|disp)
}
func renvoArmAsmStackMem(a *renvoAsm, offset int, base int, disp8 int, disp32 int) {
	if base == 0x8948 && disp8 == 0x45 {
		renvoArmAsmStoreRegStack(a, 0, offset)
		return
	}
	if base == 0x8948 && disp8 == 0x55 {
		renvoArmAsmStoreRegStack(a, 1, offset)
		return
	}
	if base == 0x8948 && disp8 == 0x4d {
		renvoArmAsmStoreRegStack(a, 2, offset)
		return
	}
	if base == 0x8b48 && disp8 == 0x45 {
		renvoArmAsmLoadRegStack(a, 0, offset)
		return
	}
	if base == 0x8b48 && disp8 == 0x55 {
		renvoArmAsmLoadRegStack(a, 1, offset)
		return
	}
	if base == 0x8b48 && disp8 == 0x4d {
		renvoArmAsmLoadRegStack(a, 2, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x45 {
		renvoArmAsmLeaRegStack(a, 0, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x55 {
		renvoArmAsmLeaRegStack(a, 1, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x7d {
		renvoArmAsmLeaRegStack(a, 3, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x75 {
		renvoArmAsmLeaRegStack(a, 4, offset)
		return
	}
}
func renvoArmAsmMemDisp(a *renvoAsm, disp int, op int, disp8 int, disp32 int) {
	if op == 0x8b48 && disp8 == 0x4a {
		renvoArmAsmLoadRegMem(a, 2, 1, disp, 4)
		return
	}
	if op == 0x8b48 && disp8 == 0x52 {
		renvoArmAsmLoadRegMem(a, 1, 1, disp, 4)
		return
	}
	if op == 0x8948 && disp8 == 0x41 {
		renvoArmAsmStoreRegMem(a, 0, 2, disp, 4)
		return
	}
}
func renvoArmAsmLoadRaxIndexRcxSize(a *renvoAsm, size int) {
	shift := 3
	if size == 1 {
		shift = 0
	}
	if size == 2 {
		shift = 1
	}
	if size == 4 {
		shift = 2
	}
	renvoArmAsmAddRegRegShift(a, 12, 0, 2, shift)
	renvoArmAsmLoadRegMem(a, 0, 12, 0, size)
}
func renvoArmAsmNormalizeRaxForKind(a *renvoAsm, kind int) {
	if kind == 3 {
		renvoArmAsmEmit(a, 0xe6ef0070)
		return
	}
	if kind == 7 {
		renvoArmAsmEmit(a, 0xe6af0070)
		return
	}
	if kind == 8 {
		renvoArmAsmEmit(a, 0xe6bf0070)
		return
	}
	if kind == 16 {
		renvoArmAsmEmit(a, 0xe6ff0070)
	}
}
func renvoArmAsmCmpRegImm(a *renvoAsm, reg int, imm int) {
	if imm >= 0 && imm <= 255 {
		renvoArmAsmEmit(a, 0xe3500000|(reg<<16)|imm)
		return
	}
	tmp := 9
	if reg == tmp {
		tmp = 10
	}
	renvoArmAsmMovRegImm(a, tmp, imm)
	renvoArmAsmCmpRegReg(a, reg, tmp)
}
func renvoArmCondFromSetcc(setcc int) int {
	if setcc == 0x94 {
		return 0
	}
	if setcc == 0x95 {
		return 1
	}
	if setcc == 0x9c {
		return 11
	}
	if setcc == 0x9e {
		return 13
	}
	if setcc == 0x9f {
		return 12
	}
	return 10
}
func renvoArmAsmDivLeftRcxRightRax(a *renvoAsm, mod bool) {
	renvoArmAsmMovRegReg(a, 9, 0)
	renvoArmAsmEmit(a, 0xe710f010|(0<<16)|(0<<8)|2)
	if mod {
		renvoArmAsmEmit(a, 0xe0600090|(2<<12)|(9<<8)|0)
	}
}
func renvoArmAsmStoreRaxMemRdxRcxSize(a *renvoAsm, size int) {
	shift := 3
	if size == 1 {
		shift = 0
	}
	if size == 2 {
		shift = 1
	}
	if size == 4 {
		shift = 2
	}
	renvoArmAsmAddRegRegShift(a, 12, 1, 2, shift)
	renvoArmAsmStoreRegMem(a, 0, 12, 0, size)
}

func renvoArmAsmAddRaxRcx(a *renvoAsm) {
	renvoArmAsmAddRegReg(a,0,0,2)
}

func renvoArmAsmAddRdxImm(a *renvoAsm, imm int) {
	renvoArmAsmAddRegImm(a,1,1,imm)
}

func renvoArmAsmAddRdxRcx(a *renvoAsm) {
	renvoArmAsmAddRegReg(a,1,1,2)
}

func renvoArmAsmAddRegReg(a *renvoAsm, dst int, left int, right int) {
	renvoArmAsmEmit(a,0xe0800000|(left<<16)|(dst<<12)|right)
}

func renvoArmAsmAddRegRegShift(a *renvoAsm, dst int, left int, right int, shift int) {
	renvoArmAsmEmit(a,0xe0800000|(left<<16)|(dst<<12)|(shift<<7)|right)
}

func renvoArmAsmBoolNotRax(a *renvoAsm) {
	renvoArmAsmCmpRaxImm8(a,0)
	renvoArmAsmCsetRax(a,0)
}

func renvoArmAsmCmpRaxImm8(a *renvoAsm, imm int) {
	renvoArmAsmCmpRegImm(a,0,imm)
}

func renvoArmAsmCmpRegReg(a *renvoAsm, left int, right int) {
	renvoArmAsmEmit(a,0xe1500000|(left<<16)|right)
}

func renvoArmAsmCsetRax(a *renvoAsm, cond int) {
	renvoArmAsmEmit(a,0xe3a00000)
	renvoArmAsmEmit(a,(cond<<28)|0x03a00001)
}

func renvoArmAsmDecMemRdx(a *renvoAsm) {
	renvoArmAsmLoadRegMem(a,9,1,0,4)
	renvoArmAsmAddRegImm(a,9,9,-1)
	renvoArmAsmStoreRegMem(a,9,1,0,4)
}

func renvoArmAsmEmit(a *renvoAsm, insn int) {
	renvoAsmEmit32(a,insn)
}

func renvoArmAsmImulRcxImm(a *renvoAsm, imm int) {
	renvoArmAsmMovRegImm(a,9,imm)
	renvoArmAsmMulRegReg(a,2,2,9)
}

func renvoArmAsmIncMemRdx(a *renvoAsm) {
	renvoArmAsmLoadRegMem(a,9,1,0,4)
	renvoArmAsmAddRegImm(a,9,9,1)
	renvoArmAsmStoreRegMem(a,9,1,0,4)
}

func renvoArmAsmIncRax(a *renvoAsm) {
	renvoArmAsmAddRegImm(a,0,0,1)
}

func renvoArmAsmIncRcx(a *renvoAsm) {
	renvoArmAsmAddRegImm(a,2,2,1)
}

func renvoArmAsmJnzLabel(a *renvoAsm, label int) {
	renvoArmAsmBCondLabel(a,label,1)
}

func renvoArmAsmJzLabel(a *renvoAsm, label int) {
	renvoArmAsmBCondLabel(a,label,0)
}

func renvoArmAsmLeaRegStack(a *renvoAsm, dst int, offset int) {
	renvoArmAsmAddRegImm(a,dst,11,-offset)
}

func renvoArmAsmLeave(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,13,11)
	renvoArmAsmEmit(a,0xe8bd4800)
}

func renvoArmAsmLoadByteRaxIndexRcx(a *renvoAsm) {
	renvoArmAsmAddRegReg(a,12,0,2)
	renvoArmAsmLoadRegMem(a,0,12,0,1)
}

func renvoArmAsmLoadQwordRaxIndexRcx8(a *renvoAsm) {
	renvoArmAsmAddRegRegShift(a,12,0,2,3)
	renvoArmAsmLoadRegMem(a,0,12,0,4)
}

func renvoArmAsmLoadQwordRaxIndexRcxDisp(a *renvoAsm, disp int) {
	renvoArmAsmAddRegReg(a,12,0,2)
	renvoArmAsmLoadRegMem(a,0,12,disp,4)
}

func renvoArmAsmLoadRaxBss(a *renvoAsm, bssOff int) {
	renvoArmAsmAccessRaxBss(a,bssOff,0xe79f0000|12)
}

func renvoArmAsmLoadRaxMemRdxDisp(a *renvoAsm, disp int) {
	renvoArmAsmLoadRegMem(a,0,1,disp,4)
}

func renvoArmAsmLoadRaxMemRdxDispSize(a *renvoAsm, disp int, size int) {
	renvoArmAsmLoadRegMem(a,0,1,disp,size)
}

func renvoArmAsmLoadRegStack(a *renvoAsm, dst int, offset int) {
	renvoArmAsmLoadRegMem(a,dst,11,-offset,4)
}

func renvoArmAsmMovR10BssAddr(a *renvoAsm, bssOff int) {
	renvoArmAsmMovRegAbs(a,8,bssOff,1)
}

func renvoArmAsmMovR8Rax(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,5,0)
}

func renvoArmAsmMovR9Rax(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,6,0)
}

func renvoArmAsmMovRaxBssAddr(a *renvoAsm, bssOff int) {
	renvoArmAsmMovRegAbs(a,0,bssOff,1)
}

func renvoArmAsmMovRaxDataAddr(a *renvoAsm, dataOff int) {
	renvoArmAsmMovRegAbs(a,0,dataOff,0)
}

func renvoArmAsmMovRaxImm(a *renvoAsm, imm int) {
	renvoArmAsmMovRegImm(a,0,imm)
}

func renvoArmAsmMovRaxImm64(a *renvoAsm, imm int) {
	renvoArmAsmMovRaxImm(a,imm)
}

func renvoArmAsmMovRaxRdx(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,0,1)
}

func renvoArmAsmMovRcxRax(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,2,0)
}

func renvoArmAsmMovRcxRdx(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,2,1)
}

func renvoArmAsmMovRdiRax(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,3,0)
}

func renvoArmAsmMovRdxImm(a *renvoAsm, imm int) {
	renvoArmAsmMovRegImm(a,1,imm)
}

func renvoArmAsmMovRdxRax(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,1,0)
}

func renvoArmAsmMovRsiRax(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,4,0)
}

func renvoArmAsmMulRegReg(a *renvoAsm, dst int, left int, right int) {
	renvoArmAsmEmit(a,0xe0000090|(dst<<16)|(right<<8)|left)
}

func renvoArmAsmNegRax(a *renvoAsm) {
	renvoArmAsmEmit(a,0xe2600000)
}

func renvoArmAsmPopRax(a *renvoAsm) {
	renvoArmAsmPopReg(a,0)
}

func renvoArmAsmPopRcx(a *renvoAsm) {
	renvoArmAsmPopReg(a,2)
}

func renvoArmAsmPopRdi(a *renvoAsm) {
	renvoArmAsmPopReg(a,3)
}

func renvoArmAsmPopRdx(a *renvoAsm) {
	renvoArmAsmPopReg(a,1)
}

func renvoArmAsmPopReg(a *renvoAsm, reg int) {
	renvoArmAsmEmit(a,0xe49d0004|(reg<<12))
}

func renvoArmAsmPopRsi(a *renvoAsm) {
	renvoArmAsmPopReg(a,4)
}

func renvoArmAsmPushImm(a *renvoAsm, imm int) {
	renvoArmAsmMovRegImm(a,9,imm)
	renvoArmAsmPushReg(a,9)
}

func renvoArmAsmPushRax(a *renvoAsm) {
	renvoArmAsmPushReg(a,0)
}

func renvoArmAsmPushRcx(a *renvoAsm) {
	renvoArmAsmPushReg(a,2)
}

func renvoArmAsmPushRdx(a *renvoAsm) {
	renvoArmAsmPushReg(a,1)
}

func renvoArmAsmPushReg(a *renvoAsm, reg int) {
	renvoArmAsmEmit(a,0xe52d0004|(reg<<12))
}

func renvoArmAsmRet(a *renvoAsm) {
	renvoArmAsmEmit(a,0xe12fff1e)
}

func renvoArmAsmSarRaxImm(a *renvoAsm, imm int) {
	renvoArmAsmEmit(a,0xe1a00040|(0<<12)|(imm<<7)|0)
}

func renvoArmAsmShlRaxImm(a *renvoAsm, imm int) {
	renvoArmAsmEmit(a,0xe1a00000|(0<<12)|(imm<<7)|0)
}

func renvoArmAsmShlRcxImm(a *renvoAsm, imm int) {
	renvoArmAsmEmit(a,0xe1a00000|(2<<12)|(imm<<7)|2)
}

func renvoArmAsmShrRaxImm(a *renvoAsm, imm int) {
	renvoArmAsmEmit(a,0xe1a00020|(0<<12)|(imm<<7)|0)
}

func renvoArmAsmStoreAlMemRdxRcx1(a *renvoAsm) {
	renvoArmAsmAddRegReg(a,12,1,2)
	renvoArmAsmStoreRegMem(a,0,12,0,1)
}

func renvoArmAsmStoreRaxBss(a *renvoAsm, bssOff int) {
	renvoArmAsmAccessRaxBss(a,bssOff,0xe78f0000|12)
}

func renvoArmAsmStoreRaxMemRdxDisp(a *renvoAsm, disp int) {
	renvoArmAsmStoreRegMem(a,0,1,disp,4)
}

func renvoArmAsmStoreRaxMemRdxDispSize(a *renvoAsm, disp int, size int) {
	renvoArmAsmStoreRegMem(a,0,1,disp,size)
}

func renvoArmAsmStoreRaxMemRdxRcx8(a *renvoAsm) {
	renvoArmAsmAddRegRegShift(a,12,1,2,3)
	renvoArmAsmStoreRegMem(a,0,12,0,4)
}

func renvoArmAsmStoreRegStack(a *renvoAsm, src int, offset int) {
	renvoArmAsmStoreRegMem(a,src,11,-offset,4)
}

func renvoArmAsmStoreSliceStack(a *renvoAsm, offset int) {
	renvoArmAsmStoreRegStack(a,0,offset)
	renvoArmAsmStoreRegStack(a,1,offset-8)
	renvoArmAsmStoreRegStack(a,2,offset-16)
}

func renvoArmAsmSubRaxRcx(a *renvoAsm) {
	renvoArmAsmSubRegReg(a,0,0,2)
}

func renvoArmAsmSubRegReg(a *renvoAsm, dst int, left int, right int) {
	renvoArmAsmEmit(a,0xe0400000|(left<<16)|(dst<<12)|right)
}

func renvoArmAsmSyscall(a *renvoAsm) {
	renvoArmAsmMovRegReg(a,7,0)
	renvoArmAsmMovRegReg(a,9,1)
	renvoArmAsmMovRegReg(a,0,3)
	renvoArmAsmMovRegReg(a,1,4)
	renvoArmAsmMovRegReg(a,2,9)
	renvoArmAsmMovRegReg(a,3,8)
	renvoArmAsmMovRegReg(a,4,8)
	renvoArmAsmMovRegImm(a,5,0)
	renvoArmAsmEmit(a,0xef000000)
}

func renvoArmAsmAccessRaxBss(a *renvoAsm, bssOff int, insn int) {
	at:=len(a.code)
	renvoAsmEmit32(a,0xe3000000|(12<<12))
	renvoAsmEmit32(a,0xe3400000|(12<<12))
	renvoAsmEmit32(a,insn)
	renvoAsmAddAbsReloc(a, at,bssOff,1)
}

func renvoArmAsmBCondLabel(a *renvoAsm, label int, cond int) {
	at:=len(a.code)
	renvoArmAsmEmit(a,(cond<<28)|0x0a000000)
	renvoAsmAddReloc(a, at,label)
}

func renvoArmAsmCallLabel(a *renvoAsm, label int) {
	at:=len(a.code)
	renvoArmAsmEmit(a,0xeb000000)
	renvoAsmAddReloc(a, at,label)
}

func renvoArmAsmCmpRcxRaxSet(a *renvoAsm, setcc int) {
	renvoArmAsmCmpRegReg(a,2,0)
	cond:=renvoArmCondFromSetcc(setcc)
	renvoArmAsmCsetRax(a,cond)
}

func renvoArmAsmJmpLabel(a *renvoAsm, label int) {
	at:=len(a.code)
	renvoArmAsmEmit(a,0xea000000)
	renvoAsmAddReloc(a, at,label)
}

func renvoArmAsmMovRegAbs(a *renvoAsm, reg int, off int, kind int) {
	at:=len(a.code)
	renvoAsmEmit32(a,0xe3000000|(reg<<12))
	renvoAsmEmit32(a,0xe3400000|(reg<<12))
	renvoAsmEmit32(a,0xe08f0000|(reg<<12)|reg)
	renvoAsmAddAbsReloc(a, at,off,kind)
}

func renvoArmAsmPatchMovRegImmAt(a *renvoAsm, at int, reg int, imm int) {
	part:=imm&65535
	renvoPut32At(a.code, at,0xe3000000|((part&0xf000)<<4)|(reg<<12)|(part&0x0fff))
	part=(imm>>16)&65535
	renvoPut32At(a.code, at+4,0xe3400000|((part&0xf000)<<4)|(reg<<12)|(part&0x0fff))
}

// Generated definition-owned relocation finalizer.
func rtgArmPatchRelocations(out *renvoAsm) {
	for i := 0; i+1 < len(out.relocs); i += 2 {
		at := int(renvo_runtime_UnsafeInt32At(out.relocs, i)) & 2147483647
		label := int(renvo_runtime_UnsafeInt32At(out.relocs, i+1)) & 2147483647
		target := renvoAsmLabelPosition(out, label)
		if target < 0 { continue }
		insn := renvoGet32At(out.code, at)

		if (insn & 0x0e000000) == 0x0a000000 {
			displacement := target - (at + 8)
			renvoPut32At(out.code, at, (insn&0xff000000)|((displacement/4)&0x00ffffff))
		}
	}
}
