// Code generated by go generate ./internal/targetinfo; DO NOT EDIT.

package main

const renvoSupportedTargets = "linux/amd64, linux/386, linux/aarch64, linux/arm, windows/amd64, windows/386, windows/arm64, darwin/arm64, wasi/wasm32, vm/vm32"

func renvoParseTargetArg(target string) int {
	if target == "linux/amd64" {
		return renvoTargetLinuxAmd64
	}
	if target == "linux/386" {
		return renvoTargetLinux386
	}
	if target == "linux/aarch64" {
		return renvoTargetLinuxAarch64
	}
	if target == "linux/arm" {
		return renvoTargetLinuxArm
	}
	if target == "windows/amd64" {
		return renvoTargetWindowsAmd64
	}
	if target == "windows/386" {
		return renvoTargetWindows386
	}
	if target == "wasi/wasm32" {
		return renvoTargetWasiWasm32
	}
	if target == "darwin/arm64" {
		return renvoTargetDarwinArm64
	}
	if target == "linux-kernel/amd64" {
		return renvoTargetLinuxKernelAmd64
	}
	if target == "windows/arm64" {
		return renvoTargetWindowsArm64
	}
	if target == "vm/vm32" {
		return renvoTargetVM32
	}
	return renvoRTGParseTargetArg(target)
}

func renvoBuiltInTargetBinding(target int) (string, string, int, bool) {
	if target == renvoTargetLinuxAmd64 {
		return "linux/amd64", "4\xfd\x9b͘3]\x8aU=)\xfa\xc2\xe8\xd5`̵\xf1\x12\x1e$m8\xc8tf\xae\xe3\x18\x94R", 3, true
	}
	if target == renvoTargetLinux386 {
		return "linux/386", "\x05T\x05\x1e\x13^g\x9b\xed\xfa6\xe3#\t\x97꠱\x8a\xee\x19\x89\xe0\xc4,Azƺ\xf4\xd4G", 3, true
	}
	if target == renvoTargetLinuxAarch64 {
		return "linux/aarch64", "\xd81\x8e\xb1\xd2A\x19\\\x89\xdb\xd8F\x12\xc1]\xbfq}\x8e\xa9\x1d\xcef\x95\u0086\x89\b\xa1\xdd3\x15", 3, true
	}
	if target == renvoTargetLinuxArm {
		return "linux/arm", "\x94isB\xbdpqӽ\xa6\x94\x17\xbb\n\xce\x04\xd0\xfb\xdd$\xaat\x88\fd\x1ct&+\xe8\xec\xa7", 3, true
	}
	if target == renvoTargetWindowsAmd64 {
		return "windows/amd64", "o\xf6\x1d\xbd/\xb7c\xd9%Ȅ\xc7\xcb\x17\xb1\xd7Mc6'M\xaev\x89\xd2\r7\xa3*tƸ", 3, true
	}
	if target == renvoTargetWindows386 {
		return "windows/386", "\x91\x83\xec\x9dQ\x19\x84\xb9\x13\xcd\x069Nw\xc3Jò\xab\xab\xa68\xbcv.HJ\xa62,\x1en", 3, true
	}
	if target == renvoTargetWasiWasm32 {
		return "wasi/wasm32", "\b~\xfa\xc3\xf6\xde\xf8\xabN\x18Ƚ\xf5\xe7\x01\x03\xaa\x9f\xd8\x1fL\xf5\xb7\x1fR\xa7xO\xc2\x14\n\xd5", 3, true
	}
	if target == renvoTargetDarwinArm64 {
		return "darwin/arm64", "q7\x91\xdf(\xa1x\"\xa2\x13\xc2j7IR>\x11Aؘ\x9e\x11}\xcc\x1e\x06yU\xd5\xcb{\r", 3, true
	}
	if target == renvoTargetLinuxKernelAmd64 {
		return "linux-kernel/amd64", "$!\xef\xffp\x92\x95\xb4\x93\xadA\x19\x9f\xb3\xb9\x18*\xca2\xd2-\x90\x06\xbd\xa0\xb64^\xb9\xc4j\xa1", 3, true
	}
	if target == renvoTargetWindowsArm64 {
		return "windows/arm64", "\xe3\xbc\xf5\xf3\xdaN\"\x9a\x88\xa5KX\x82\\s\x85\xf3\xffZ\x88\x8c\x97-\xf7)\x8e\xeb|\x99\v\x99\xbb", 3, true
	}
	if target == renvoTargetVM32 {
		return "vm/vm32", "\x1abX\x92\xac\xef\x03D4\xb4\xadūe]K\xb4A\xa2/D\xc2\xf1\x03I\x11\"\x90\x92\xcdy\x89", 3, true
	}
	return "", "", 0, false
}
