// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: architecture-kernel
package main


type RTGRegister struct {
	Code int
	Valid bool
}

type RTGLabel struct {
	Code int
	Valid bool
}

type RTGAddress struct {
	Target       RTGLabel
	Addend       int
	Base         RTGRegister
	Index        RTGRegister
	Displacement int
	Scale        int
}

type RTGCondition struct {
	Code       int
	SetOpcode  byte
	JumpOpcode byte
}
type RTGSymbol struct {
	nameStart int
	nameEnd   int
	label     int
}
type RTGShiftDirection int

const (
	RTGShiftLeft RTGShiftDirection = 1
	RTGShiftRight RTGShiftDirection = 2
)

const RTGRelocationAbsoluteData = 0
const RTGRelocationAbsoluteBSS = 1

const RTGScalarByte = 3
const RTGScalarInt8 = 7
const RTGScalarInt16 = 8
const RTGScalarInt32 = 9
const RTGScalarUint16 = 16
const RTGScalarUint32 = 17

var RTGNoRegister = RTGRegister{}

type RTGEmitter struct {
	asm    *renvoAsm
	relocs []int
}

func renvoRTGEmitter(asm *renvoAsm) RTGEmitter {
	return RTGEmitter{asm: asm}
}

func renvoRTGLabel(code int) RTGLabel {
	return RTGLabel{Code: code, Valid: code >= 0}
}

func renvoRTGLabelCode(code int) int {
	return code
}

func RTGLabelFromCode(code int) RTGLabel {
	return renvoRTGLabel(code)
}

func (out *RTGEmitter) Len() int {
	return len(out.asm.code)
}

func (out *RTGEmitter) Byte(value byte) {
	out.asm.code = append(out.asm.code, value)
}

func (out *RTGEmitter) Int8(value int) {
	out.Byte(byte(value))
}

func (out *RTGEmitter) Uint16(value int) {
	out.asm.code = append(out.asm.code, byte(value), byte(value >> 8))
}

func (out *RTGEmitter) Uint24(value int) {
	out.Uint16(value)
	out.Byte(byte(value >> 16))
}

func RTGByte(out *RTGEmitter, value byte) {
	out.Byte(value)
}

func (out *RTGEmitter) Uint32(value uint32) {
	out.asm.code = append(out.asm.code, byte(value), byte(value >> 8), byte(value >> 16), byte(value >> 24))
}

func (out *RTGEmitter) Int32(value int) {
	out.Uint32(uint32(value))
}

func RTGUint32(out *RTGEmitter, value int) {
	out.Uint32(uint32(value))
}

func (out *RTGEmitter) Uint64(value uint64) {
	out.Uint32(uint32(value))
	out.Uint32(uint32(value >> 32))
}

func (out *RTGEmitter) Int64(value int) {
	out.Uint64(uint64(value))
}

func (out *RTGEmitter) Bytes2(v0 int, v1 int) {
	out.Byte(byte(v0))
	out.Byte(byte(v1))
}

func (out *RTGEmitter) Bytes3(v0 int, v1 int, v2 int) {
	out.Bytes2(v0, v1)
	out.Byte(byte(v2))
}

func (out *RTGEmitter) Bytes4(v0 int, v1 int, v2 int, v3 int) {
	out.Bytes3(v0, v1, v2)
	out.Byte(byte(v3))
}

func (out *RTGEmitter) Text(value string) {
	for i := 0; i < len(value); i++ {
		out.Byte(value[i])
	}
}

func RTGUint64(out *RTGEmitter, value uint64) {
	out.Uint64(value)
}

func (out *RTGEmitter) PatchUint32(at int, value int) {
	renvoPut32At(out.asm.code, at, value)
}

func (out *RTGEmitter) AbsoluteReloc(at int, offset int, kind int) {
	renvoAsmAddAbsReloc(out.asm, at, offset, kind)
}

func (out *RTGEmitter) RelocAt(at int, label int) {
	if label >= 0 {
		renvoAsmAddReloc(out.asm, at, label)
	}
}

func (out *RTGEmitter) PrimaryLoad() int {
	return out.asm.lastPrimaryLoad
}

func (out *RTGEmitter) SetPrimaryLoad(value int) {
	out.asm.lastPrimaryLoad = value
}

func (out *RTGEmitter) ByteAt(at int) byte {
	return out.asm.code[at]
}

func (out *RTGEmitter) SetByteAt(at int, value byte) {
	out.asm.code[at] = value
}

func (out *RTGEmitter) AddByteAt(at int, value byte) {
	out.asm.code[at] += value
}

func (out *RTGEmitter) AppendByte(value int) {
	out.asm.code = append(out.asm.code, byte(value))
}

func (out *RTGEmitter) Truncate(size int) {
	out.asm.code = out.asm.code[:size]
}

func (out *RTGEmitter) Code() []byte {
	return out.asm.code
}

func (out *RTGEmitter) SetCode(value []byte) {
	out.asm.code = value
}

func (out *RTGEmitter) Data() []byte {
	return out.asm.data
}

func (out *RTGEmitter) BSSSize() int {
	return out.asm.bssSize
}

func (out *RTGEmitter) RelocationCount() int {
	return len(out.asm.relocs) / 2
}

func (out *RTGEmitter) RelocationAt(index int) (int, int) {
	at := index * 2
	return int(out.asm.relocs[at]), int(out.asm.relocs[at+1])
}

func (out *RTGEmitter) RelocationOffset(index int) int {
	return int(out.asm.relocs[index*2])
}

func (out *RTGEmitter) RelocationLabel(index int) int {
	return int(out.asm.relocs[index*2+1])
}

func (out *RTGEmitter) RelocationWordCount() int {
	return len(out.asm.relocs)
}

func (out *RTGEmitter) RelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.asm.relocs, index))
}

func (out *RTGEmitter) AbsoluteRelocationCount() int {
	return len(out.asm.absRelocs) / 3
}

func (out *RTGEmitter) AbsoluteRelocationAt(index int) (int, int, int) {
	at := index * 3
	return int(out.asm.absRelocs[at]), int(out.asm.absRelocs[at+1]), int(out.asm.absRelocs[at+2])
}

func (out *RTGEmitter) AbsoluteRelocationOffset(index int) int {
	return int(out.asm.absRelocs[index*3])
}

func (out *RTGEmitter) AbsoluteRelocationAddend(index int) int {
	return int(out.asm.absRelocs[index*3+1])
}

func (out *RTGEmitter) AbsoluteRelocationKind(index int) int {
	return int(out.asm.absRelocs[index*3+2])
}

func (out *RTGEmitter) AbsoluteRelocationWordCount() int {
	return len(out.asm.absRelocs)
}

func (out *RTGEmitter) AbsoluteRelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.asm.absRelocs, index))
}

func (out *RTGEmitter) LabelPosition(label int) int {
	return renvoAsmLabelPosition(out.asm, label)
}

func (out *RTGEmitter) SymbolCount() int {
	return len(out.asm.symbols)
}

func (out *RTGEmitter) SymbolPC(index int) int {
	return renvoAsmLabelPosition(out.asm, out.asm.symbols[index].label)
}

func (out *RTGEmitter) SymbolNameEquals(index int, name string) bool {
	symbol := &out.asm.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.asm.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func (out *RTGEmitter) SymbolNameLength(index int) int {
	symbol := &out.asm.symbols[index]
	return symbol.nameEnd - symbol.nameStart
}

func (out *RTGEmitter) SymbolNameByte(index int, offset int) byte {
	symbol := &out.asm.symbols[index]
	return out.asm.symbolName[symbol.nameStart+offset]
}

func (out *RTGEmitter) Symbol(index int) *RTGSymbol {
	symbol := &out.asm.symbols[index]
	return &RTGSymbol{nameStart: symbol.nameStart, nameEnd: symbol.nameEnd, label: symbol.label}
}

func (out *RTGEmitter) SymbolNameByteAt(index int) byte {
	return out.asm.symbolName[index]
}

func RTGPatchUint32(out *RTGEmitter, at int, value int) {
	out.PatchUint32(at, value)
}

func (out *RTGEmitter) NewLabel() RTGLabel {
	return RTGLabel{Code: renvoAsmNewLabel(out.asm), Valid: true}
}

func (out *RTGEmitter) Mark(label RTGLabel) {
	if label.Valid {
		renvoAsmMarkLabel(out.asm, label.Code)
	}
}

func (out *RTGEmitter) Rel32(label RTGLabel) {
	out.Rel32Addend(label, 0)
}

func (out *RTGEmitter) Rel32Addend(label RTGLabel, addend int) {
	at := len(out.asm.code)
	out.Uint32(uint32(0))
	if label.Valid {
		out.relocs = append(out.relocs, at, label.Code, addend)
	}
}

func (out *RTGEmitter) Reloc(label RTGLabel) {
	if label.Valid && len(out.asm.code) >= 4 {
		renvoAsmAddReloc(out.asm, len(out.asm.code)-4, label.Code)
	}
}

func RTGReloc(out *RTGEmitter, label RTGLabel) {
	out.Reloc(label)
}

func RTGAddressValid(address RTGAddress) bool {
	return address.Target.Valid
}

func RTGAddressRel32Addend(out *RTGEmitter, address RTGAddress) {
	out.Rel32Addend(address.Target, address.Addend)
}

func RTGInt8Fits(value int) bool {
	return value >= -128 && value <= 127
}

func RTGPopPrimary(out *RTGEmitter) {
	out.Byte(0x58)
}

func RTGArenaMark() int {
	return renvo_runtime_ArenaMark()
}

func RTGArenaReset(mark int) {
	renvo_runtime_ArenaReset(mark)
}

func RTGByteAt(in []byte, at int) byte {
	return in[at]
}

func RTGGet32At(in []byte, at int) int {
	return int(in[at]) | int(in[at+1])<<8 | int(in[at+2])<<16 | int(in[at+3])<<24
}

func RTGPut32At(out []byte, at int, value int) {
	out[at] = byte(value)
	out[at+1] = byte(value >> 8)
	out[at+2] = byte(value >> 16)
	out[at+3] = byte(value >> 24)
}

func RTGAppend32(out []byte, value int) []byte {
	out = append(out, byte(value))
	out = append(out, byte(value>>8))
	out = append(out, byte(value>>16))
	out = append(out, byte(value>>24))
	return out
}

func RTGAlignValue(value int, alignment int) int {
	return (value + alignment - 1) & -alignment
}

func RTGAlign8(value int) int {
	return (value + 7) & -8
}

func RTGMakeIntScratch(capacity int) []int {
	return make([]int, 0, capacity)
}

func RTGMakeByteBuffer(length int) []byte {
	return make([]byte, length)
}

func (out *RTGEmitter) Patch() {
	for i := 0; i+2 < len(out.relocs); i += 3 {
		at := out.relocs[i]
		label := out.relocs[i+1]
		addend := out.relocs[i+2]
		target := renvoAsmLabelPosition(out.asm, label)
		if at < 0 || at+4 > len(out.asm.code) || target < 0 {
			continue
		}
		renvoPut32At(out.asm.code, at, target+addend-(at+4))
	}
}

func RTGSignedFits(value int64, bits int) bool {
	if bits <= 0 {
		return false
	}
	if bits >= 63 {
		return true
	}
	limit := int64(1) << (bits - 1)
	return value >= -limit && value < limit
}

func RTGUnsignedFits(value uint64, bits int) bool {
	if bits <= 0 {
		return false
	}
	if bits >= 63 {
		return true
	}
	return value < uint64(1) << bits
}

func RTGLog2(value int) int {
	result := 0
	for value > 1 {
		value >>= 1
		result++
	}
	return result
}

type renvoRTGAddress struct {
	Target       int
	TargetValid  bool
	Addend       int
	Base         RTGRegister
	Index        RTGRegister
	Displacement int
	Scale        int
}

func (out *renvoAsm) Byte(value byte) {
	renvoAsmEmit8(out, int(value))
}

func (out *renvoAsm) Uint32(value uint32) {
	renvoAsmEmit32(out, int(value))
}

func (out *renvoAsm) Uint64(value uint64) {
	renvoAsmEmit32(out, int(value))
	renvoAsmEmit32(out, int(value >> 32))
}

func (out *renvoAsm) PatchUint32(at int, value int) {
	renvoPut32At(out.code, at, value)
}

func (out *renvoAsm) NewLabel() int {
	return renvoAsmNewLabel(out)
}

func (out *renvoAsm) Mark(label int) {
	if label >= 0 {
		renvoAsmMarkLabel(out, label)
	}
}

func (out *renvoAsm) Rel32(label int) {
	out.Rel32Addend(label, 0)
}

func (out *renvoAsm) Rel32Addend(label int, addend int) {
	at := len(out.code)
	renvoAsmEmit32(out, addend)
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	}
}

func (out *renvoAsm) Reloc(label int) {
	if label >= 0 && len(out.code) >= 4 {
		renvoAsmAddReloc(out, len(out.code)-4, label)
	}
}

func (out *renvoAsm) Patch() {
	renvoAsmPatch(out)
}

func (out *renvoAsm) Code() []byte {
	return out.code
}

func (out *renvoAsm) SetCode(value []byte) {
	out.code = value
}

func (out *renvoAsm) Data() []byte {
	return out.data
}

func (out *renvoAsm) BSSSize() int {
	return out.bssSize
}

func (out *renvoAsm) RelocationCount() int {
	return len(out.relocs) / 2
}

func (out *renvoAsm) RelocationAt(index int) (int, int) {
	at := index * 2
	return int(out.relocs[at]), int(out.relocs[at+1])
}

func (out *renvoAsm) RelocationOffset(index int) int {
	return int(out.relocs[index*2])
}

func (out *renvoAsm) RelocationLabel(index int) int {
	return int(out.relocs[index*2+1])
}

func (out *renvoAsm) RelocationWordCount() int {
	return len(out.relocs)
}

func (out *renvoAsm) RelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.relocs, index))
}

func (out *renvoAsm) AbsoluteRelocationCount() int {
	return len(out.absRelocs) / 3
}

func (out *renvoAsm) AbsoluteRelocationAt(index int) (int, int, int) {
	at := index * 3
	return int(out.absRelocs[at]), int(out.absRelocs[at+1]), int(out.absRelocs[at+2])
}

func (out *renvoAsm) AbsoluteRelocationOffset(index int) int {
	return int(out.absRelocs[index*3])
}

func (out *renvoAsm) AbsoluteRelocationAddend(index int) int {
	return int(out.absRelocs[index*3+1])
}

func (out *renvoAsm) AbsoluteRelocationKind(index int) int {
	return int(out.absRelocs[index*3+2])
}

func (out *renvoAsm) AbsoluteRelocationWordCount() int {
	return len(out.absRelocs)
}

func (out *renvoAsm) AbsoluteRelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.absRelocs, index))
}

func (out *renvoAsm) LabelPosition(label int) int {
	return renvoAsmLabelPosition(out, label)
}

func (out *renvoAsm) SymbolCount() int {
	return len(out.symbols)
}

func (out *renvoAsm) SymbolPC(index int) int {
	return renvoAsmLabelPosition(out, out.symbols[index].label)
}

func (out *renvoAsm) SymbolNameEquals(index int, name string) bool {
	symbol := &out.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func (out *renvoAsm) SymbolNameLength(index int) int {
	symbol := &out.symbols[index]
	return symbol.nameEnd - symbol.nameStart
}

func (out *renvoAsm) SymbolNameByte(index int, offset int) byte {
	symbol := &out.symbols[index]
	return out.symbolName[symbol.nameStart+offset]
}

func (out *renvoAsm) Symbol(index int) *RTGSymbol {
	symbol := &out.symbols[index]
	return &RTGSymbol{nameStart: symbol.nameStart, nameEnd: symbol.nameEnd, label: symbol.label}
}

func (out *renvoAsm) SymbolNameByteAt(index int) byte {
	return out.symbolName[index]
}

func renvoRTGRelocationAt(out *renvoAsm, index int) (int, int) {
	at := index * 2
	return int(out.relocs[at]), int(out.relocs[at+1])
}

func renvoRTGAbsoluteRelocationAt(out *renvoAsm, index int) (int, int, int) {
	at := index * 3
	return int(out.absRelocs[at]), int(out.absRelocs[at+1]), int(out.absRelocs[at+2])
}

func renvoRTGSymbolPC(out *renvoAsm, index int) int {
	return renvoAsmLabelPosition(out, out.symbols[index].label)
}

func renvoRTGSymbolNameEquals(out *renvoAsm, index int, name string) bool {
	symbol := &out.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func renvoRTGAddressValid(address renvoRTGAddress) bool {
	return address.TargetValid
}

func renvoRTGAddressRel32Addend(out *renvoAsm, address renvoRTGAddress) {
	out.Rel32Addend(address.Target, address.Addend)
}

func renvoRTGByte(out *renvoAsm, value byte) {
	renvoAsmEmit8(out, int(value))
}

func renvoRTGUint32(out *renvoAsm, value int) {
	renvoAsmEmit32(out, value)
}

func renvoRTGUint64(out *renvoAsm, value uint64) {
	renvoAsmEmit32(out, int(value))
	renvoAsmEmit32(out, int(value >> 32))
}

func renvoRTGPatchUint32(out *renvoAsm, at int, value int) {
	renvoPut32At(out.code, at, value)
}

func renvoRTGNewLabel(out *renvoAsm) int {
	return renvoAsmNewLabel(out)
}

func renvoRTGMark(out *renvoAsm, label int) {
	if label >= 0 {
		renvoAsmMarkLabel(out, label)
	}
}

func renvoRTGReloc(out *renvoAsm, label int) {
	if label >= 0 && len(out.code) >= 4 {
		renvoAsmAddReloc(out, len(out.code)-4, label)
	}
}
