// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: target-projection/darwin/arm64
// unit: native c4a1acba64b4846279b9d494ef4db6344d6104b5425e1e334e51ac849e293424
package main


const rtgBuiltinDarwinAarch64PackageMachCodeOffset = 0x1000
const rtgBuiltinDarwinAarch64PackageMachImageBase = 0x100000000
const rtgBuiltinDarwinAarch64PackageMachPageSize = 0x4000
const rtgBuiltinDarwinAarch64PackageMachLibSystem = "/usr/lib/libSystem.B.dylib"
const rtgBuiltinDarwinAarch64PackageMachCallInteger = 0
const rtgBuiltinDarwinAarch64PackageMachCallString = 1
const rtgBuiltinDarwinAarch64PackageMachCallSlice = 2
const rtgBuiltinDarwinAarch64PackageMachCallFloat32 = 3
const rtgBuiltinDarwinAarch64PackageMachCallFloat64 = 4
const rtgBuiltinDarwinAarch64PackageMachCallIntegerFloat64 = 5
const rtgBuiltinDarwinAarch64PackageMachCallIntegerFloat32 = 6
type rtgBuiltinDarwinAarch64PackageMachImportLayout struct {
	got []int
}
func rtgBuiltinDarwinAarch64PackageMachStaticImport(out *renvoAsm, importID int) int {
	library := out.staticImports[importID].dll
	name := out.staticImports[importID].name
	if len(name) == 0 || name[0] != '_' {
		name = "_" + name
	}
	return out.DynamicImport(library, name)
}
func rtgBuiltinDarwinAarch64PackageMachIntegerStaticCall(
	out *renvoAsm, importIndex int, parameterCount int,
) {
	registerWords := parameterCount
	if registerWords > 8 {
		registerWords = 8
	}
	for i := 0; i < registerWords; i++ {
		renvoAarch64AsmPopReg(out, i)
	}
	stackWords := parameterCount - registerWords
	if stackWords == 0 {
		for i := registerWords; i < 8; i++ {
			renvoAarch64AsmMovRegImm(out, i, 0)
		}
		renvoAarch64AsmCallLabel(out, out.DynamicImportLabel(importIndex))
		return
	}
	renvoAarch64AsmEmit(out, 0x910003e9)
	savedSPOff := stackWords * 8
	allocation := renvoAlignValue(savedSPOff+8, 16)
	renvoAarch64AsmAddRegImm(out, 31, 31, -allocation)
	for i := 0; i < stackWords; i++ {
		renvoAarch64AsmLoadRegMem(out, 10, 9, i*16, 8)
		renvoAarch64AsmStoreRegMem(out, 10, 31, i*8, 8)
	}
	renvoAarch64AsmStoreRegMem(out, 9, 31, savedSPOff, 8)
	renvoAarch64AsmCallLabel(out, out.DynamicImportLabel(importIndex))
	renvoAarch64AsmMovRegReg(out, 10, 0)
	renvoAarch64AsmLoadRegMem(out, 9, 31, savedSPOff, 8)
	renvoAarch64AsmEmit(out, 0x9100013f)
	renvoAarch64AsmAddRegImm(out, 31, 31, stackWords*16)
	renvoAarch64AsmMovRegReg(out, 0, 10)
}
func rtgBuiltinDarwinAarch64PackageMachStaticCall(out *renvoAsm, importID int, wordCount int) {
	_ = wordCount
	parameterCount := out.staticCallParamCount
	importIndex := rtgBuiltinDarwinAarch64PackageMachStaticImport(out, importID)
	integerOnly := true
	if parameterCount <= 16 {
		for i := 0; i < parameterCount; i++ {
			if int(out.staticCallParamKinds[i]) != rtgBuiltinDarwinAarch64PackageMachCallInteger {
				integerOnly = false
			}
		}
	}
	if parameterCount > 8 && integerOnly {
		rtgBuiltinDarwinAarch64PackageMachIntegerStaticCall(out, importIndex, parameterCount)
		return
	}
	intReg := 0
	floatReg := 0
	for i := 0; i < parameterCount; i++ {
		kind := int(out.staticCallParamKinds[i])
		if kind == rtgBuiltinDarwinAarch64PackageMachCallFloat32 || kind == rtgBuiltinDarwinAarch64PackageMachCallFloat64 || kind == rtgBuiltinDarwinAarch64PackageMachCallIntegerFloat64 ||
			kind == rtgBuiltinDarwinAarch64PackageMachCallIntegerFloat32 {
			renvoAarch64AsmPopReg(out, 16)
			if kind == rtgBuiltinDarwinAarch64PackageMachCallFloat32 {
				renvoAarch64AsmEmit(out, 0x1e270000|(16<<5)|floatReg)
			} else if kind == rtgBuiltinDarwinAarch64PackageMachCallFloat64 {
				renvoAarch64AsmEmit(out, 0x9e670000|(16<<5)|floatReg)
			} else if kind == rtgBuiltinDarwinAarch64PackageMachCallIntegerFloat32 {
				renvoAarch64AsmEmit(out, 0x9e220000|(16<<5)|floatReg)
			} else {
				renvoAarch64AsmEmit(out, 0x9e620000|(16<<5)|floatReg)
			}
			floatReg++
			continue
		}
		renvoAarch64AsmPopReg(out, intReg)
		if kind == rtgBuiltinDarwinAarch64PackageMachCallString {
			renvoAarch64AsmPopReg(out, 16)
		} else if kind == rtgBuiltinDarwinAarch64PackageMachCallSlice {
			renvoAarch64AsmPopReg(out, 16)
			renvoAarch64AsmPopReg(out, 16)
		}
		intReg++
	}
	for intReg < 8 {
		renvoAarch64AsmMovRegImm(out, intReg, 0)
		intReg++
	}
	renvoAarch64AsmCallLabel(out, out.DynamicImportLabel(importIndex))
	resultFloatReg := out.staticCallResultFloat
	if resultFloatReg >= 0 {
		if resultFloatReg >= 8 {
			resultFloatReg -= 8
			renvoAarch64AsmEmit(out, 0x1e260000|(resultFloatReg<<5))
		} else {
			renvoAarch64AsmEmit(out, 0x9e660000|(resultFloatReg<<5))
		}
	}
}
func rtgBuiltinDarwinAarch64PackageMachAppendStringZ(out []byte, value string) []byte {
	for i := 0; i < len(value); i++ {
		out = append(out, value[i])
	}
	return append(out, 0)
}
func rtgBuiltinDarwinAarch64PackageMachAppendUntil(out []byte, size int) []byte {
	for len(out) < size {
		out = append(out, 0)
	}
	return out
}
func rtgBuiltinDarwinAarch64PackageMachAppendULEB(out []byte, value int) []byte {
	for {
		b := byte(value & 127)
		value = value >> 7
		if value != 0 {
			b = b | 128
		}
		out = append(out, b)
		if value == 0 {
			return out
		}
	}
}
func rtgBuiltinDarwinAarch64PackageMachAppendName16(out []byte, name string) []byte {
	for i := 0; i < 16; i++ {
		if i < len(name) {
			out = append(out, name[i])
		} else {
			out = append(out, 0)
		}
	}
	return out
}
func rtgBuiltinDarwinAarch64PackageMachExtraDylibs(out *renvoAsm) []string {
	var dylibs []string
	for i := 0; i < out.DynamicImportCount(); i++ {
		dylib := out.DynamicImportLibrary(i)
		if dylib == rtgBuiltinDarwinAarch64PackageMachLibSystem {
			continue
		}
		found := false
		for j := 0; j < len(dylibs); j++ {
			if dylibs[j] == dylib {
				found = true
			}
		}
		if !found {
			dylibs = append(dylibs, dylib)
		}
	}
	return dylibs
}
func rtgBuiltinDarwinAarch64PackageMachDylibOrdinal(out *renvoAsm, dylib string) int {
	if dylib == rtgBuiltinDarwinAarch64PackageMachLibSystem {
		return 1
	}
	dylibs := rtgBuiltinDarwinAarch64PackageMachExtraDylibs(out)
	for i := 0; i < len(dylibs); i++ {
		if dylibs[i] == dylib {
			return i + 2
		}
	}
	return 0
}
func rtgBuiltinDarwinAarch64PackageMachPatchAbsoluteRelocations(
	out *renvoAsm, dataFileOff int, dataSize int,
) {
	for i := 0; i < len(out.absRelocs) / 3; i++ {
		at := int(out.absRelocs[i*3])
		addend := int(out.absRelocs[i*3+1])
		kind := int(out.absRelocs[i*3+2])
		target, resolved := renvoRTGResolveAbsoluteRelocation(
			out, kind, addend, dataFileOff, dataFileOff+dataSize)
		if !resolved {
			continue
		}
		insn := renvoGet32At(out.code, at)
		reg := insn & 31
		address := rtgBuiltinDarwinAarch64PackageMachImageBase + target
		pc := rtgBuiltinDarwinAarch64PackageMachImageBase + rtgBuiltinDarwinAarch64PackageMachCodeOffset + at
		delta := (address >> 12) - (pc >> 12)
		imm := delta & 0x1fffff
		renvoPut32At(out.code, at,
			0x90000000|((imm&3)<<29)|
				(((imm>>2)&0x7ffff)<<5)|reg)
		renvoPut32At(out.code, at+4,
			0x91000000|((address&0xfff)<<10)|(reg<<5)|reg)
		renvoPut32At(out.code, at+8, 0xd503201f)
		renvoPut32At(out.code, at+12, 0xd503201f)
	}
}
func rtgBuiltinDarwinAarch64PackageMachPrepareImports(
	out *renvoAsm,
) rtgBuiltinDarwinAarch64PackageMachImportLayout {
	var layout rtgBuiltinDarwinAarch64PackageMachImportLayout
	count := out.DynamicImportCount()
	layout.got = make([]int, count)
	stubs := make([]int, count)
	for i := 0; i < count; i++ {
		renvoAarch64AsmAlign(out)
		renvoAsmMarkLabel(out, out.DynamicImportLabel(i))
		stubs[i] = len(out.code)
		renvoAarch64AsmEmit(out, 0x90000010)
		renvoAarch64AsmEmit(out, 0xf9400210)
		renvoAarch64AsmEmit(out, 0xd61f0200)
	}
	out.Patch()
	dataFileOff := renvoAlignValue(
		rtgBuiltinDarwinAarch64PackageMachCodeOffset+len(out.code), rtgBuiltinDarwinAarch64PackageMachPageSize)
	data := out.data
	data = rtgBuiltinDarwinAarch64PackageMachAppendUntil(data, renvoAlignValue(len(data), 8))
	for i := 0; i < count; i++ {
		layout.got[i] = len(data)
		data = rtgBuiltinDarwinAarch64PackageMachAppend64(data, 0)
	}
	data = rtgBuiltinDarwinAarch64PackageMachAppendUntil(
		data, renvoAlignValue(len(data), rtgBuiltinDarwinAarch64PackageMachPageSize))
	out.data = data
	rtgBuiltinDarwinAarch64PackageMachPatchAbsoluteRelocations(
		out, dataFileOff, len(data))
	for i := 0; i < count; i++ {
		stubAt := stubs[i]
		target := rtgBuiltinDarwinAarch64PackageMachImageBase +
			dataFileOff + layout.got[i]
		pc := rtgBuiltinDarwinAarch64PackageMachImageBase +
			rtgBuiltinDarwinAarch64PackageMachCodeOffset + stubAt
		rtgBuiltinDarwinAarch64PackageMachPatchADRP(out, stubAt, pc, target)
		pageOff := target & 0xfff
		renvoPut32At(out.code, stubAt+4, 0xf9400210|((pageOff/8)<<10))
	}
	return layout
}
func rtgBuiltinDarwinAarch64PackageMachBuildBindData(
	out *renvoAsm, got []int,
) []byte {
	bind := make([]byte, 0, 256)
	bind = append(bind, 0x51)
	for i := 0; i < out.DynamicImportCount(); i++ {
		ordinal := rtgBuiltinDarwinAarch64PackageMachDylibOrdinal(
			out, out.DynamicImportLibrary(i))
		if ordinal < 16 {
			bind = append(bind, byte(0x10|ordinal))
		} else {
			bind = append(bind, 0x20)
			bind = rtgBuiltinDarwinAarch64PackageMachAppendULEB(bind, ordinal)
		}
		bind = append(bind, 0x40)
		bind = rtgBuiltinDarwinAarch64PackageMachAppendStringZ(
			bind, out.DynamicImportName(i))
		bind = append(bind, 0x72)
		bind = rtgBuiltinDarwinAarch64PackageMachAppendULEB(bind, got[i])
		bind = append(bind, 0x90)
	}
	return append(bind, 0)
}
func rtgBuiltinDarwinAarch64PackageMachBuildStringTable(out *renvoAsm) []byte {
	strtab := make([]byte, 0, 128)
	strtab = append(strtab, 0)
	strtab = rtgBuiltinDarwinAarch64PackageMachAppendStringZ(strtab, "_main")
	for i := 0; i < out.DynamicImportCount(); i++ {
		strtab = rtgBuiltinDarwinAarch64PackageMachAppendStringZ(
			strtab, out.DynamicImportName(i))
	}
	return strtab
}
func rtgBuiltinDarwinAarch64PackageMachBuildSymbolTable(out *renvoAsm) []byte {
	count := out.DynamicImportCount()
	symtab := make([]byte, 0, 16*(count+1))
	symtab = rtgBuiltinDarwinAarch64PackageMachAppend32(symtab, 1)
	symtab = append(symtab, 0x0f, 1)
	symtab = rtgBuiltinDarwinAarch64PackageMachAppend16(symtab, 0)
	symtab = rtgBuiltinDarwinAarch64PackageMachAppend64(
		symtab, rtgBuiltinDarwinAarch64PackageMachImageBase+rtgBuiltinDarwinAarch64PackageMachCodeOffset)
	nameOff := 7
	for i := 0; i < count; i++ {
		symtab = rtgBuiltinDarwinAarch64PackageMachAppend32(symtab, nameOff)
		symtab = append(symtab, 1, 0)
		symtab = rtgBuiltinDarwinAarch64PackageMachAppend16(symtab, 0x100)
		symtab = rtgBuiltinDarwinAarch64PackageMachAppend64(symtab, 0)
		nameOff += len(out.DynamicImportName(i)) + 1
	}
	return symtab
}
func rtgBuiltinDarwinAarch64PackageMachHeader(
	out *renvoAsm,
	textFileSize int,
	dataFileOff int,
	dataFileSize int,
	dataVMSize int,
	linkeditOff int,
	linkeditSize int,
	bindOff int,
	bindSize int,
	symOff int,
	symbolCount int,
	strOff int,
	strSize int,
	undefinedCount int,
	sigOff int,
	sigSize int,
) []byte {
	dylibs := rtgBuiltinDarwinAarch64PackageMachExtraDylibs(out)
	commandSize := 856
	for i := 0; i < len(dylibs); i++ {
		commandSize += rtgBuiltinDarwinAarch64PackageMachDylibCommandSize(dylibs[i])
	}
	header := make([]byte, 0, rtgBuiltinDarwinAarch64PackageMachCodeOffset)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0xfeedfacf)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x0100000c)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 2)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 13+len(dylibs))
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, commandSize)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x200085)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppendSegment64(
		header, "__PAGEZERO", 0, rtgBuiltinDarwinAarch64PackageMachImageBase,
		0, 0, 0, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppendTextSegment(
		header, len(out.code), textFileSize)
	header = rtgBuiltinDarwinAarch64PackageMachAppendDataSegment(
		header, dataFileOff, dataFileSize, out.bssSize)
	header = rtgBuiltinDarwinAarch64PackageMachAppendSegment64(
		header,
		"__LINKEDIT",
		rtgBuiltinDarwinAarch64PackageMachImageBase+dataFileOff+dataVMSize,
		renvoAlignValue(linkeditSize, rtgBuiltinDarwinAarch64PackageMachPageSize),
		linkeditOff,
		linkeditSize,
		1,
		1,
	)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x80000022)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 48)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, bindOff)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, bindSize)
	for i := 0; i < 6; i++ {
		header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	}
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x02)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 24)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, symOff)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, symbolCount)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, strOff)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, strSize)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x0b)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 80)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 1)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 1)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, undefinedCount)
	for i := 0; i < 12; i++ {
		header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	}
	cmdStart := len(header)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x0e)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 32)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 12)
	header = rtgBuiltinDarwinAarch64PackageMachAppendStringZ(header, "/usr/lib/dyld")
	header = rtgBuiltinDarwinAarch64PackageMachAppendUntil(header, cmdStart+32)
	header = rtgBuiltinDarwinAarch64PackageMachAppendDylibCommand(
		header, rtgBuiltinDarwinAarch64PackageMachLibSystem)
	for i := 0; i < len(dylibs); i++ {
		header = rtgBuiltinDarwinAarch64PackageMachAppendDylibCommand(
			header, dylibs[i])
	}
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x1b)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 24)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x52544758)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x44415257)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x494e4152)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x4d363400)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x32)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 24)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 1)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x000b0000)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x000b0000)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x80000028)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 24)
	header = rtgBuiltinDarwinAarch64PackageMachAppend64(header, rtgBuiltinDarwinAarch64PackageMachCodeOffset)
	header = rtgBuiltinDarwinAarch64PackageMachAppend64(header, 0)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 0x1d)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, 16)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, sigOff)
	header = rtgBuiltinDarwinAarch64PackageMachAppend32(header, sigSize)
	return rtgBuiltinDarwinAarch64PackageMachAppendUntil(header, rtgBuiltinDarwinAarch64PackageMachCodeOffset)
}
func rtgBuiltinDarwinAarch64PackageMachSHA256Schedule(
	message []byte, chunk int, words []int,
) {
	for i := 0; i < 16; i++ {
		at := chunk + i*4
		word := int(message[at]) << 24
		word = word | (int(message[at+1]) << 16)
		word = word | (int(message[at+2]) << 8)
		word = word | int(message[at+3])
		words[i] = word & 0xffffffff
	}
	for i := 16; i < 64; i++ {
		x := words[i-15] & 0xffffffff
		y := words[i-2] & 0xffffffff
		s0 := ((x >> 7) | ((x << 25) & 0xffffffff))
		s0 = s0 ^ ((x >> 18) | ((x << 14) & 0xffffffff))
		s0 = s0 ^ (x >> 3)
		s1 := ((y >> 17) | ((y << 15) & 0xffffffff))
		s1 = s1 ^ ((y >> 19) | ((y << 13) & 0xffffffff))
		s1 = s1 ^ (y >> 10)
		word := words[i-16] + s0
		word = word + words[i-7] + s1
		words[i] = word & 0xffffffff
	}
}
func rtgBuiltinDarwinAarch64PackageMachSHA256Rounds(
	words []int, constants []int, values []int,
) {
	a := values[0]
	b := values[1]
	c := values[2]
	d := values[3]
	e := values[4]
	f := values[5]
	g := values[6]
	h := values[7]
	for i := 0; i < 64; i++ {
		e32 := e & 0xffffffff
		a32 := a & 0xffffffff
		s1 := (e32 >> 6) | ((e32 << 26) & 0xffffffff)
		s1 = s1 ^ ((e32 >> 11) | ((e32 << 21) & 0xffffffff))
		s1 = s1 ^ ((e32 >> 25) | ((e32 << 7) & 0xffffffff))
		choose := (e & f) ^ ((e ^ 0xffffffff) & g)
		t1 := h + s1 + choose
		t1 = (t1 + constants[i] + words[i]) & 0xffffffff
		s0 := (a32 >> 2) | ((a32 << 30) & 0xffffffff)
		s0 = s0 ^ ((a32 >> 13) | ((a32 << 19) & 0xffffffff))
		s0 = s0 ^ ((a32 >> 22) | ((a32 << 10) & 0xffffffff))
		majority := (a & b) ^ (a & c) ^ (b & c)
		t2 := (s0 + majority) & 0xffffffff
		h = g
		g = f
		f = e
		e = (d + t1) & 0xffffffff
		d = c
		c = b
		b = a
		a = (t1 + t2) & 0xffffffff
	}
	values[0] = (values[0] + a) & 0xffffffff
	values[1] = (values[1] + b) & 0xffffffff
	values[2] = (values[2] + c) & 0xffffffff
	values[3] = (values[3] + d) & 0xffffffff
	values[4] = (values[4] + e) & 0xffffffff
	values[5] = (values[5] + f) & 0xffffffff
	values[6] = (values[6] + g) & 0xffffffff
	values[7] = (values[7] + h) & 0xffffffff
}
func rtgBuiltinDarwinAarch64PackageMachSHA256(data []byte) []byte {
	messageSize := len(data) + 1 + 8
	messageSize = renvoAlignValue(messageSize, 64)
	message := make([]byte, messageSize)
	for i := 0; i < len(data); i++ {
		message[i] = data[i]
	}
	message[len(data)] = 0x80
	bits := len(data) * 8
	for i := 0; i < 8; i++ {
		message[messageSize-1-i] = byte(bits >> (i * 8))
	}
	values := []int{
		0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
		0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
	}
	constants := rtgBuiltinDarwinAarch64PackageMachSHA256Constants()
	words := make([]int, 64)
	for chunk := 0; chunk < len(message); chunk += 64 {
		rtgBuiltinDarwinAarch64PackageMachSHA256Schedule(message, chunk, words)
		rtgBuiltinDarwinAarch64PackageMachSHA256Rounds(words, constants, values)
	}
	hash := make([]byte, 0, 32)
	for i := 0; i < len(values); i++ {
		hash = append(hash, byte(values[i]>>24))
		hash = append(hash, byte(values[i]>>16))
		hash = append(hash, byte(values[i]>>8))
		hash = append(hash, byte(values[i]))
	}
	return hash
}
func rtgBuiltinDarwinAarch64PackageMachCodeSignature(
	code []byte, identifier string, executableLimit int,
) []byte {
	slots := (len(code) + 16383) / 16384
	identifierOffset := 88
	hashOffset := identifierOffset + len(identifier) + 1
	codeDirectorySize := hashOffset + slots*32
	totalSize := 20 + codeDirectorySize
	signature := make([]byte, 0, totalSize)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0xfade0cc0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, totalSize)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 1)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 20)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0xfade0c02)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(
		signature, codeDirectorySize)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0x20400)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0x2)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, hashOffset)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(
		signature, identifierOffset)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, slots)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, len(code))
	signature = append(signature, 32, 2, 0, 14)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE32(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE64(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE64(signature, 0)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE64(
		signature, executableLimit)
	signature = rtgBuiltinDarwinAarch64PackageMachAppendBE64(signature, 1)
	for i := 0; i < len(identifier); i++ {
		signature = append(signature, identifier[i])
	}
	signature = append(signature, 0)
	for slot := 0; slot < slots; slot++ {
		start := slot * 16384
		end := start + 16384
		if end > len(code) {
			end = len(code)
		}
		hash := rtgBuiltinDarwinAarch64PackageMachSHA256(code[start:end])
		signature = append(signature, hash...)
	}
	return signature
}
func rtgBuiltinDarwinAarch64PackageDarwinEntryStart(out *renvoAsm, stateOffset int) bool {
	// dyld supplies argc, argv, and envp in x0, x1, and x2. Preserve them
	// before arena and global initialization reuse those registers.
	at := len(out.code)
	renvoAsmEmit32(out, 0x90000009)
	renvoAsmEmit32(out, 0xd503201f)
	renvoAsmEmit32(out, 0xd503201f)
	renvoAsmEmit32(out, 0xd503201f)
	renvoAsmAddAbsReloc(out, at, stateOffset, 1)
	renvoAsmEmit32(out, 0xf9000120)
	renvoAsmEmit32(out, 0xf9000521)
	renvoAsmEmit32(out, 0xf9000922)
	return true
}

func rtgBuiltinDarwinAarch64PackageDarwinExit(out *renvoAsm, status int) {
	renvoAarch64AsmMovRegReg(out,0,status)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_exit")
}

func rtgBuiltinDarwinAarch64PackageMachImage(out *renvoAsm) []byte {
	imports:=rtgBuiltinDarwinAarch64PackageMachPrepareImports(out)
	dataFileOff:=renvoAlignValue(rtgBuiltinDarwinAarch64PackageMachCodeOffset+len(out.code),rtgBuiltinDarwinAarch64PackageMachPageSize)
	bind:=rtgBuiltinDarwinAarch64PackageMachBuildBindData(out,imports.got)
	symtab:=rtgBuiltinDarwinAarch64PackageMachBuildSymbolTable(out)
	strtab:=rtgBuiltinDarwinAarch64PackageMachBuildStringTable(out)
	undefinedCount:=out.DynamicImportCount()
	textFileSize:=dataFileOff
	dataFileSize:=len(out.data)
	dataVMSize:=renvoAlignValue(dataFileSize+out.bssSize,rtgBuiltinDarwinAarch64PackageMachPageSize)
	linkeditOff:=dataFileOff+dataFileSize
	bindOff:=linkeditOff
	symOff:=renvoAlignValue(bindOff+len(bind),8)
	strOff:=symOff+len(symtab)
	sigOff:=renvoAlignValue(strOff+len(strtab),16)
	sigSize:=rtgBuiltinDarwinAarch64PackageMachCodeSignatureSize(sigOff,"renvo")
	linkeditSize:=sigOff+sigSize-linkeditOff
	image:=rtgBuiltinDarwinAarch64PackageMachHeader(out,textFileSize,dataFileOff,dataFileSize,dataVMSize,linkeditOff,linkeditSize,bindOff,len(bind),symOff,1+undefinedCount,strOff,len(strtab),undefinedCount,sigOff,sigSize,)
	image=append(image,out.code...)
	image=rtgBuiltinDarwinAarch64PackageMachAppendUntil(image,dataFileOff)
	image=append(image,out.data...)
	image=rtgBuiltinDarwinAarch64PackageMachAppendUntil(image,bindOff)
	image=append(image,bind...)
	image=rtgBuiltinDarwinAarch64PackageMachAppendUntil(image,symOff)
	image=append(image,symtab...)
	image=append(image,strtab...)
	image=rtgBuiltinDarwinAarch64PackageMachAppendUntil(image,sigOff)
	signature:=rtgBuiltinDarwinAarch64PackageMachCodeSignature(image,"renvo",textFileSize)
	return append(image,signature...)
}

func rtgBuiltinDarwinAarch64PackageDarwinCallImport(out *renvoAsm, name string) {
	index:=out.DynamicImport(rtgBuiltinDarwinAarch64PackageMachLibSystem,name)
	renvoAarch64AsmCallLabel(out,out.DynamicImportLabel(index))
}

func rtgBuiltinDarwinAarch64PackageMachAppend16(out []byte, value int) []byte {
	return append(out,byte(value),byte(value>>8))
}

func rtgBuiltinDarwinAarch64PackageMachAppend32(out []byte, value int) []byte {
	return append(out,byte(value),byte(value>>8),byte(value>>16),byte(value>>24))
}

func rtgBuiltinDarwinAarch64PackageMachAppend64(out []byte, value int) []byte {
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,value)
	return rtgBuiltinDarwinAarch64PackageMachAppend32(out,value>>32)
}

func rtgBuiltinDarwinAarch64PackageMachAppendBE32(out []byte, value int) []byte {
	out=append(out,byte(value>>24))
	out=append(out,byte(value>>16))
	out=append(out,byte(value>>8))
	return append(out,byte(value))
}

func rtgBuiltinDarwinAarch64PackageMachAppendBE64(out []byte, value int) []byte {
	out=rtgBuiltinDarwinAarch64PackageMachAppendBE32(out,value>>32)
	return rtgBuiltinDarwinAarch64PackageMachAppendBE32(out,value)
}

func rtgBuiltinDarwinAarch64PackageMachAppendDataSegment(out []byte, dataFileOff int, dataFileSize int, bssSize int) []byte {
	vmSize:=renvoAlignValue(dataFileSize+bssSize,rtgBuiltinDarwinAarch64PackageMachPageSize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0x19)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,232)
	out=rtgBuiltinDarwinAarch64PackageMachAppendName16(out,"__DATA")
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,rtgBuiltinDarwinAarch64PackageMachImageBase+dataFileOff)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,vmSize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,dataFileOff)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,dataFileSize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,3)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,3)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,2)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	out=rtgBuiltinDarwinAarch64PackageMachAppendSection64(out,"__data","__DATA",rtgBuiltinDarwinAarch64PackageMachImageBase+dataFileOff,dataFileSize,dataFileOff,3,0,)
	return rtgBuiltinDarwinAarch64PackageMachAppendSection64(out,"__bss","__DATA",rtgBuiltinDarwinAarch64PackageMachImageBase+dataFileOff+dataFileSize,bssSize,0,3,1,)
}

func rtgBuiltinDarwinAarch64PackageMachAppendDylibCommand(out []byte, path string) []byte {
	start:=len(out)
	size:=rtgBuiltinDarwinAarch64PackageMachDylibCommandSize(path)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0x0c)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,size)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,24)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,2)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0x00010000)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0x00010000)
	out=rtgBuiltinDarwinAarch64PackageMachAppendStringZ(out,path)
	return rtgBuiltinDarwinAarch64PackageMachAppendUntil(out,start+size)
}

func rtgBuiltinDarwinAarch64PackageMachAppendSection64(out []byte, section string, segment string, addr int, size int, offset int, align int, flags int) []byte {
	out=rtgBuiltinDarwinAarch64PackageMachAppendName16(out,section)
	out=rtgBuiltinDarwinAarch64PackageMachAppendName16(out,segment)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,addr)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,size)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,offset)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,align)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,flags)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	return rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
}

func rtgBuiltinDarwinAarch64PackageMachAppendSegment64(out []byte, name string, vmaddr int, vmsize int, fileoff int, filesize int, maxprot int, initprot int) []byte {
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0x19)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,72)
	out=rtgBuiltinDarwinAarch64PackageMachAppendName16(out,name)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,vmaddr)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,vmsize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,fileoff)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,filesize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,maxprot)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,initprot)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	return rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
}

func rtgBuiltinDarwinAarch64PackageMachAppendTextSegment(out []byte, codeSize int, fileSize int) []byte {
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0x19)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,152)
	out=rtgBuiltinDarwinAarch64PackageMachAppendName16(out,"__TEXT")
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,rtgBuiltinDarwinAarch64PackageMachImageBase)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,fileSize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,0)
	out=rtgBuiltinDarwinAarch64PackageMachAppend64(out,fileSize)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,5)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,5)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,1)
	out=rtgBuiltinDarwinAarch64PackageMachAppend32(out,0)
	return rtgBuiltinDarwinAarch64PackageMachAppendSection64(out,"__text","__TEXT",rtgBuiltinDarwinAarch64PackageMachImageBase+rtgBuiltinDarwinAarch64PackageMachCodeOffset,codeSize,rtgBuiltinDarwinAarch64PackageMachCodeOffset,2,0x80000400,)
}

func rtgBuiltinDarwinAarch64PackageMachCodeSignatureSize(codeLimit int, identifier string) int {
	slots:=(codeLimit+16383)/16384
	codeDirectorySize:=88+len(identifier)+1+slots*32
	return 20+codeDirectorySize
}

func rtgBuiltinDarwinAarch64PackageMachDylibCommandSize(path string) int {
	return renvoAlignValue(24+len(path)+1,8)
}

func rtgBuiltinDarwinAarch64PackageMachPatchADRP(out *renvoAsm, at int, pc int, target int) {
	delta:=(target>>12)-(pc>>12)
	imm:=delta&0x1fffff
	insn:=0x90000010
	insn=insn|((imm&3)<<29)
	insn=insn|(((imm>>2)&0x7ffff)<<5)
	renvoPut32At(out.code, at,insn)
}

func rtgBuiltinDarwinAarch64PackageMachSHA256Constants() []int {
	return []int{0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2,}
}

func rtgBuiltinDarwinAarch64PackageDarwinRead(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegReg(out,2,1)
	renvoAarch64AsmMovRegReg(out,1,4)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_read")
}

func rtgBuiltinDarwinAarch64PackageDarwinWrite(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegReg(out,2,1)
	renvoAarch64AsmMovRegReg(out,1,4)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_write")
}

func rtgBuiltinDarwinAarch64PackageDarwinReadAt(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegReg(out,3,2)
	renvoAarch64AsmMovRegReg(out,2,1)
	renvoAarch64AsmMovRegReg(out,1,4)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_pread")
}

func rtgBuiltinDarwinAarch64PackageDarwinWriteAt(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegReg(out,3,2)
	renvoAarch64AsmMovRegReg(out,2,1)
	renvoAarch64AsmMovRegReg(out,1,4)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_pwrite")
}

func rtgBuiltinDarwinAarch64PackageDarwinOpen(out *renvoAsm) {
	renvoAarch64AsmPushReg(out,1)
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegReg(out,1,4)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_open")
	renvoAarch64AsmAddRegImm(out,31,31,16)
}

func rtgBuiltinDarwinAarch64PackageDarwinClose(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,0,3)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_close")
}

func rtgBuiltinDarwinAarch64PackageDarwinChmod(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegReg(out,1,4)
	rtgBuiltinDarwinAarch64PackageDarwinCallImport(out,"_fchmod")
}

func rtgBuiltinDarwinAarch64PackageEmitCStringRecord(out *renvoAsm, pointer int, table int, length int, scratch int) {
	scan:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmStoreRegMem(out,pointer,table,0,8)
	renvoAarch64AsmMovRegImm(out,length,0)
	renvoAsmMarkLabel(out, scan)
	renvoAarch64AsmAddRegReg(out,scratch,pointer,length)
	renvoAarch64AsmLoadRegMem(out,scratch,scratch,0,1)
	renvoAarch64AsmCmpRegImm(out,scratch,0)
	renvoDarwinAarch64BCondEQ(out,done)
	renvoAarch64AsmAddRegImm(out,length,length,1)
	renvoAarch64AsmJmpLabel(out, scan)
	renvoAsmMarkLabel(out, done)
	renvoAarch64AsmStoreRegMem(out,length,table,8,8)
}

func rtgBuiltinDarwinAarch64PackageEmitBoundedCountedCStringTable(out *renvoAsm, source int, count int, tableOffset int, table int, index int, pointer int, length int, scratch int) {
	loop:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmMovRegAbs(out,table,tableOffset,1)
	renvoAarch64AsmMovRegImm(out,index,0)
	renvoAsmMarkLabel(out, loop)
	renvoAarch64AsmCmpRegImm(out,index,2048)
	renvoDarwinAarch64BCondSGE(out,done)
	renvoAarch64AsmCmpRegReg(out,index,count)
	renvoDarwinAarch64BCondEQ(out,done)
	renvoAarch64AsmAddRegRegShift(out,pointer,source,index,3)
	renvoAarch64AsmLoadRegMem(out,pointer,pointer,0,8)
	rtgBuiltinDarwinAarch64PackageEmitCStringRecord(out,pointer,table,length,scratch)
	renvoAarch64AsmAddRegImm(out,table,table,16)
	renvoAarch64AsmAddRegImm(out,index,index,1)
	renvoAarch64AsmJmpLabel(out, loop)
	renvoAsmMarkLabel(out, done)
}

func rtgBuiltinDarwinAarch64PackageEmitBoundedTerminatedCStringTable(out *renvoAsm, source int, tableOffset int, table int, index int, pointer int, length int, scratch int) {
	loop:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmMovRegAbs(out,table,tableOffset,1)
	renvoAarch64AsmMovRegImm(out,index,0)
	renvoAsmMarkLabel(out, loop)
	renvoAarch64AsmCmpRegImm(out,index,2048)
	renvoDarwinAarch64BCondSGE(out,done)
	renvoAarch64AsmLoadRegMem(out,pointer,source,0,8)
	renvoAarch64AsmCmpRegImm(out,pointer,0)
	renvoDarwinAarch64BCondEQ(out,done)
	rtgBuiltinDarwinAarch64PackageEmitCStringRecord(out,pointer,table,length,scratch)
	renvoAarch64AsmAddRegImm(out,table,table,16)
	renvoAarch64AsmAddRegImm(out,source,source,8)
	renvoAarch64AsmAddRegImm(out,index,index,1)
	renvoAarch64AsmJmpLabel(out, loop)
	renvoAsmMarkLabel(out, done)
}

func rtgBuiltinDarwinAarch64PackageBindEntryCollections(out *renvoAsm, argsOffset int, argsLength int, environmentOffset int, environmentLength int) {
	renvoAarch64AsmMovRegAbs(out,3,argsOffset,1)
	renvoAarch64AsmMovRegReg(out,4,argsLength)
	renvoAarch64AsmMovRegReg(out,1,argsLength)
	renvoAarch64AsmMovRegAbs(out,2,environmentOffset,1)
	renvoAarch64AsmMovRegReg(out,5,environmentLength)
	renvoAarch64AsmMovRegReg(out,6,environmentLength)
}

func rtgBuiltinDarwinAarch64PackageDarwinEntry(out *renvoAsm, argsOffset int, environmentOffset int, stateOffset int) {
	renvoAarch64AsmMovRegAbs(out,9,stateOffset,1)
	renvoAarch64AsmLoadRegMem(out,13,9,0,8)
	renvoAarch64AsmLoadRegMem(out,14,9,8,8)
	renvoAarch64AsmLoadRegMem(out,15,9,16,8)
	rtgBuiltinDarwinAarch64PackageEmitBoundedCountedCStringTable(out,14,13,argsOffset,10,11,12,0,9,)
	renvoAarch64AsmMovRegReg(out,13,11)
	rtgBuiltinDarwinAarch64PackageEmitBoundedTerminatedCStringTable(out,15,environmentOffset,10,11,12,0,9,)
	rtgBuiltinDarwinAarch64PackageBindEntryCollections(out,argsOffset,13,environmentOffset,11,)
}


func renvoDarwinAarch64BCondEQ(out *renvoAsm, label int) { renvoAarch64AsmBCondLabel(out, label, 0) }
func renvoDarwinAarch64BCondSGE(out *renvoAsm, label int) { renvoAarch64AsmBCondLabel(out, label, 10) }

const renvoDarwinArm64CodeOffset = 4096
const renvoDarwinArm64EntryStateBytes = 24

func renvoDarwinSHA256(data []byte) []byte {
	return rtgBuiltinDarwinAarch64PackageMachSHA256(data)
}

func renvoDarwinArm64DefinitionRead(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinRead(a)
}

func renvoDarwinArm64DefinitionWrite(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinWrite(a)
}

func renvoDarwinArm64DefinitionReadAt(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinReadAt(a)
}

func renvoDarwinArm64DefinitionWriteAt(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinWriteAt(a)
}

func renvoDarwinArm64DefinitionOpen(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinOpen(a)
}

func renvoDarwinArm64DefinitionClose(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinClose(a)
}

func renvoDarwinArm64DefinitionChmod(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinChmod(a)
}

func renvoDarwinArm64DefinitionExit(a *renvoAsm) {
	rtgBuiltinDarwinAarch64PackageDarwinExit(a, 0)
}

func renvoDarwinArm64DefinitionEntryStart(a *renvoAsm, stateOffset int) bool {
	return rtgBuiltinDarwinAarch64PackageDarwinEntryStart(a, stateOffset)
}

func renvoDarwinArm64DefinitionStaticCall(a *renvoAsm, importID int, wordCount int) {
	rtgBuiltinDarwinAarch64PackageMachStaticCall(a, importID, wordCount)
}

func renvoDarwinArm64DefinitionImage(a *renvoAsm) []byte {
	return rtgBuiltinDarwinAarch64PackageMachImage(a)
}

func renvoDarwinArm64Image(a *renvoAsm) []byte {
	data := renvoDarwinArm64DefinitionImage(a)
	if renvoFixedTarget == 0 && a.c.emitImage {
		return renvoAppendReplLinkTable(data, a)
	}
	return data
}

const renvoDarwinArm64ArgsBSSSize = 32768
const renvoDarwinArm64ArgsBSSAlignment = 16
const renvoDarwinArm64EnvironmentBSSSize = 32768
const renvoDarwinArm64EnvironmentBSSAlignment = 16

func renvoDarwinArm64DefinitionEntry(a *renvoAsm, argsOff int, environmentOff int, stateOffset int) {
	rtgBuiltinDarwinAarch64PackageDarwinEntry(a, argsOff, environmentOff, stateOffset)
}


func renvoEmitProgramEntryArgsDarwinArm64(g *renvoLinearGen, appIndex int) bool {
	app := &g.meta.funcs[appIndex]
	if app.resultType != 0 && !renvoTypeIsInt(g.meta, app.resultType) { return false }
	if app.paramCount == 0 { return true }
	if app.paramCount > 2 || !renvoTypeIsStringSlice(g.meta, g.meta.params[app.firstParam].typ) { return false }
	if app.paramCount == 2 && !renvoTypeIsStringSlice(g.meta, g.meta.params[app.firstParam+1].typ) { return false }
	argsOff := renvoAlignValue(g.asm.bssSize, renvoDarwinArm64ArgsBSSAlignment)
	g.asm.bssSize = argsOff + renvoDarwinArm64ArgsBSSSize
	envOff := renvoAlignValue(g.asm.bssSize, renvoDarwinArm64EnvironmentBSSAlignment)
	g.asm.bssSize = envOff + renvoDarwinArm64EnvironmentBSSSize
	renvoDarwinArm64DefinitionEntry(&g.asm, argsOff, envOff, g.darwinEntryOff)
	return true
}
