// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: algorithms/aarch64
// unit: native ef82d796223f9f2694b7a111107bb6e0780287c95bb2269deae01dae3fb65eb1
package main


func renvoAarch64AsmAlign(a *renvoAsm) {
	for len(a.code)%4 != 0 {
		renvoAsmEmit8(a, 0)
	}
}
func renvoAarch64AsmMovRegReg(a *renvoAsm, dst int, src int) {
	if dst == src {
		return
	}
	renvoAarch64AsmEmit(a, 0xaa0003e0|(src<<16)|dst)
}
func renvoAarch64AsmMovRegImm(a *renvoAsm, reg int, imm int) {
	if imm < 0 {
		inv := -imm - 1
		part := inv & 65535
		renvoAarch64AsmEmit(a, 0x92800000|(part<<5)|reg)
		for i := 1; i < 4; i++ {
			targetPart := (imm >> (i * 16)) & 65535
			if targetPart != 65535 {
				renvoAarch64AsmEmit(a, 0xf2800000|(i<<21)|(targetPart<<5)|reg)
			}
		}
		return
	}
	part := imm & 65535
	renvoAarch64AsmEmit(a, 0xd2800000|(part<<5)|reg)
	for i := 1; i < 4; i++ {
		part = (imm >> (i * 16)) & 65535
		if part != 0 {
			renvoAarch64AsmEmit(a, 0xf2800000|(i<<21)|(part<<5)|reg)
		}
	}
}
func renvoAarch64AsmPatchMovRegImmAt(a *renvoAsm, at int, reg int, imm int) {
	part := imm & 65535
	renvoPut32At(a.code, at, 0xd2800000|(part<<5)|reg)
	for i := 1; i < 4; i++ {
		part = (imm >> (i * 16)) & 65535
		renvoPut32At(a.code, at+i*4, 0xf2800000|(i<<21)|(part<<5)|reg)
	}
}
func renvoAarch64AsmAddRegImm(a *renvoAsm, dst int, src int, imm int) {
	if imm == 0 {
		renvoAarch64AsmMovRegReg(a, dst, src)
		return
	}
	op := 0x91000000
	if imm < 0 {
		op = 0xd1000000
		imm = -imm
	}
	cur := src
	for imm > 0 {
		shift := 0
		chunk := imm
		if chunk > 4095 {
			chunk = imm / 4096
			if chunk > 4095 {
				chunk = 4095
			}
			shift = 1
			imm = imm - chunk*4096
		} else {
			imm = 0
		}
		renvoAarch64AsmEmit(a, op|(shift<<22)|(chunk<<10)|(cur<<5)|dst)
		cur = dst
	}
}
func renvoAarch64AsmAddr(a *renvoAsm, base int, disp int) int {
	if disp == 0 {
		return base
	}
	renvoAarch64AsmAddRegImm(a, 12, base, disp)
	return 12
}
func renvoAarch64AsmLoadRegMem(a *renvoAsm, dst int, base int, disp int, size int) {
	if disp != 0 && disp >= -256 && disp <= 255 {
		imm := (disp & 511) << 12
		if size == 1 {
			renvoAarch64AsmEmit(a, 0x38400000|imm|(base<<5)|dst)
			return
		}
		if size == 2 {
			renvoAarch64AsmEmit(a, 0x78400000|imm|(base<<5)|dst)
			return
		}
		if size == 4 {
			renvoAarch64AsmEmit(a, 0xb8400000|imm|(base<<5)|dst)
			return
		}
		renvoAarch64AsmEmit(a, 0xf8400000|imm|(base<<5)|dst)
		return
	}
	addr := renvoAarch64AsmAddr(a, base, disp)
	if size == 1 {
		renvoAarch64AsmEmit(a, 0x39400000|(addr<<5)|dst)
		return
	}
	if size == 2 {
		renvoAarch64AsmEmit(a, 0x79800000|(addr<<5)|dst)
		return
	}
	if size == 4 {
		renvoAarch64AsmEmit(a, 0xb9800000|(addr<<5)|dst)
		return
	}
	renvoAarch64AsmEmit(a, 0xf9400000|(addr<<5)|dst)
}
func renvoAarch64AsmStoreRegMem(a *renvoAsm, src int, base int, disp int, size int) {
	if disp != 0 && disp >= -256 && disp <= 255 {
		imm := (disp & 511) << 12
		if size == 1 {
			renvoAarch64AsmEmit(a, 0x38000000|imm|(base<<5)|src)
			return
		}
		if size == 2 {
			renvoAarch64AsmEmit(a, 0x78000000|imm|(base<<5)|src)
			return
		}
		if size == 4 {
			renvoAarch64AsmEmit(a, 0xb8000000|imm|(base<<5)|src)
			return
		}
		renvoAarch64AsmEmit(a, 0xf8000000|imm|(base<<5)|src)
		return
	}
	addr := renvoAarch64AsmAddr(a, base, disp)
	if size == 1 {
		renvoAarch64AsmEmit(a, 0x39000000|(addr<<5)|src)
		return
	}
	if size == 2 {
		renvoAarch64AsmEmit(a, 0x79000000|(addr<<5)|src)
		return
	}
	if size == 4 {
		renvoAarch64AsmEmit(a, 0xb9000000|(addr<<5)|src)
		return
	}
	renvoAarch64AsmEmit(a, 0xf9000000|(addr<<5)|src)
}
func renvoAarch64AsmStackMem(a *renvoAsm, offset int, base int, disp8 int, disp32 int) {
	if base == 0x8948 && disp8 == 0x45 {
		renvoAarch64AsmStoreRegStack(a, 0, offset)
		return
	}
	if base == 0x8948 && disp8 == 0x55 {
		renvoAarch64AsmStoreRegStack(a, 1, offset)
		return
	}
	if base == 0x8948 && disp8 == 0x4d {
		renvoAarch64AsmStoreRegStack(a, 2, offset)
		return
	}
	if base == 0x8b48 && disp8 == 0x45 {
		renvoAarch64AsmLoadRegStack(a, 0, offset)
		return
	}
	if base == 0x8b48 && disp8 == 0x55 {
		renvoAarch64AsmLoadRegStack(a, 1, offset)
		return
	}
	if base == 0x8b48 && disp8 == 0x4d {
		renvoAarch64AsmLoadRegStack(a, 2, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x45 {
		renvoAarch64AsmLeaRegStack(a, 0, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x55 {
		renvoAarch64AsmLeaRegStack(a, 1, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x7d {
		renvoAarch64AsmLeaRegStack(a, 3, offset)
		return
	}
	if base == 0x8d48 && disp8 == 0x75 {
		renvoAarch64AsmLeaRegStack(a, 4, offset)
		return
	}
}
func renvoAarch64AsmMemDisp(a *renvoAsm, disp int, op int, disp8 int, disp32 int) {
	if op == 0x8b48 && disp8 == 0x4a {
		renvoAarch64AsmLoadRegMem(a, 2, 1, disp, 8)
		return
	}
	if op == 0x8b48 && disp8 == 0x52 {
		renvoAarch64AsmLoadRegMem(a, 1, 1, disp, 8)
		return
	}
}
func renvoAarch64AsmLoadRaxIndexRcxSize(a *renvoAsm, size int) {
	shift := 3
	if size == 1 {
		shift = 0
	}
	if size == 2 {
		shift = 1
	}
	if size == 4 {
		shift = 2
	}
	renvoAarch64AsmAddRegRegShift(a, 12, 0, 2, shift)
	renvoAarch64AsmLoadRegMem(a, 0, 12, 0, size)
}
func renvoAarch64AsmNormalizeRaxForKind(a *renvoAsm, kind int) {
	if kind == 3 {
		renvoAarch64AsmEmit(a, 0x92401c00)
		return
	}
	if kind == 7 {
		renvoAarch64AsmEmit(a, 0x93401c00)
		return
	}
	if kind == 8 {
		renvoAarch64AsmEmit(a, 0x93403c00)
		return
	}
	if kind == 16 {
		renvoAarch64AsmEmit(a, 0x92403c00)
		return
	}
	if kind == 9 {
		renvoAarch64AsmEmit(a, 0x93407c00)
		return
	}
	if kind == 17 {
		renvoAarch64AsmEmit(a, 0x92407c00)
	}
}
func renvoAarch64AsmCmpRegImm(a *renvoAsm, reg int, imm int) {
	if imm >= 0 && imm <= 4095 {
		renvoAarch64AsmEmit(a, 0xf100001f|(imm<<10)|(reg<<5))
		return
	}
	renvoAarch64AsmMovRegImm(a, 9, imm)
	renvoAarch64AsmCmpRegReg(a, reg, 9)
}
func renvoAarch64AsmDivLeftRcxRightRax(a *renvoAsm, mod bool) {
	renvoAarch64AsmMovRegReg(a, 9, 0)
	renvoAarch64AsmEmit(a, 0x9ac00c40)
	if mod {
		renvoAarch64AsmEmit(a, 0x9b098800)
	}
}
func renvoAarch64CondFromSetcc(setcc int) int {
	if setcc == 0x94 {
		return 0
	}
	if setcc == 0x95 {
		return 1
	}
	if setcc == 0x92 {
		return 3
	}
	if setcc == 0x93 {
		return 2
	}
	if setcc == 0x96 {
		return 9
	}
	if setcc == 0x97 {
		return 8
	}
	if setcc == 0x9c {
		return 11
	}
	if setcc == 0x9e {
		return 13
	}
	if setcc == 0x9f {
		return 12
	}
	return 10
}
func renvoAarch64AsmStoreRaxMemRdxRcxSize(a *renvoAsm, size int) {
	shift := 3
	if size == 1 {
		shift = 0
	}
	if size == 2 {
		shift = 1
	}
	if size == 4 {
		shift = 2
	}
	renvoAarch64AsmAddRegRegShift(a, 12, 1, 2, shift)
	renvoAarch64AsmStoreRegMem(a, 0, 12, 0, size)
}

// Generated from bounded sequence renvoAarch64AsmAddRaxRcx.
func renvoAarch64AsmAddRaxRcx(a *renvoAsm) {
	renvoAarch64AsmAddRegReg(a,0,0,2)
}

// Generated from bounded sequence renvoAarch64AsmAddRdxImm.
func renvoAarch64AsmAddRdxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmAddRegImm(a,1,1,imm)
}

// Generated from bounded sequence renvoAarch64AsmAddRdxRcx.
func renvoAarch64AsmAddRdxRcx(a *renvoAsm) {
	renvoAarch64AsmAddRegReg(a,1,1,2)
}

// Generated from bounded sequence renvoAarch64AsmAddRegReg.
func renvoAarch64AsmAddRegReg(a *renvoAsm, dst int, left int, right int) {
	renvoAarch64AsmEmit(a,0x8b000000|(right<<16)|(left<<5)|dst)
}

// Generated from bounded sequence renvoAarch64AsmAddRegRegShift.
func renvoAarch64AsmAddRegRegShift(a *renvoAsm, dst int, left int, right int, shift int) {
	renvoAarch64AsmEmit(a,0x8b000000|(right<<16)|(shift<<10)|(left<<5)|dst)
}

// Generated from bounded sequence renvoAarch64AsmBoolNotRax.
func renvoAarch64AsmBoolNotRax(a *renvoAsm) {
	renvoAarch64AsmCmpRaxImm8(a,0)
	renvoAarch64AsmCsetRax(a,0)
}

// Generated from bounded sequence renvoAarch64AsmCmpRaxImm8.
func renvoAarch64AsmCmpRaxImm8(a *renvoAsm, imm int) {
	renvoAarch64AsmCmpRegImm(a,0,imm)
}

// Generated from bounded sequence renvoAarch64AsmCmpRegReg.
func renvoAarch64AsmCmpRegReg(a *renvoAsm, left int, right int) {
	renvoAarch64AsmEmit(a,0xeb00001f|(right<<16)|(left<<5))
}

// Generated from bounded sequence renvoAarch64AsmCsetRax.
func renvoAarch64AsmCsetRax(a *renvoAsm, cond int) {
	renvoAarch64AsmEmit(a,0x9a9f07e0|((cond^1)<<12))
}

// Generated from bounded sequence renvoAarch64AsmDecMemRdx.
func renvoAarch64AsmDecMemRdx(a *renvoAsm) {
	renvoAarch64AsmLoadRegMem(a,9,1,0,8)
	renvoAarch64AsmAddRegImm(a,9,9,-1)
	renvoAarch64AsmStoreRegMem(a,9,1,0,8)
}

// Generated from bounded sequence renvoAarch64AsmEmit.
func renvoAarch64AsmEmit(a *renvoAsm, insn int) {
	renvoAsmEmit32(a,insn)
}

// Generated from bounded sequence renvoAarch64AsmImulRcxImm.
func renvoAarch64AsmImulRcxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmMovRegImm(a,9,imm)
	renvoAarch64AsmEmit(a,0x9b007c00|(9<<16)|(2<<5)|2)
}

// Generated from bounded sequence renvoAarch64AsmIncMemRdx.
func renvoAarch64AsmIncMemRdx(a *renvoAsm) {
	renvoAarch64AsmLoadRegMem(a,9,1,0,8)
	renvoAarch64AsmAddRegImm(a,9,9,1)
	renvoAarch64AsmStoreRegMem(a,9,1,0,8)
}

// Generated from bounded sequence renvoAarch64AsmIncRax.
func renvoAarch64AsmIncRax(a *renvoAsm) {
	renvoAarch64AsmAddRegImm(a,0,0,1)
}

// Generated from bounded sequence renvoAarch64AsmIncRcx.
func renvoAarch64AsmIncRcx(a *renvoAsm) {
	renvoAarch64AsmAddRegImm(a,2,2,1)
}

// Generated from bounded sequence renvoAarch64AsmJnzLabel.
func renvoAarch64AsmJnzLabel(a *renvoAsm, label int) {
	renvoAarch64AsmBCondLabel(a,label,1)
}

// Generated from bounded sequence renvoAarch64AsmJzLabel.
func renvoAarch64AsmJzLabel(a *renvoAsm, label int) {
	renvoAarch64AsmBCondLabel(a,label,0)
}

// Generated from bounded sequence renvoAarch64AsmLeaRegStack.
func renvoAarch64AsmLeaRegStack(a *renvoAsm, dst int, offset int) {
	renvoAarch64AsmAddRegImm(a,dst,29,-offset)
}

// Generated from bounded sequence renvoAarch64AsmLeave.
func renvoAarch64AsmLeave(a *renvoAsm) {
	renvoAarch64AsmEmit(a,0x910003bf)
	renvoAarch64AsmEmit(a,0xa8c17bfd)
}

// Generated from bounded sequence renvoAarch64AsmLoadByteRaxIndexRcx.
func renvoAarch64AsmLoadByteRaxIndexRcx(a *renvoAsm) {
	renvoAarch64AsmAddRegRegShift(a,12,0,2,0)
	renvoAarch64AsmLoadRegMem(a,0,12,0,1)
}

// Generated from bounded sequence renvoAarch64AsmLoadQwordRaxIndexRcx8.
func renvoAarch64AsmLoadQwordRaxIndexRcx8(a *renvoAsm) {
	renvoAarch64AsmAddRegRegShift(a,12,0,2,3)
	renvoAarch64AsmLoadRegMem(a,0,12,0,8)
}

// Generated from bounded sequence renvoAarch64AsmLoadQwordRaxIndexRcxDisp.
func renvoAarch64AsmLoadQwordRaxIndexRcxDisp(a *renvoAsm, disp int) {
	renvoAarch64AsmAddRegReg(a,12,0,2)
	renvoAarch64AsmLoadRegMem(a,0,12,disp,8)
}

// Generated from bounded sequence renvoAarch64AsmLoadRaxBss.
func renvoAarch64AsmLoadRaxBss(a *renvoAsm, bssOff int) {
	renvoAarch64AsmMovRegAbs(a,12,bssOff,1)
	renvoAarch64AsmLoadRegMem(a,0,12,0,8)
}

// Generated from bounded sequence renvoAarch64AsmLoadRaxMemRdxDisp.
func renvoAarch64AsmLoadRaxMemRdxDisp(a *renvoAsm, disp int) {
	renvoAarch64AsmLoadRegMem(a,0,1,disp,8)
}

// Generated from bounded sequence renvoAarch64AsmLoadRaxMemRdxDispSize.
func renvoAarch64AsmLoadRaxMemRdxDispSize(a *renvoAsm, disp int, size int) {
	renvoAarch64AsmLoadRegMem(a,0,1,disp,size)
}

// Generated from bounded sequence renvoAarch64AsmLoadRegStack.
func renvoAarch64AsmLoadRegStack(a *renvoAsm, dst int, offset int) {
	renvoAarch64AsmLoadRegMem(a,dst,29,-offset,8)
}

// Generated from bounded sequence renvoAarch64AsmMovR10BssAddr.
func renvoAarch64AsmMovR10BssAddr(a *renvoAsm, bssOff int) {
	renvoAarch64AsmMovRegAbs(a,7,bssOff,1)
}

// Generated from bounded sequence renvoAarch64AsmMovR8Rax.
func renvoAarch64AsmMovR8Rax(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,5,0)
}

// Generated from bounded sequence renvoAarch64AsmMovR9Rax.
func renvoAarch64AsmMovR9Rax(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,6,0)
}

// Generated from bounded sequence renvoAarch64AsmMovRaxBssAddr.
func renvoAarch64AsmMovRaxBssAddr(a *renvoAsm, bssOff int) {
	renvoAarch64AsmMovRegAbs(a,0,bssOff,1)
}

// Generated from bounded sequence renvoAarch64AsmMovRaxDataAddr.
func renvoAarch64AsmMovRaxDataAddr(a *renvoAsm, dataOff int) {
	renvoAarch64AsmMovRegAbs(a,0,dataOff,0)
}

// Generated from bounded sequence renvoAarch64AsmMovRaxImm.
func renvoAarch64AsmMovRaxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmMovRegImm(a,0,imm)
}

// Generated from bounded sequence renvoAarch64AsmMovRaxImm64.
func renvoAarch64AsmMovRaxImm64(a *renvoAsm, imm int) {
	renvoAarch64AsmMovRaxImm(a,imm)
}

// Generated from bounded sequence renvoAarch64AsmMovRaxRdx.
func renvoAarch64AsmMovRaxRdx(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,0,1)
}

// Generated from bounded sequence renvoAarch64AsmMovRcxRax.
func renvoAarch64AsmMovRcxRax(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,2,0)
}

// Generated from bounded sequence renvoAarch64AsmMovRcxRdx.
func renvoAarch64AsmMovRcxRdx(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,2,1)
}

// Generated from bounded sequence renvoAarch64AsmMovRdiRax.
func renvoAarch64AsmMovRdiRax(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,3,0)
}

// Generated from bounded sequence renvoAarch64AsmMovRdxImm.
func renvoAarch64AsmMovRdxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmMovRegImm(a,1,imm)
}

// Generated from bounded sequence renvoAarch64AsmMovRdxRax.
func renvoAarch64AsmMovRdxRax(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,1,0)
}

// Generated from bounded sequence renvoAarch64AsmMovRsiRax.
func renvoAarch64AsmMovRsiRax(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,4,0)
}

// Generated from bounded sequence renvoAarch64AsmMulRegReg.
func renvoAarch64AsmMulRegReg(a *renvoAsm, dst int, left int, right int) {
	renvoAarch64AsmEmit(a,0x9b007c00|(right<<16)|(left<<5)|dst)
}

// Generated from bounded sequence renvoAarch64AsmNegRax.
func renvoAarch64AsmNegRax(a *renvoAsm) {
	renvoAarch64AsmSubRegReg(a,0,31,0)
}

// Generated from bounded sequence renvoAarch64AsmPopRax.
func renvoAarch64AsmPopRax(a *renvoAsm) {
	renvoAarch64AsmPopReg(a,0)
}

// Generated from bounded sequence renvoAarch64AsmPopRcx.
func renvoAarch64AsmPopRcx(a *renvoAsm) {
	renvoAarch64AsmPopReg(a,2)
}

// Generated from bounded sequence renvoAarch64AsmPopRdi.
func renvoAarch64AsmPopRdi(a *renvoAsm) {
	renvoAarch64AsmPopReg(a,3)
}

// Generated from bounded sequence renvoAarch64AsmPopRdx.
func renvoAarch64AsmPopRdx(a *renvoAsm) {
	renvoAarch64AsmPopReg(a,1)
}

// Generated from bounded sequence renvoAarch64AsmPopReg.
func renvoAarch64AsmPopReg(a *renvoAsm, reg int) {
	renvoAarch64AsmEmit(a,0xf84107e0|reg)
}

// Generated from bounded sequence renvoAarch64AsmPopRsi.
func renvoAarch64AsmPopRsi(a *renvoAsm) {
	renvoAarch64AsmPopReg(a,4)
}

// Generated from bounded sequence renvoAarch64AsmPushImm.
func renvoAarch64AsmPushImm(a *renvoAsm, imm int) {
	renvoAarch64AsmMovRegImm(a,9,imm)
	renvoAarch64AsmPushReg(a,9)
}

// Generated from bounded sequence renvoAarch64AsmPushRax.
func renvoAarch64AsmPushRax(a *renvoAsm) {
	renvoAarch64AsmPushReg(a,0)
}

// Generated from bounded sequence renvoAarch64AsmPushRcx.
func renvoAarch64AsmPushRcx(a *renvoAsm) {
	renvoAarch64AsmPushReg(a,2)
}

// Generated from bounded sequence renvoAarch64AsmPushRdx.
func renvoAarch64AsmPushRdx(a *renvoAsm) {
	renvoAarch64AsmPushReg(a,1)
}

// Generated from bounded sequence renvoAarch64AsmPushReg.
func renvoAarch64AsmPushReg(a *renvoAsm, reg int) {
	renvoAarch64AsmEmit(a,0xf81f0fe0|reg)
}

// Generated from bounded sequence renvoAarch64AsmRet.
func renvoAarch64AsmRet(a *renvoAsm) {
	renvoAarch64AsmEmit(a,0xd65f03c0)
}

// Generated from bounded sequence renvoAarch64AsmSarRaxImm.
func renvoAarch64AsmSarRaxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmEmit(a,0x9340fc00|(imm<<16))
}

// Generated from bounded sequence renvoAarch64AsmShlRaxImm.
func renvoAarch64AsmShlRaxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmEmit(a,0xd3400000|((64-imm)<<16)|((63-imm)<<10))
}

// Generated from bounded sequence renvoAarch64AsmShlRcxImm.
func renvoAarch64AsmShlRcxImm(a *renvoAsm, imm int) {
	renvoAarch64AsmEmit(a,0xd3400000|((64-imm)<<16)|((63-imm)<<10)|(2<<5)|2)
}

// Generated from bounded sequence renvoAarch64AsmStoreAlMemRdxRcx1.
func renvoAarch64AsmStoreAlMemRdxRcx1(a *renvoAsm) {
	renvoAarch64AsmAddRegRegShift(a,12,1,2,0)
	renvoAarch64AsmStoreRegMem(a,0,12,0,1)
}

// Generated from bounded sequence renvoAarch64AsmStoreRaxBss.
func renvoAarch64AsmStoreRaxBss(a *renvoAsm, bssOff int) {
	renvoAarch64AsmMovRegAbs(a,12,bssOff,1)
	renvoAarch64AsmStoreRegMem(a,0,12,0,8)
}

// Generated from bounded sequence renvoAarch64AsmStoreRaxMemRdxDisp.
func renvoAarch64AsmStoreRaxMemRdxDisp(a *renvoAsm, disp int) {
	renvoAarch64AsmStoreRegMem(a,0,1,disp,8)
}

// Generated from bounded sequence renvoAarch64AsmStoreRaxMemRdxDispSize.
func renvoAarch64AsmStoreRaxMemRdxDispSize(a *renvoAsm, disp int, size int) {
	renvoAarch64AsmStoreRegMem(a,0,1,disp,size)
}

// Generated from bounded sequence renvoAarch64AsmStoreRaxMemRdxRcx8.
func renvoAarch64AsmStoreRaxMemRdxRcx8(a *renvoAsm) {
	renvoAarch64AsmAddRegRegShift(a,12,1,2,3)
	renvoAarch64AsmStoreRegMem(a,0,12,0,8)
}

// Generated from bounded sequence renvoAarch64AsmStoreRegStack.
func renvoAarch64AsmStoreRegStack(a *renvoAsm, src int, offset int) {
	renvoAarch64AsmStoreRegMem(a,src,29,-offset,8)
}

// Generated from bounded sequence renvoAarch64AsmStoreSliceStack.
func renvoAarch64AsmStoreSliceStack(a *renvoAsm, offset int) {
	renvoAarch64AsmStoreRegStack(a,0,offset)
	renvoAarch64AsmStoreRegStack(a,1,offset-8)
	renvoAarch64AsmStoreRegStack(a,2,offset-16)
}

// Generated from bounded sequence renvoAarch64AsmSubRaxRcx.
func renvoAarch64AsmSubRaxRcx(a *renvoAsm) {
	renvoAarch64AsmSubRegReg(a,0,0,2)
}

// Generated from bounded sequence renvoAarch64AsmSubRegReg.
func renvoAarch64AsmSubRegReg(a *renvoAsm, dst int, left int, right int) {
	renvoAarch64AsmEmit(a,0xcb000000|(right<<16)|(left<<5)|dst)
}

// Generated from bounded sequence renvoAarch64AsmSyscall.
func renvoAarch64AsmSyscall(a *renvoAsm) {
	renvoAarch64AsmMovRegReg(a,8,0)
	renvoAarch64AsmMovRegReg(a,9,1)
	renvoAarch64AsmMovRegReg(a,0,3)
	renvoAarch64AsmMovRegReg(a,1,4)
	renvoAarch64AsmMovRegReg(a,2,9)
	renvoAarch64AsmMovRegReg(a,3,7)
	renvoAarch64AsmEmit(a,0xd4000001)
}

// Generated from bounded sequence renvoAarch64AsmBCondLabel.
func renvoAarch64AsmBCondLabel(a *renvoAsm, label int, cond int) {
	at:=len(a.code)
	renvoAarch64AsmEmit(a,0x54000000|cond)
	renvoAsmAddReloc(a,at,label)
}

// Generated from bounded sequence renvoAarch64AsmCallLabel.
func renvoAarch64AsmCallLabel(a *renvoAsm, label int) {
	at:=len(a.code)
	renvoAarch64AsmEmit(a,0x94000000)
	renvoAsmAddReloc(a,at,label)
}

// Generated from bounded sequence renvoAarch64AsmCmpRcxRaxSet.
func renvoAarch64AsmCmpRcxRaxSet(a *renvoAsm, setcc int) {
	renvoAarch64AsmCmpRegReg(a,2,0)
	cond:=renvoAarch64CondFromSetcc(setcc)
	renvoAarch64AsmCsetRax(a,cond)
}

// Generated from bounded sequence renvoAarch64AsmJmpLabel.
func renvoAarch64AsmJmpLabel(a *renvoAsm, label int) {
	at:=len(a.code)
	renvoAarch64AsmEmit(a,0x14000000)
	renvoAsmAddReloc(a,at,label)
}

// Generated from bounded sequence renvoAarch64AsmMovRegAbs.
func renvoAarch64AsmMovRegAbs(a *renvoAsm, reg int, off int, kind int) {
	at:=len(a.code)
	renvoAarch64AsmMovRegImm(a,reg,0)
	renvoAarch64AsmEmit(a,0xf2800000|(1<<21)|reg)
	renvoAarch64AsmEmit(a,0xf2800000|(2<<21)|reg)
	renvoAarch64AsmEmit(a,0xf2800000|(3<<21)|reg)
	renvoAsmAddAbsReloc(a,at,off,kind)
}
