// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: target-projection/windows/arm64
// unit: native 4fa4be83de6f23f1817bbf019e3161f1f3607526f1498234da11ff902435218b
package main


func rtgBuiltinWindowsAarch64PackageWindowsStaticCall(out *renvoAsm, importID int, wordCount int) {
	registerWords := wordCount
	if registerWords > 8 {
		registerWords = 8
	}
	for i := 0; i < registerWords; i++ {
		renvoAarch64AsmPopReg(out, i)
	}
	stackWords := wordCount - registerWords
	renvoAarch64AsmEmit(out, 0x910003e9)
	savedSPOff := stackWords * 8
	allocation := renvoAlignValue(savedSPOff+8, 16)
	renvoAarch64AsmAddRegImm(out, 31, 31, -allocation)
	for i := 0; i < stackWords; i++ {
		renvoAarch64AsmLoadRegMem(out, 10, 9, i*16, 8)
		renvoAarch64AsmStoreRegMem(out, 10, 31, i*8, 8)
	}
	renvoAarch64AsmStoreRegMem(out, 9, 31, savedSPOff, 8)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out, importID)
	renvoAarch64AsmMovRegReg(out, 10, 0)
	renvoAarch64AsmLoadRegMem(out, 9, 31, savedSPOff, 8)
	renvoAarch64AsmEmit(out, 0x9100013f)
	renvoAarch64AsmAddRegImm(out, 31, 31, stackWords*16)
	renvoAarch64AsmMovRegReg(out, 0, 10)
}

func rtgBuiltinWindowsAarch64PackageWindowsExit(out *renvoAsm, status int) {
	renvoAarch64AsmMovRegReg(out,0,status)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,8)
}

func rtgBuiltinWindowsAarch64PackageWindowsCallImport(out *renvoAsm, importID int) {
	renvoAarch64AsmMovRegAbs(out,16,importID,2)
	renvoAarch64AsmLoadRegMem(out,16,16,0,8)
	renvoAarch64AsmEmit(out,0xd63f0200)
}

func rtgBuiltinWindowsAarch64PackageWindowsRuntimeChmod(out *renvoAsm) {
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmMovRegReg(out,0,3)
	renvoAarch64AsmMovRegImm(out,1,0)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,1)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,-1)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,failed,0)
	renvoAarch64AsmMovRegImm(out,0,0)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, failed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAsmMarkLabel(out, done)
}

func rtgBuiltinWindowsAarch64PackageWindowsRuntimeClose(out *renvoAsm) {
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmMovRegReg(out,0,3)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,2)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,failed,0)
	renvoAarch64AsmMovRegImm(out,0,0)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, failed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAsmMarkLabel(out, done)
}

func rtgBuiltinWindowsAarch64PackageWindowsRuntimeOpen(out *renvoAsm) {
	renvoAarch64AsmMovRegReg(out,9,3)
	renvoAarch64AsmMovRegReg(out,0,4)
	rtgBuiltinWindowsAarch64PackageWindowsTranslateCreateFileFlags(out)
	renvoAarch64AsmMovRegReg(out,0,9)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,1)
}

func rtgBuiltinWindowsAarch64PackageWindowsTestRegImmediate(out *renvoAsm, register int, immediate int) {
	renvoAarch64AsmMovRegImm(out,15,immediate)
	renvoAarch64AsmEmit(out,0xea00001f|(15<<16)|(register<<5))
}

func rtgBuiltinWindowsAarch64PackageWindowsTranslateCreateFileFlags(out *renvoAsm) {
	notReadWrite:=renvoAsmNewLabel(out)
	accessDone:=renvoAsmNewLabel(out)
	noCreate:=renvoAsmNewLabel(out)
	createDone:=renvoAsmNewLabel(out)
	renvoAarch64AsmMovRegImm(out,1,-2147483648)
	rtgBuiltinWindowsAarch64PackageWindowsTestRegImmediate(out,0,2)
	renvoAarch64AsmBCondLabel(out,notReadWrite,0)
	renvoAarch64AsmMovRegImm(out,1,-1073741824)
	renvoAarch64AsmJmpLabel(out, accessDone)
	renvoAsmMarkLabel(out, notReadWrite)
	rtgBuiltinWindowsAarch64PackageWindowsTestRegImmediate(out,0,1)
	renvoAarch64AsmBCondLabel(out,accessDone,0)
	renvoAarch64AsmMovRegImm(out,1,0x40000000)
	renvoAsmMarkLabel(out, accessDone)
	renvoAarch64AsmMovRegImm(out,4,3)
	rtgBuiltinWindowsAarch64PackageWindowsTestRegImmediate(out,0,64)
	renvoAarch64AsmBCondLabel(out,noCreate,0)
	renvoAarch64AsmMovRegImm(out,4,4)
	rtgBuiltinWindowsAarch64PackageWindowsTestRegImmediate(out,0,512)
	renvoAarch64AsmBCondLabel(out,createDone,0)
	renvoAarch64AsmMovRegImm(out,4,2)
	renvoAarch64AsmJmpLabel(out, createDone)
	renvoAsmMarkLabel(out, noCreate)
	rtgBuiltinWindowsAarch64PackageWindowsTestRegImmediate(out,0,512)
	renvoAarch64AsmBCondLabel(out,createDone,0)
	renvoAarch64AsmMovRegImm(out,4,5)
	renvoAsmMarkLabel(out, createDone)
	renvoAarch64AsmMovRegImm(out,2,3)
	renvoAarch64AsmMovRegImm(out,3,0)
	renvoAarch64AsmMovRegImm(out,5,0x80)
	renvoAarch64AsmMovRegImm(out,6,0)
}

func rtgBuiltinWindowsAarch64PackageWindowsEntry(out *renvoAsm, argsOffset int, argsTextOffset int, argsLengthOffset int, environmentOffset int, environmentLengthOffset int) {
	skip:=renvoAsmNewLabel(out)
	start:=renvoAsmNewLabel(out)
	copyArgument:=renvoAsmNewLabel(out)
	quote:=renvoAsmNewLabel(out)
	setQuote:=renvoAsmNewLabel(out)
	copyCharacter:=renvoAsmNewLabel(out)
	argumentDone:=renvoAsmNewLabel(out)
	argumentsDone:=renvoAsmNewLabel(out)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,7)
	renvoAarch64AsmMovRegReg(out,9,0)
	renvoAarch64AsmMovRegAbs(out,10,argsOffset,1)
	renvoAarch64AsmMovRegAbs(out,11,argsTextOffset,1)
	renvoAarch64AsmMovRegImm(out,12,0)
	renvoAsmMarkLabel(out, skip)
	renvoAarch64AsmLoadRegMem(out,13,9,0,1)
	renvoAarch64AsmCmpRegImm(out,13,0)
	renvoAarch64AsmBCondLabel(out,argumentsDone,0)
	renvoAarch64AsmCmpRegImm(out,13,92)
	renvoAarch64AsmBCondLabel(out,start,1)
	renvoAarch64AsmAddRegImm(out,9,9,1)
	renvoAarch64AsmJmpLabel(out, skip)
	renvoAsmMarkLabel(out, start)
	renvoAarch64AsmCmpRegImm(out,13,9)
	renvoAarch64AsmBCondLabel(out,copyArgument,1)
	renvoAarch64AsmAddRegImm(out,9,9,1)
	renvoAarch64AsmJmpLabel(out, skip)
	renvoAsmMarkLabel(out, copyArgument)
	renvoAarch64AsmMovRegReg(out,14,11)
	renvoAarch64AsmMovRegImm(out,15,0)
	renvoAarch64AsmMovRegImm(out,17,0)
	copyLoop:=renvoAsmNewLabel(out)
	renvoAsmMarkLabel(out, copyLoop)
	renvoAarch64AsmLoadRegMem(out,13,9,0,1)
	renvoAarch64AsmCmpRegImm(out,13,0)
	renvoAarch64AsmBCondLabel(out,argumentDone,0)
	renvoAarch64AsmCmpRegImm(out,13,'"')
	renvoAarch64AsmBCondLabel(out,quote,0)
	renvoAarch64AsmCmpRegImm(out,17,0)
	renvoAarch64AsmBCondLabel(out,copyCharacter,1)
	renvoAarch64AsmCmpRegImm(out,13,92)
	renvoAarch64AsmBCondLabel(out,argumentDone,0)
	renvoAarch64AsmCmpRegImm(out,13,9)
	renvoAarch64AsmBCondLabel(out,argumentDone,0)
	renvoAsmMarkLabel(out, copyCharacter)
	renvoAarch64AsmStoreRegMem(out,13,11,0,1)
	renvoAarch64AsmAddRegImm(out,9,9,1)
	renvoAarch64AsmAddRegImm(out,11,11,1)
	renvoAarch64AsmAddRegImm(out,15,15,1)
	renvoAarch64AsmJmpLabel(out, copyLoop)
	renvoAsmMarkLabel(out, quote)
	renvoAarch64AsmCmpRegImm(out,17,0)
	renvoAarch64AsmBCondLabel(out,setQuote,0)
	renvoAarch64AsmMovRegImm(out,17,0)
	renvoAarch64AsmAddRegImm(out,9,9,1)
	renvoAarch64AsmJmpLabel(out, copyLoop)
	renvoAsmMarkLabel(out, setQuote)
	renvoAarch64AsmMovRegImm(out,17,1)
	renvoAarch64AsmAddRegImm(out,9,9,1)
	renvoAarch64AsmJmpLabel(out, copyLoop)
	renvoAsmMarkLabel(out, argumentDone)
	renvoAarch64AsmStoreRegMem(out,31,11,0,1)
	renvoAarch64AsmStoreRegMem(out,14,10,0,8)
	renvoAarch64AsmStoreRegMem(out,15,10,8,8)
	renvoAarch64AsmAddRegImm(out,10,10,16)
	renvoAarch64AsmAddRegImm(out,11,11,1)
	renvoAarch64AsmAddRegImm(out,12,12,1)
	renvoAarch64AsmCmpRegImm(out,13,0)
	renvoAarch64AsmBCondLabel(out,argumentsDone,0)
	renvoAarch64AsmAddRegImm(out,9,9,1)
	renvoAarch64AsmJmpLabel(out, skip)
	renvoAsmMarkLabel(out, argumentsDone)
	renvoAarch64AsmMovRegAbs(out,9,argsLengthOffset,1)
	renvoAarch64AsmStoreRegMem(out,12,9,0,8)
	environmentLoop:=renvoAsmNewLabel(out)
	environmentLength:=renvoAsmNewLabel(out)
	environmentStringDone:=renvoAsmNewLabel(out)
	environmentDone:=renvoAsmNewLabel(out)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,9)
	renvoAarch64AsmMovRegReg(out,9,0)
	renvoAarch64AsmMovRegAbs(out,10,environmentOffset,1)
	renvoAarch64AsmMovRegImm(out,11,0)
	renvoAsmMarkLabel(out, environmentLoop)
	renvoAarch64AsmLoadRegMem(out,12,9,0,1)
	renvoAarch64AsmCmpRegImm(out,12,0)
	renvoAarch64AsmBCondLabel(out,environmentDone,0)
	renvoAarch64AsmStoreRegMem(out,9,10,0,8)
	renvoAarch64AsmMovRegImm(out,13,0)
	renvoAsmMarkLabel(out, environmentLength)
	renvoAarch64AsmAddRegReg(out,14,9,13)
	renvoAarch64AsmLoadRegMem(out,12,14,0,1)
	renvoAarch64AsmCmpRegImm(out,12,0)
	renvoAarch64AsmBCondLabel(out,environmentStringDone,0)
	renvoAarch64AsmAddRegImm(out,13,13,1)
	renvoAarch64AsmJmpLabel(out, environmentLength)
	renvoAsmMarkLabel(out, environmentStringDone)
	renvoAarch64AsmStoreRegMem(out,13,10,8,8)
	renvoAarch64AsmAddRegImm(out,10,10,16)
	renvoAarch64AsmAddRegImm(out,13,13,1)
	renvoAarch64AsmAddRegReg(out,9,9,13)
	renvoAarch64AsmAddRegImm(out,11,11,1)
	renvoAarch64AsmJmpLabel(out, environmentLoop)
	renvoAsmMarkLabel(out, environmentDone)
	renvoAarch64AsmMovRegAbs(out,9,environmentLengthOffset,1)
	renvoAarch64AsmStoreRegMem(out,11,9,0,8)
	renvoAarch64AsmMovRegAbs(out,3,argsOffset,1)
	renvoAarch64AsmMovRegAbs(out,9,argsLengthOffset,1)
	renvoAarch64AsmLoadRegMem(out,4,9,0,8)
	renvoAarch64AsmMovRegReg(out,1,4)
	renvoAarch64AsmMovRegAbs(out,2,environmentOffset,1)
	renvoAarch64AsmMovRegReg(out,5,11)
	renvoAarch64AsmMovRegReg(out,6,11)
}

func rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out *renvoAsm, importID int, countOffset int) {
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmLoadRegMem(out,1,31,32,8)
	renvoAarch64AsmLoadRegMem(out,2,31,16,8)
	renvoAarch64AsmMovRegAbs(out,3,countOffset,1)
	renvoAarch64AsmMovRegImm(out,4,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,importID)
}

func rtgBuiltinWindowsAarch64PackageWindowsRead(out *renvoAsm) {
	helper:=renvoAsmNewLabel(out)
	after:=renvoAsmNewLabel(out)
	countOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	positionOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	resultOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	standard:=renvoAsmNewLabel(out)
	standardError:=renvoAsmNewLabel(out)
	handleReady:=renvoAsmNewLabel(out)
	sequential:=renvoAsmNewLabel(out)
	positionFailed:=renvoAsmNewLabel(out)
	ioFailed:=renvoAsmNewLabel(out)
	restore:=renvoAsmNewLabel(out)
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmJmpLabel(out, after)
	renvoAsmMarkLabel(out, helper)
	renvoAarch64AsmPushReg(out,30)
	renvoAarch64AsmPushReg(out,3)
	renvoAarch64AsmPushReg(out,4)
	renvoAarch64AsmPushReg(out,2)
	renvoAarch64AsmPushReg(out,1)
	renvoAarch64AsmLoadRegMem(out,9,31,48,8)
	renvoAarch64AsmCmpRegImm(out,9,0)
	renvoAarch64AsmBCondLabel(out,standard,0)
	renvoAarch64AsmStoreRegMem(out,9,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standard)
	standardHandle:=-10
	renvoAarch64AsmMovRegImm(out,0,standardHandle)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standardError)
	renvoAarch64AsmMovRegImm(out,0,-12)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAsmMarkLabel(out, handleReady)
	renvoAarch64AsmLoadRegMem(out,9,31,0,8)
	renvoAarch64AsmCmpRegImm(out,9,0)
	renvoAarch64AsmBCondLabel(out,sequential,11)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegImm(out,1,0)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,1)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,positionFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmStoreRegMem(out,0,9,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmLoadRegMem(out,1,31,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,3,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,9,9,0,8)
	renvoAarch64AsmJmpLabel(out, restore)
	renvoAsmMarkLabel(out, ioFailed)
	renvoAarch64AsmMovRegImm(out,9,-1)
	renvoAsmMarkLabel(out, restore)
	renvoAarch64AsmMovRegAbs(out,10,resultOffset,1)
	renvoAarch64AsmStoreRegMem(out,9,10,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmLoadRegMem(out,1,9,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegAbs(out,9,resultOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, positionFailed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, sequential)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,3,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,failed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, failed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAsmMarkLabel(out, done)
	renvoAarch64AsmAddRegImm(out,31,31,64)
	renvoAarch64AsmPopReg(out,30)
	renvoAarch64AsmRet(out)
	renvoAsmMarkLabel(out, after)
	renvoAarch64AsmMovRegImm(out,2,-1)
	renvoAarch64AsmCallLabel(out, helper)
}

func rtgBuiltinWindowsAarch64PackageWindowsWrite(out *renvoAsm) {
	helper:=renvoAsmNewLabel(out)
	after:=renvoAsmNewLabel(out)
	countOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	positionOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	resultOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	standard:=renvoAsmNewLabel(out)
	standardError:=renvoAsmNewLabel(out)
	handleReady:=renvoAsmNewLabel(out)
	sequential:=renvoAsmNewLabel(out)
	positionFailed:=renvoAsmNewLabel(out)
	ioFailed:=renvoAsmNewLabel(out)
	restore:=renvoAsmNewLabel(out)
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmJmpLabel(out, after)
	renvoAsmMarkLabel(out, helper)
	renvoAarch64AsmPushReg(out,30)
	renvoAarch64AsmPushReg(out,3)
	renvoAarch64AsmPushReg(out,4)
	renvoAarch64AsmPushReg(out,2)
	renvoAarch64AsmPushReg(out,1)
	renvoAarch64AsmLoadRegMem(out,9,31,48,8)
	renvoAarch64AsmCmpRegImm(out,9,1)
	renvoAarch64AsmBCondLabel(out,standard,0)
	renvoAarch64AsmCmpRegImm(out,9,2)
	renvoAarch64AsmBCondLabel(out,standardError,0)
	renvoAarch64AsmStoreRegMem(out,9,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standard)
	standardHandle:=-10
	standardHandle=-11
	renvoAarch64AsmMovRegImm(out,0,standardHandle)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standardError)
	renvoAarch64AsmMovRegImm(out,0,-12)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAsmMarkLabel(out, handleReady)
	renvoAarch64AsmLoadRegMem(out,9,31,0,8)
	renvoAarch64AsmCmpRegImm(out,9,0)
	renvoAarch64AsmBCondLabel(out,sequential,11)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegImm(out,1,0)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,1)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,positionFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmStoreRegMem(out,0,9,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmLoadRegMem(out,1,31,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,4,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,9,9,0,8)
	renvoAarch64AsmJmpLabel(out, restore)
	renvoAsmMarkLabel(out, ioFailed)
	renvoAarch64AsmMovRegImm(out,9,-1)
	renvoAsmMarkLabel(out, restore)
	renvoAarch64AsmMovRegAbs(out,10,resultOffset,1)
	renvoAarch64AsmStoreRegMem(out,9,10,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmLoadRegMem(out,1,9,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegAbs(out,9,resultOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, positionFailed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, sequential)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,4,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,failed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, failed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAsmMarkLabel(out, done)
	renvoAarch64AsmAddRegImm(out,31,31,64)
	renvoAarch64AsmPopReg(out,30)
	renvoAarch64AsmRet(out)
	renvoAsmMarkLabel(out, after)
	renvoAarch64AsmMovRegImm(out,2,-1)
	renvoAarch64AsmCallLabel(out, helper)
}

func rtgBuiltinWindowsAarch64PackageWindowsReadAt(out *renvoAsm) {
	helper:=renvoAsmNewLabel(out)
	after:=renvoAsmNewLabel(out)
	countOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	positionOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	resultOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	standard:=renvoAsmNewLabel(out)
	standardError:=renvoAsmNewLabel(out)
	handleReady:=renvoAsmNewLabel(out)
	sequential:=renvoAsmNewLabel(out)
	positionFailed:=renvoAsmNewLabel(out)
	ioFailed:=renvoAsmNewLabel(out)
	restore:=renvoAsmNewLabel(out)
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmJmpLabel(out, after)
	renvoAsmMarkLabel(out, helper)
	renvoAarch64AsmPushReg(out,30)
	renvoAarch64AsmPushReg(out,3)
	renvoAarch64AsmPushReg(out,4)
	renvoAarch64AsmPushReg(out,2)
	renvoAarch64AsmPushReg(out,1)
	renvoAarch64AsmLoadRegMem(out,9,31,48,8)
	renvoAarch64AsmCmpRegImm(out,9,0)
	renvoAarch64AsmBCondLabel(out,standard,0)
	renvoAarch64AsmStoreRegMem(out,9,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standard)
	standardHandle:=-10
	renvoAarch64AsmMovRegImm(out,0,standardHandle)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standardError)
	renvoAarch64AsmMovRegImm(out,0,-12)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAsmMarkLabel(out, handleReady)
	renvoAarch64AsmLoadRegMem(out,9,31,0,8)
	renvoAarch64AsmCmpRegImm(out,9,0)
	renvoAarch64AsmBCondLabel(out,sequential,11)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegImm(out,1,0)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,1)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,positionFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmStoreRegMem(out,0,9,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmLoadRegMem(out,1,31,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,3,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,9,9,0,8)
	renvoAarch64AsmJmpLabel(out, restore)
	renvoAsmMarkLabel(out, ioFailed)
	renvoAarch64AsmMovRegImm(out,9,-1)
	renvoAsmMarkLabel(out, restore)
	renvoAarch64AsmMovRegAbs(out,10,resultOffset,1)
	renvoAarch64AsmStoreRegMem(out,9,10,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmLoadRegMem(out,1,9,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegAbs(out,9,resultOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, positionFailed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, sequential)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,3,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,failed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, failed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAsmMarkLabel(out, done)
	renvoAarch64AsmAddRegImm(out,31,31,64)
	renvoAarch64AsmPopReg(out,30)
	renvoAarch64AsmRet(out)
	renvoAsmMarkLabel(out, after)
	renvoAarch64AsmCallLabel(out, helper)
}

func rtgBuiltinWindowsAarch64PackageWindowsWriteAt(out *renvoAsm) {
	helper:=renvoAsmNewLabel(out)
	after:=renvoAsmNewLabel(out)
	countOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	positionOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	resultOffset:=renvoWindowsArm64ReserveBSS(out,8,8)
	standard:=renvoAsmNewLabel(out)
	standardError:=renvoAsmNewLabel(out)
	handleReady:=renvoAsmNewLabel(out)
	sequential:=renvoAsmNewLabel(out)
	positionFailed:=renvoAsmNewLabel(out)
	ioFailed:=renvoAsmNewLabel(out)
	restore:=renvoAsmNewLabel(out)
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAarch64AsmJmpLabel(out, after)
	renvoAsmMarkLabel(out, helper)
	renvoAarch64AsmPushReg(out,30)
	renvoAarch64AsmPushReg(out,3)
	renvoAarch64AsmPushReg(out,4)
	renvoAarch64AsmPushReg(out,2)
	renvoAarch64AsmPushReg(out,1)
	renvoAarch64AsmLoadRegMem(out,9,31,48,8)
	renvoAarch64AsmCmpRegImm(out,9,1)
	renvoAarch64AsmBCondLabel(out,standard,0)
	renvoAarch64AsmCmpRegImm(out,9,2)
	renvoAarch64AsmBCondLabel(out,standardError,0)
	renvoAarch64AsmStoreRegMem(out,9,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standard)
	standardHandle:=-10
	standardHandle=-11
	renvoAarch64AsmMovRegImm(out,0,standardHandle)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAarch64AsmJmpLabel(out, handleReady)
	renvoAsmMarkLabel(out, standardError)
	renvoAarch64AsmMovRegImm(out,0,-12)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,6)
	renvoAarch64AsmStoreRegMem(out,0,31,48,8)
	renvoAsmMarkLabel(out, handleReady)
	renvoAarch64AsmLoadRegMem(out,9,31,0,8)
	renvoAarch64AsmCmpRegImm(out,9,0)
	renvoAarch64AsmBCondLabel(out,sequential,11)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegImm(out,1,0)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,1)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,positionFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmStoreRegMem(out,0,9,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmLoadRegMem(out,1,31,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegImm(out,9,0xffffffff)
	renvoAarch64AsmCmpRegReg(out,0,9)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,4,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,ioFailed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,9,9,0,8)
	renvoAarch64AsmJmpLabel(out, restore)
	renvoAsmMarkLabel(out, ioFailed)
	renvoAarch64AsmMovRegImm(out,9,-1)
	renvoAsmMarkLabel(out, restore)
	renvoAarch64AsmMovRegAbs(out,10,resultOffset,1)
	renvoAarch64AsmStoreRegMem(out,9,10,0,8)
	renvoAarch64AsmLoadRegMem(out,0,31,48,8)
	renvoAarch64AsmMovRegAbs(out,9,positionOffset,1)
	renvoAarch64AsmLoadRegMem(out,1,9,0,8)
	renvoAarch64AsmMovRegImm(out,2,0)
	renvoAarch64AsmMovRegImm(out,3,0)
	rtgBuiltinWindowsAarch64PackageWindowsCallImport(out,5)
	renvoAarch64AsmMovRegAbs(out,9,resultOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, positionFailed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, sequential)
	rtgBuiltinWindowsAarch64PackageWindowsReadWriteCall(out,4,countOffset)
	renvoAarch64AsmCmpRegImm(out,0,0)
	renvoAarch64AsmBCondLabel(out,failed,0)
	renvoAarch64AsmMovRegAbs(out,9,countOffset,1)
	renvoAarch64AsmLoadRegMem(out,0,9,0,8)
	renvoAarch64AsmJmpLabel(out, done)
	renvoAsmMarkLabel(out, failed)
	renvoAarch64AsmMovRegImm(out,0,-1)
	renvoAsmMarkLabel(out, done)
	renvoAarch64AsmAddRegImm(out,31,31,64)
	renvoAarch64AsmPopReg(out,30)
	renvoAarch64AsmRet(out)
	renvoAsmMarkLabel(out, after)
	renvoAarch64AsmCallLabel(out, helper)
}


func renvoWindowsArm64ReserveBSS(out *renvoAsm, size int, alignment int) int {
	offset := renvoAlignValue(out.bssSize, alignment)
	out.bssSize = offset + size
	return offset
}

func renvoWinArm64DefinitionStaticCall(a *renvoAsm, importID int, wordCount int) {
	rtgBuiltinWindowsAarch64PackageWindowsStaticCall(a, importID, wordCount)
}

func renvoWinArm64DefinitionOpen(a *renvoAsm) {
	rtgBuiltinWindowsAarch64PackageWindowsRuntimeOpen(a)
}

func renvoWinArm64DefinitionClose(a *renvoAsm) {
	rtgBuiltinWindowsAarch64PackageWindowsRuntimeClose(a)
}

func renvoWinArm64DefinitionChmod(a *renvoAsm) {
	rtgBuiltinWindowsAarch64PackageWindowsRuntimeChmod(a)
}

func renvoWinArm64DefinitionReadAt(g *renvoLinearGen) {
	renvoWinArm64DefinitionReadWrite(g, false)
}

func renvoWinArm64DefinitionWriteAt(g *renvoLinearGen) {
	renvoWinArm64DefinitionReadWrite(g, true)
}

func renvoWinArm64DefinitionReadWrite(g *renvoLinearGen, isWrite bool) {
	a := &g.asm
	label := g.winReadLabel
	if isWrite {
		label = g.winWriteLabel
	}
	if isWrite && g.winWriteEmitted || !isWrite && g.winReadEmitted {
		renvoAsmCallLabel(a, label)
		return
	}
	label = renvoAsmNewLabel(a)
	if isWrite {
		g.winWriteEmitted = true
		g.winWriteLabel = label
	} else {
		g.winReadEmitted = true
		g.winReadLabel = label
	}
	after := renvoAsmNewLabel(a)
	renvoAsmJmpMarkLabel(a, after, label)
	if isWrite {
		rtgBuiltinWindowsAarch64PackageWindowsWriteAt(a)
	} else {
		rtgBuiltinWindowsAarch64PackageWindowsReadAt(a)
	}
	renvoAsmRet(a)
	renvoAsmMarkLabel(a, after)
	renvoAsmCallLabel(a, label)
}

func renvoWinArm64DefinitionExit(a *renvoAsm) {
	rtgBuiltinWindowsAarch64PackageWindowsExit(a, 0)
}

const renvoWindowsArm64ArgsBSSSize = 32768
const renvoWindowsArm64ArgsBSSAlignment = 16
const renvoWindowsArm64ArgsTextBSSSize = 32768
const renvoWindowsArm64ArgsTextBSSAlignment = 16
const renvoWindowsArm64ArgsLengthBSSSize = 8
const renvoWindowsArm64ArgsLengthBSSAlignment = 8
const renvoWindowsArm64EnvironmentBSSSize = 32768
const renvoWindowsArm64EnvironmentBSSAlignment = 16
const renvoWindowsArm64EnvironmentLengthBSSSize = 8
const renvoWindowsArm64EnvironmentLengthBSSAlignment = 8

func renvoWinArm64DefinitionEntry(a *renvoAsm, argsOff int, argsTextOff int, argsLengthOff int, environmentOff int, environmentLengthOff int) {
	rtgBuiltinWindowsAarch64PackageWindowsEntry(a, argsOff, argsTextOff, argsLengthOff, environmentOff, environmentLengthOff)
}


func compileWindowsArm64(input []int, output int) int {
	return compileWindowsArm64Arena(input, output, 0)
}
func compileWindowsArm64Arena(input []int, output int, arenaSize int) int {
	renvoSetTarget(renvoTargetWindowsArm64)
	return renvoCompileAarch64(input, output, arenaSize)
}

func renvoEmitProgramEntryArgsWindowsArm64(g *renvoLinearGen, appIndex int) bool {
	app := &g.meta.funcs[appIndex]
	if app.resultType != 0 && !renvoTypeIsInt(g.meta, app.resultType) {
		return false
	}
	if app.paramCount == 0 {
		return true
	}
	if app.paramCount > 2 || !renvoTypeIsStringSlice(g.meta, g.meta.params[app.firstParam].typ) {
		return false
	}
	if app.paramCount == 2 && !renvoTypeIsStringSlice(g.meta, g.meta.params[app.firstParam+1].typ) {
		return false
	}
	argsOff := renvoAlignValue(g.asm.bssSize, renvoWindowsArm64ArgsBSSAlignment)
	g.asm.bssSize = argsOff + renvoWindowsArm64ArgsBSSSize
	argsTextOff := renvoAlignValue(g.asm.bssSize, renvoWindowsArm64ArgsTextBSSAlignment)
	g.asm.bssSize = argsTextOff + renvoWindowsArm64ArgsTextBSSSize
	argsLenOff := renvoAlignValue(g.asm.bssSize, renvoWindowsArm64ArgsLengthBSSAlignment)
	g.asm.bssSize = argsLenOff + renvoWindowsArm64ArgsLengthBSSSize
	envOff := renvoAlignValue(g.asm.bssSize, renvoWindowsArm64EnvironmentBSSAlignment)
	g.asm.bssSize = envOff + renvoWindowsArm64EnvironmentBSSSize
	envLenOff := renvoAlignValue(g.asm.bssSize, renvoWindowsArm64EnvironmentLengthBSSAlignment)
	g.asm.bssSize = envLenOff + renvoWindowsArm64EnvironmentLengthBSSSize
	renvoWinArm64DefinitionEntry(&g.asm, argsOff, argsTextOff, argsLenOff, envOff, envLenOff)
	return true
}

func renvoAsmPatchWindowsArm64(a *renvoAsm, layout renvoWinImportLayout) {
	for i := 0; i+2 < len(a.absRelocs); i += 3 {
		at := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i))
		off := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i+1))
		kind := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i+2))
		target := a.dataOffset + off
		if kind == renvoAbsWinImportReloc {
			target = layout.iatRVAs[off]
		} else if kind == renvoAbsBssReloc {
			target = renvoAsmBssOffset(a) + off
		}
		insn := renvoGet32At(a.code, at)
		reg := insn & 31
		pc := a.codeOffset + at
		delta := (target >> 12) - (pc >> 12)
		imm := delta & 0x1fffff
		renvoPut32At(a.code, at, 0x90000000|((imm&3)<<29)|(((imm>>2)&0x7ffff)<<5)|reg)
		renvoPut32At(a.code, at+4, 0x91000000|((target&0xfff)<<10)|(reg<<5)|reg)
		renvoPut32At(a.code, at+8, 0xd503201f)
		renvoPut32At(a.code, at+12, 0xd503201f)
	}
}

func renvoAsmImageWindowsArm64(a *renvoAsm) []byte {
	renvoAsmPatch(a)
	for (a.codeOffset+len(a.code))%8 != 0 {
		a.code = append(a.code, 0)
	}
	textVirtualSize := len(a.code)
	textRawSize := renvoAlignValue(textVirtualSize, renvoWinFileAlign)
	dataRVA := renvoAlignValue(a.codeOffset+textVirtualSize, renvoWinSectionAlign)
	a.dataOffset = dataRVA
	var imports renvoWinImportLayout
	if renvoAsmHasWinImportRelocs(a) {
		renvoAppendWinImports(a, &imports)
	}
	renvoAsmPatchWindowsArm64(a, imports)
	dataRawSize := renvoAlignValue(len(a.data), renvoWinFileAlign)
	dataVirtualSize := len(a.data) + a.bssSize
	iatSize := 0
	if imports.kernelIATRVA != 0 {
		iatSize = (renvoWinImportFixedCount + 1) * imports.thunkSize
	}
	var out []byte
	out = renvoAppendPEHeader64WithContext(a.c, out, textRawSize, textVirtualSize, dataRVA, dataRawSize, dataVirtualSize, imports.importRVA, imports.importSize, imports.kernelIATRVA, iatSize)
	out[0xc0] = 6
	out[0xc2] = 1
	out[0xc4] = 1
	out[0xc8] = 6
	out[0xca] = 1
	out[0x9a] = 3
	out[0x96] = 0x22
	out[0xde] = 0
	out[0xdf] = 0x81
	out = append(out, a.code...)
	out = renvoAppendUntil(out, renvoWinHeadersSize+textRawSize)
	out = append(out, a.data...)
	out = renvoAppendUntil(out, renvoWinHeadersSize+textRawSize+dataRawSize)
	if renvoFixedTarget == 0 && a.c.emitImage {
		return renvoAppendReplLinkTable(out, a)
	}
	return out
}
