//go:build !renvo_prepared && !renvo_jvm_prepared

// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: architecture-kernel
package main


type RTGRegister struct {
	Code int
	Valid bool
}

type RTGCondition struct {
	Code       int
	SetOpcode  byte
	JumpOpcode byte
}

type RTGSymbol struct {
	nameStart int
	nameEnd   int
	label     int
}

type RTGShiftDirection int

const (
	RTGShiftLeft RTGShiftDirection = 1
	RTGShiftRight RTGShiftDirection = 2
)

const RTGRelocationAbsoluteData = 0
const RTGRelocationAbsoluteBSS = 1
const RTGRelocationImport = 2
const RTGRelocationAbsoluteBSSEnd = 3
const RTGRuntimeRead = 1
const RTGRuntimeWrite = 2
const RTGRuntimeReadAt = 3
const RTGRuntimeWriteAt = 4
const RTGRuntimeOpen = 5
const RTGRuntimeClose = 6
const RTGRuntimeChmod = 7

const RTGScalarByte = 3
const RTGScalarInt8 = 7
const RTGScalarInt16 = 8
const RTGScalarInt32 = 9
const RTGScalarUint16 = 16
const RTGScalarUint32 = 17

var RTGNoRegister = RTGRegister{}

func renvoRTGLabelCode(code int) int {
	return code
}

func RTGSignedFits(value int64, bits int) bool {
	if bits <= 0 {
		return false
	}
	if bits >= 63 {
		return true
	}
	limit := int64(1) << (bits - 1)
	return value >= -limit && value < limit
}

func RTGUnsignedFits(value uint64, bits int) bool {
	if bits <= 0 {
		return false
	}
	if bits >= 63 {
		return true
	}
	return value < uint64(1)<<bits
}

func renvoRTGRel32(out *renvoAsm, label int) {
	at := len(out.code)
	renvoAsmEmit32(out, 0)
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2001
	}
}

func RTGLog2(value int) int {
	result := 0
	for value > 1 {
		value >>= 1
		result++
	}
	return result
}

type renvoRTGAddress struct {
	Target       int
	TargetValid  bool
	Kind         int
	Addend       int
	Base         RTGRegister
	Index        RTGRegister
	Displacement int
	Scale        int
}

func (out *renvoAsm) Byte(value byte) {
	renvoAsmEmit8(out, int(value))
}

func (out *renvoAsm) Uint32(value uint32) {
	renvoAsmEmit32(out, int(value))
}

func (out *renvoAsm) Uint64(value uint64) {
	renvoAsmEmit32(out, int(value))
	renvoAsmEmit32(out, int(value >> 32))
}

func (out *renvoAsm) PatchUint32(at int, value int) {
	renvoPut32At(out.code, at, value)
}

func (out *renvoAsm) NewLabel() int {
	return renvoAsmNewLabel(out)
}

func (out *renvoAsm) Mark(label int) {
	if label < 0 || label >= len(out.labelPos) || renvoAsmLabelPosition(out, label) >= 0 {
		if renvoRTGUnsupportedOperation == 0 {
			renvoRTGUnsupportedOperation = 2002
		}
		return
	}
	renvoAsmMarkLabel(out, label)
}

func (out *renvoAsm) Rel32(label int) {
	out.Rel32Addend(label, 0)
}

func (out *renvoAsm) Rel32Addend(label int, addend int) {
	at := len(out.code)
	renvoAsmEmit32(out, addend)
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2001
	}
}

func (out *renvoAsm) Reloc(label int) {
	if label >= 0 && len(out.code) >= 4 {
		renvoAsmAddReloc(out, len(out.code)-4, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2003
	}
}

func (out *renvoAsm) Patch() {
	renvoAsmPatch(out)
}

func (out *renvoAsm) Code() []byte {
	return out.code
}

func (out *renvoAsm) SetCode(value []byte) {
	out.code = value
}

func (out *renvoAsm) Data() []byte {
	return out.data
}

func (out *renvoAsm) SetData(value []byte) {
	out.data = value
}

func (out *renvoAsm) SetDataOffset(value int) {
	out.dataOffset = value
}

func (out *renvoAsm) BSSSize() int {
	return out.bssSize
}

func (out *renvoAsm) ReserveBSS(size int, alignment int) int {
	if alignment <= 0 {
		alignment = 1
	}
	offset := renvoAlignValue(out.bssSize, alignment)
	out.bssSize = offset + size
	return offset
}

func (out *renvoAsm) WindowsSubsystem() int {
	return out.c.windowsSubsystem
}

func (out *renvoAsm) StaticImportCount() int {
	return len(out.staticImports)
}

func (out *renvoAsm) StaticImportDLL(index int) string {
	return out.staticImports[index].dll
}

func (out *renvoAsm) StaticImportName(index int) string {
	return out.staticImports[index].name
}

func (out *renvoAsm) StaticCallParameterCount() int {
	return out.staticCallParamCount
}

func (out *renvoAsm) StaticCallParameterKind(index int) int {
	return int(out.staticCallParamKinds[index])
}

func (out *renvoAsm) StaticCallResultFloatRegister() int {
	return out.staticCallResultFloat
}

func (out *renvoAsm) DynamicImport(library string, name string) int {
	for i := 0; i < len(out.darwinImports); i++ {
		if out.darwinImports[i].dylib == library && out.darwinImports[i].name == name {
			out.darwinImports[i].used = true
			return i
		}
	}
	if renvoFixedTarget == 0 || renvoFixedTarget == renvoTargetDarwinArm64 {
		library = renvo_runtime_ArenaPersistString(library)
		name = renvo_runtime_ArenaPersistString(name)
	}
	label := renvoAsmNewLabel(out)
	out.darwinImports = append(out.darwinImports,
		renvoDarwinStaticImport{dylib: library, name: name, label: label, used: true})
	return len(out.darwinImports) - 1
}

func (out *renvoAsm) DynamicImportCount() int {
	return len(out.darwinImports)
}

func (out *renvoAsm) DynamicImportLibrary(index int) string {
	return out.darwinImports[index].dylib
}

func (out *renvoAsm) DynamicImportName(index int) string {
	return out.darwinImports[index].name
}

func (out *renvoAsm) DynamicImportLabel(index int) int {
	return out.darwinImports[index].label
}

func (out *renvoAsm) ExternalImport(name string) int {
	return renvoAsmAddExternalImportName(out, name)
}

func (out *renvoAsm) ExternalImportCount() int {
	return len(out.kernelImportOffsets) / 2
}

func (out *renvoAsm) ExternalImportName(index int) string {
	at := index * 2
	if at < 0 || at+1 >= len(out.kernelImportOffsets) {
		return ""
	}
	return string(out.kernelImportNames[
		out.kernelImportOffsets[at]:out.kernelImportOffsets[at+1]])
}

func (out *renvoAsm) KernelModuleName() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelModuleName
}

func (out *renvoAsm) KernelLicense() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelLicense
}

func (out *renvoAsm) KernelRelease() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelRelease
}

func (out *renvoAsm) KernelVersion() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelVersion
}

func (out *renvoAsm) KernelBTF() []byte {
	if out.c == nil || out.c.kernel == nil {
		return nil
	}
	return out.c.kernel.kernelBTF
}

func (out *renvoAsm) KernelSymvers() []byte {
	if out.c == nil || out.c.kernel == nil {
		return nil
	}
	return out.c.kernel.kernelSymvers
}

func (out *renvoAsm) RelocationCount() int {
	return len(out.relocs) / 2
}

func (out *renvoAsm) RelocationAt(index int) (int, int) {
	at := index * 2
	return int(out.relocs[at]), int(out.relocs[at+1])
}

func (out *renvoAsm) RelocationOffset(index int) int {
	return int(out.relocs[index*2])
}

func (out *renvoAsm) RelocationLabel(index int) int {
	return int(out.relocs[index*2+1])
}

func (out *renvoAsm) RelocationWordCount() int {
	return len(out.relocs)
}

func (out *renvoAsm) RelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.relocs, index))
}

func (out *renvoAsm) AbsoluteRelocationCount() int {
	return len(out.absRelocs) / 3
}

func (out *renvoAsm) AbsoluteRelocationAt(index int) (int, int, int) {
	at := index * 3
	return int(out.absRelocs[at]), int(out.absRelocs[at+1]), int(out.absRelocs[at+2])
}

func (out *renvoAsm) AbsoluteRelocationOffset(index int) int {
	return int(out.absRelocs[index*3])
}

func (out *renvoAsm) AbsoluteRelocationAddend(index int) int {
	return int(out.absRelocs[index*3+1])
}

func (out *renvoAsm) AbsoluteRelocationKind(index int) int {
	return int(out.absRelocs[index*3+2])
}

func (out *renvoAsm) AbsoluteRelocationWordCount() int {
	return len(out.absRelocs)
}

func (out *renvoAsm) AbsoluteRelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.absRelocs, index))
}

func (out *renvoAsm) LabelPosition(label int) int {
	return renvoAsmLabelPosition(out, label)
}

func (out *renvoAsm) SymbolCount() int {
	return len(out.symbols)
}

func (out *renvoAsm) SymbolPC(index int) int {
	return renvoAsmLabelPosition(out, out.symbols[index].label)
}

func (out *renvoAsm) SymbolNameEquals(index int, name string) bool {
	symbol := &out.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func (out *renvoAsm) SymbolNameLength(index int) int {
	symbol := &out.symbols[index]
	return symbol.nameEnd - symbol.nameStart
}

func (out *renvoAsm) SymbolNameByte(index int, offset int) byte {
	symbol := &out.symbols[index]
	return out.symbolName[symbol.nameStart+offset]
}

func (out *renvoAsm) Symbol(index int) *RTGSymbol {
	symbol := &out.symbols[index]
	return &RTGSymbol{nameStart: symbol.nameStart, nameEnd: symbol.nameEnd, label: symbol.label}
}

func (out *renvoAsm) SymbolNameByteAt(index int) byte {
	return out.symbolName[index]
}

func renvoRTGRelocationAt(out *renvoAsm, index int) (int, int) {
	at := index * 2
	return int(out.relocs[at]), int(out.relocs[at+1])
}

func renvoRTGAbsoluteRelocationAt(out *renvoAsm, index int) (int, int, int) {
	at := index * 3
	return int(out.absRelocs[at]), int(out.absRelocs[at+1]), int(out.absRelocs[at+2])
}

func renvoRTGSymbolPC(out *renvoAsm, index int) int {
	return renvoAsmLabelPosition(out, out.symbols[index].label)
}

func renvoRTGSymbolNameEquals(out *renvoAsm, index int, name string) bool {
	symbol := &out.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func renvoRTGAddressValid(address renvoRTGAddress) bool {
	return address.TargetValid || address.Kind != 0
}

func renvoRTGAddressRel32Addend(out *renvoAsm, address renvoRTGAddress) {
	if address.Kind != 0 {
		at := len(out.code)
		renvoAsmEmit32(out, 0)
		renvoAsmAddAbsReloc(out, at, address.Addend, address.Kind-1)
		return
	}
	out.Rel32Addend(address.Target, address.Addend)
}

func renvoRTGAddressRelocAt(out *renvoAsm, address renvoRTGAddress, at int) {
	if address.Kind != 0 {
		renvoAsmAddAbsReloc(out, at, address.Addend, address.Kind-1)
		return
	}
	if address.TargetValid {
		renvoAsmAddReloc(out, at, address.Target)
	}
}

func renvoRTGLabelRelocAt(out *renvoAsm, label int, at int) {
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	}
}

func renvoRTGDataAddress(offset int) renvoRTGAddress {
	return renvoRTGAddress{Kind: 1, Addend: offset}
}

func renvoRTGBSSAddress(offset int) renvoRTGAddress {
	return renvoRTGAddress{Kind: 2, Addend: offset}
}

func renvoRTGBSSEndAddress(alignment int) renvoRTGAddress {
	return renvoRTGAddress{Kind: 4, Addend: alignment}
}

func renvoRTGResolveAbsoluteRelocation(out *renvoAsm, kind int, addend int, dataAddress int, bssAddress int) (int, bool) {
	if kind == RTGRelocationAbsoluteData {
		return dataAddress + addend, true
	}
	if kind == RTGRelocationAbsoluteBSS {
		return bssAddress + addend, true
	}
	if kind == RTGRelocationAbsoluteBSSEnd {
		if addend <= 0 {
			addend = 1
		}
		return bssAddress + renvoAlignValue(out.bssSize, addend), true
	}
	return 0, false
}

func renvoRTGByte(out *renvoAsm, value byte) {
	renvoAsmEmit8(out, int(value))
}

func renvoRTGUint32(out *renvoAsm, value int) {
	renvoAsmEmit32(out, value)
}

func renvoRTGUint64(out *renvoAsm, value uint64) {
	renvoAsmEmit32(out, int(value))
	renvoAsmEmit32(out, int(value >> 32))
}

func renvoRTGPatchUint32(out *renvoAsm, at int, value int) {
	renvoPut32At(out.code, at, value)
}

func renvoRTGNewLabel(out *renvoAsm) int {
	return renvoAsmNewLabel(out)
}

func renvoRTGMark(out *renvoAsm, label int) {
	if label < 0 || label >= len(out.labelPos) || renvoAsmLabelPosition(out, label) >= 0 {
		if renvoRTGUnsupportedOperation == 0 {
			renvoRTGUnsupportedOperation = 2002
		}
		return
	}
	renvoAsmMarkLabel(out, label)
}

func renvoRTGReloc(out *renvoAsm, label int) {
	if label >= 0 && len(out.code) >= 4 {
		renvoAsmAddReloc(out, len(out.code)-4, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2003
	}
}

var renvoRTGUnsupportedOperation int

func renvoRTGDirectMove(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 1 }
}

func renvoRTGDirectAddress(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 2 }
}

func renvoRTGDirectLoadNative(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 3 }
}

func renvoRTGDirectLoadI32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 4 }
}

func renvoRTGDirectLoadU32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 5 }
}

func renvoRTGDirectLoadI16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 6 }
}

func renvoRTGDirectLoadU16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 7 }
}

func renvoRTGDirectLoadI8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 8 }
}

func renvoRTGDirectLoadU8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 9 }
}

func renvoRTGDirectStoreNative(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 10 }
}

func renvoRTGDirectStoreU32(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 11 }
}

func renvoRTGDirectStoreU16(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 12 }
}

func renvoRTGDirectStoreU8(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 13 }
}

func renvoRTGDirectAdd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 14 }
}

func renvoRTGDirectSubtract(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 15 }
}

func renvoRTGDirectMultiply(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 16 }
}

func renvoRTGDirectBitAnd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 17 }
}

func renvoRTGDirectBitOr(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 18 }
}

func renvoRTGDirectBitXor(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 19 }
}

func renvoRTGDirectCompare(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 20 }
}

func renvoRTGDirectTest(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 21 }
}

func renvoRTGDirectIncrement(out *renvoAsm, operand RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 22 }
}

func renvoRTGDirectDecrement(out *renvoAsm, operand RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 23 }
}

func renvoRTGDirectShiftLeftImmediate(out *renvoAsm, destination RTGRegister, value byte) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 24 }
}

func renvoRTGDirectShiftRightUnsignedImmediate(out *renvoAsm, destination RTGRegister, value byte) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 25 }
}

func renvoRTGDirectShiftRightSignedImmediate(out *renvoAsm, destination RTGRegister, value byte) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 26 }
}

func renvoRTGDirectCall(out *renvoAsm, label int) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 27 }
}

func renvoRTGDirectCallIndirect(out *renvoAsm, operand RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 28 }
}

func renvoRTGDirectJump(out *renvoAsm, label int) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 29 }
}

func renvoRTGDirectJumpCondition(out *renvoAsm, condition RTGCondition, label int) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 30 }
}

func renvoRTGDirectSetCondition(out *renvoAsm, condition RTGCondition, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 31 }
}

func renvoRTGDirectReturn(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 32 }
}

func renvoRTGDirectLeave(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 33 }
}

func renvoRTGDirectHostSyscall(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 34 }
}

func renvoRTGDirectMoveImmediate(out *renvoAsm, destination RTGRegister, value int64) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 35 }
}

func renvoRTGDirectVariableShift(out *renvoAsm, direction RTGShiftDirection, signed bool) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 36 }
}

func renvoRTGDirectSignedDivide(out *renvoAsm, remainder bool) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 37 }
}

func renvoRTGDirectCopyBytes(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 38 }
}

var renvoRTGPrimary = RTGNoRegister
var renvoRTGSecondary = RTGNoRegister
var renvoRTGTertiary = RTGNoRegister
var renvoRTGScratch = RTGNoRegister
var renvoRTGCopyDestination = RTGNoRegister
var renvoRTGCopySource = RTGNoRegister
var renvoRTGCopyCount = RTGNoRegister
var renvoRTGStack = RTGNoRegister
var renvoRTGFrame = RTGNoRegister
var renvoRTGCallWord0 = RTGNoRegister
var renvoRTGCallWord1 = RTGNoRegister
var renvoRTGCallWord2 = RTGNoRegister
var renvoRTGCallWord3 = RTGNoRegister
var renvoRTGCallWord4 = RTGNoRegister
var renvoRTGCallWord5 = RTGNoRegister
var renvoRTGSyscallNumber = RTGNoRegister
var renvoRTGSyscallWord0 = RTGNoRegister
var renvoRTGSyscallWord1 = RTGNoRegister
var renvoRTGSyscallWord2 = RTGNoRegister
var renvoRTGSyscallWord3 = RTGNoRegister
var renvoRTGSyscallWord4 = RTGNoRegister
var renvoRTGSyscallWord5 = RTGNoRegister
var renvoRTGSyscallResult = RTGNoRegister
const renvoRTGStackWordBytes = 0
func renvoRTGConditionFromSetcc(setcc int) RTGCondition { return RTGCondition{} }
func renvoRTGPatchRelocations(out *renvoAsm) {}
func renvoRTGFrameStart(out *renvoAsm) int { return -1 }
func renvoRTGFrameFinish(out *renvoAsm, framePatch int, stackUsed int) {}
func renvoRTGABIPushRegister(out *renvoAsm, source RTGRegister) bool { return false }
func renvoRTGABIPushImmediate(out *renvoAsm, value int) bool { return false }
func renvoRTGABIPopRegister(out *renvoAsm, destination RTGRegister) bool { return false }
func renvoRTGABILoadFrame(out *renvoAsm, destination RTGRegister, offset int) bool { return false }
func renvoRTGABIStoreFrame(out *renvoAsm, offset int, source RTGRegister) bool { return false }
func renvoRTGABIAddressFrame(out *renvoAsm, destination RTGRegister, offset int) bool { return false }
func renvoRTGABIStoreParamWord(out *renvoAsm, word int, offset int) bool { return false }
func renvoRTGABICallWordCount(out *renvoAsm, label int, wordCount int) bool { return false }
func renvoRTGMarkLabel(out *renvoAsm, label int) {}
func renvoRTGFunctionStart(out *renvoAsm, label int) {}
func renvoRTGFunctionFinish(out *renvoAsm) {}
func renvoRTGEmitJITCall(out *renvoAsm, entry RTGRegister, stackTop RTGRegister, argsData RTGRegister, argsLen RTGRegister, envData RTGRegister, envLen RTGRegister) bool { return false }
func renvoRTGEmitUnsignedDivide(out *renvoAsm, remainder bool) bool { return false }
const renvoRTGCodeOffset = 0
func renvoRTGImage(out *renvoAsm) []byte { return nil }
func renvoRTGKernelImage(out *renvoAsm, initLabel int, exitLabel int) []byte { return nil }
const renvoRTGEntryStateBytes = 0
func renvoRTGEmitEntryStart(out *renvoAsm, stateOffset int) bool { return true }
func renvoRTGEmitEntry(out *renvoAsm, parameterCount int, stateOffset int) bool { return parameterCount == 0 }
func renvoRTGKernelEntryPrologue(out *renvoAsm) {}
func renvoRTGKernelEntryEpilogue(out *renvoAsm) {}
func renvoRTGKernelCallbackAddress(out *renvoAsm, label int) {}
func renvoRTGEmitExit(out *renvoAsm, status RTGRegister) bool { return false }
func renvoRTGEmitStaticCall(out *renvoAsm, importID int, wordCount int) bool { return false }
func renvoRTGEmitRuntimeOperation(out *renvoAsm, operation int) bool { return false }

const renvoRTGPreparedOS = 0
const renvoRTGPreparedIntBits = 0
const renvoRTGPreparedKernelModule = 0
const renvoRTGPreparedObject = 0
const renvoRTGPreparedSysVX8664 = 0
const renvoRTGPreparedFunctionSymbols = 0
const renvoRTGPreparedIEEEFloat = 0

func renvoRTGParseTargetArg(name string) int {
return 0
}

func renvoRTGTargetValid(target int) bool {
return false
}
func renvoRTGTargetOS(target int) int {
return 0
}
func renvoRTGTargetIntBits(target int) int {
return 0
}

func renvoRTGTargetHasBuildTag(target int, tag string) bool {
return false
}

func renvoRTGTargetHasCapability(target int, capability string) bool {
return false
}

func renvoRTGProfileForTarget(target int) renvoTargetProfile {
return renvoTargetProfile{}
}

func renvoRTGDefaultArenaSize(target int) int {
return 0
}

func renvoRTGTargetBinding(target int) (string, string, int, bool) {
return renvoBuiltInTargetBinding(target)
}
