// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: target-projection/linux/amd64
// unit: native a38b01dc597533ebe065783c39a1961f0967982574948501c8263ee6af5580df
package main


func rtgBuiltinLinuxAmd64PackageLinuxObjectStaticCall(
	out *renvoAsm, importID int, wordCount int,
) {
	vectorMask := wordCount >> 8
	wordCount &= 255
	integerCount := 0
	vectorCount := 0
	for i := 0; i < wordCount; i++ {
		if vectorMask&(1<<i) != 0 {
			renvoAsmEmit8(out, 0x58)
			// Floating arguments already use their IEEE-754 binary64 bit
			// representation. Move those bits directly into the next SysV
			// vector register rather than treating them as the legacy
			// fixed-point value used by the old floating-point backend.
			renvoAsmEmit4(out, 0x66, 0x48, 0x0f, 0x6e)
			renvoAsmEmit8(out, 0xc0 | vectorCount<<3)
			vectorCount++
		} else {
			if integerCount == 0 {
				renvoAsmEmit8(out, 0x5f)
			} else if integerCount == 1 {
				renvoAsmEmit8(out, 0x5e)
			} else if integerCount == 2 {
				renvoAsmEmit8(out, 0x5a)
			} else if integerCount == 3 {
				renvoAsmEmit8(out, 0x59)
			} else if integerCount == 4 {
				renvoAsmEmit2(out, 0x41, 0x58)
			} else {
				renvoAsmEmit2(out, 0x41, 0x59)
			}
			integerCount++
		}
	}
	externalID := renvoAsmAddExternalImportName(out, out.staticImports[importID].name)
	// Expression evaluation can leave an odd number of words below the
	// arguments. Preserve that exact stack pointer while aligning the SysV
	// call boundary; the foreign callee may freely clobber r11.
	renvoAsmEmit3(out, 0x49, 0x89, 0xe3)
	renvoAsmEmit4(out, 0x48, 0x83, 0xe4, 0xf0)
	renvoAsmEmit4(out, 0x48, 0x83, 0xec, 0x10)
	renvoAsmEmit4(out, 0x4c, 0x89, 0x5c, 0x24)
	renvoAsmEmit8(out, 0x08)
	// Fixed callees ignore AL; variadic callees use it as the vector count.
	renvoAsmEmit8(out, 0xb0)
	renvoAsmEmit8(out, vectorCount)
	renvoAsmEmit8(out, 0xe8)
	at := len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at, externalID, 2)
	renvoAsmEmit4(out, 0x48, 0x8b, 0x64, 0x24)
	renvoAsmEmit8(out, 0x08)
}

func rtgBuiltinLinuxAmd64PackageLinuxPrepareReadWriteBuffer(out *renvoAsm) {
	renvoAsmEmit16(out, 0x5a51)
}

func rtgBuiltinLinuxAmd64PackageLinuxMoveOffsetArgument(out *renvoAsm) {
	renvoAsmEmit24(out, 0xc28949)
}

const renvoLinuxAmd64SysReadSeq = 0
const renvoLinuxAmd64SysWriteSeq = 1
const renvoLinuxAmd64SysOpen = 2
const renvoLinuxAmd64SysClose = 3
const renvoLinuxAmd64SysReadAt = 17
const renvoLinuxAmd64SysWriteAt = 18
const renvoLinuxAmd64SysFchmod = 91

func renvoAmd64AsmPrepareReadWriteBuf(a *renvoAsm) {
	renvoNonNil(a)
	renvoAsmCopyPrimaryToCallWord1(a)
	rtgBuiltinLinuxAmd64PackageLinuxPrepareReadWriteBuffer(a)
}

func renvoAmd64AsmMoveOffsetArg(a *renvoAsm) {
	renvoNonNil(a)
	rtgBuiltinLinuxAmd64PackageLinuxMoveOffsetArgument(a)
}

func compileLinuxAmd64(input []int, output int) int {
	return compileLinuxAmd64Arena(input, output, 0)
}

func compileLinuxAmd64Arena(input []int, output int, arenaSize int) int {
	renvoSetTarget(renvoTargetLinuxAmd64)
	return renvoCompileAmd64(input, output, arenaSize)
}

const renvoLinuxAmd64ArgsBSSSize = 32768
const renvoLinuxAmd64ArgsBSSAlignment = 16
const renvoLinuxAmd64EnvironmentBSSSize = 32768
const renvoLinuxAmd64EnvironmentBSSAlignment = 16
const renvoLinuxAmd64EnvironmentLengthBSSSize = 8
const renvoLinuxAmd64EnvironmentLengthBSSAlignment = 8

func renvoAsmBuildArgvEnvSlicesAmd64(a *renvoAsm, argsOff int, environmentOff int, environmentLengthOff int) {
	renvoNonNil(a)
	base := len(a.code)
	renvoAsmEmitText(a, "\x48\x8b\x04\x24\x49\x89\xc0\x4c\x8d\x4c\x24\x08\x4c\x8d\x15\x00\x00\x00\x00\x4d\x89\xd4\x4d\x31\xdb\x4d\x39\xc3\x7d\x22\x4b\x8b\x3c\xd9\x49\x89\x3a\x48\x31\xc0\x80\x3c\x07\x00\x74\x05\x48\xff\xc0\xeb\xf5\x49\x89\x42\x08\x49\x83\xc2\x10\x49\xff\xc3\xeb\xd9\x4c\x8d\x4c\x24\x08\x49\x83\x39\x00\x74\x06\x49\x83\xc1\x08\xeb\xf4\x49\x83\xc1\x08\x4c\x8d\x15\x00\x00\x00\x00\x4d\x31\xdb\x4b\x8b\x3c\xd9\x48\x83\xff\x00\x74\x1e\x49\x89\x3a\x48\x31\xc0\x80\x3c\x07\x00\x74\x05\x48\xff\xc0\xeb\xf5\x49\x89\x42\x08\x49\x83\xc2\x10\x49\xff\xc3\xeb\xd8\x4c\x89\xd8\x48\x89\x05\x00\x00\x00\x00\x4c\x89\xe7\x4c\x89\xc6\x4c\x89\xc2\x48\x8d\x05\x00\x00\x00\x00\x50\x59\x48\x8b\x05\x00\x00\x00\x00\x49\x89\xc0\x49\x89\xc1")
	renvoAsmAddAbsReloc(a, base+15, argsOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+88, environmentOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+141, environmentLengthOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+157, environmentOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+166, environmentLengthOff, renvoAbsBssReloc)
}


func renvoAsmImageObjectAmd64(emitter *renvoAsm) []byte {
	return renvoAsmImageRelocatableObjectAmd64(emitter)
}

func renvoAmd64EmitObjectStaticCall(out *renvoAsm, importID int, wordCount int) {
	rtgBuiltinLinuxAmd64PackageLinuxObjectStaticCall(out, importID, wordCount)
}

const renvoLinuxAmd64ELFMachine = 62

func renvoAsmImageAmd64(a *renvoAsm) []byte {
	renvoNonNil(a)
	renvoAsmPatch(a)
	loadFileSize := a.dataOffset + len(a.data)
	bssOffset := renvoAsmBssOffset(a)
	syscallTableSize := len(a.openbsdSyscalls) / 2 * 8
	if a.c.stripSymbols {
		oldCodeLen := len(a.code)
		var out []byte
		out = a.code
		if renvoFixedTarget == 0 && loadFileSize > cap(out) {
			out = renvoAppendUntil(out, loadFileSize)
		} else {
			renvoTruncBytes(&out, loadFileSize)
		}
		if renvoFixedTarget == 0 {
			copy(out[a.codeOffset:a.codeOffset+oldCodeLen], out[:oldCodeLen])
		} else {
			for i := oldCodeLen; i > 0; i-- {
				out[a.codeOffset+i-1] = out[i-1]
			}
		}
		var header []byte
		header = renvoAppendElfHeaderAmd64(header, a, a.codeOffset, loadFileSize, bssOffset, a.bssSize, 0, loadFileSize, syscallTableSize)
		if renvoFixedTarget == 0 {
			copy(out, header)
		} else {
			for i := 0; i < len(header); i++ {
				out[i] = header[i]
			}
		}
		pos := a.dataOffset
		if a.c.renvoTargetOS == renvoOSOpenBSD {
			out = renvoAppendOpenBSDSyscallTable(out, a)
		}
		if renvoFixedTarget == 0 {
			copy(out[pos:], a.data)
		} else {
			for i := 0; i < len(a.data); i++ {
				out[pos+i] = a.data[i]
			}
		}
		if renvoFixedTarget == 0 {
			return renvoAppendReplLinkTable(out, a)
		}
		return out
	}
	var sec renvoElfSymbolSections
	renvoBuildElfSymbolSections(a, 0, a.codeOffset, loadFileSize, &sec)
	finalSize := sec.shoff + 448
	syscallTableOff := finalSize
	finalSize += syscallTableSize
	out := make([]byte, finalSize)
	renvoTruncBytes(&out, 0)
	out = renvoAppendElfHeaderAmd64(out, a, a.codeOffset, loadFileSize, bssOffset, a.bssSize, sec.shoff, syscallTableOff, syscallTableSize)
	for i := 0; i < len(a.code); i++ {
		out = append(out, a.code[i])
	}
	out = renvoAppendUntil(out, a.dataOffset)
	for i := 0; i < len(a.data); i++ {
		out = append(out, a.data[i])
	}
	out = renvoAppendUntil(out, sec.symtabOff)
	for i := 0; i < len(sec.symtab); i++ {
		out = append(out, sec.symtab[i])
	}
	out = renvoAppendUntil(out, sec.strtabOff)
	for i := 0; i < len(sec.strtab); i++ {
		out = append(out, sec.strtab[i])
	}
	out = renvoAppendUntil(out, sec.shstrOff)
	for i := 0; i < len(sec.shstrtab); i++ {
		out = append(out, sec.shstrtab[i])
	}
	out = renvoAppendUntil(out, sec.shoff)
	out = renvoAppendElfSectionHeaders(out, &sec, a, 0)
	if a.c.renvoTargetOS == renvoOSOpenBSD {
		out = renvoAppendOpenBSDSyscallTable(out, a)
	}
	if renvoFixedTarget == 0 {
		return renvoAppendReplLinkTable(out, a)
	}
	return out
}

func renvoAppendElfHeaderAmd64(out []byte, a *renvoAsm, entryOff int, fileSize int, bssOffset int, bssSize int, shoff int, syscallTableOff int, syscallTableSize int) []byte {
	if a.c.renvoTargetOS == renvoOSOpenBSD {
		return renvoAppendOpenBSDElfHeaderAmd64(out, entryOff, a.dataOffset, fileSize, bssOffset, bssSize, shoff, syscallTableOff, syscallTableSize)
	}
	if a.c.renvoTargetOS == renvoOSNetBSD {
		return renvoAppendNetBSDElfHeaderAmd64(out, entryOff, fileSize, bssOffset, bssSize, shoff)
	}
	start := len(out)
	base := 0
	header := "\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x38\x00\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00"
	for i := 0; i < len(header); i++ {
		out = append(out, header[i])
	}
	out[start+18] = byte(renvoLinuxAmd64ELFMachine)
	out[start+19] = byte(renvoLinuxAmd64ELFMachine >> 8)
	if a.c.renvoTargetOS == renvoOSFreeBSD {
		out[start+7] = 9
	}
	// All Linux/amd64 references are RIP-relative. ET_DYN lets the kernel
	// randomize this self-contained image without a dynamic loader.
	out[start+16] = 3
	renvoPut32At(out, start+24, base+entryOff)
	renvoPut32At(out, start+40, shoff)
	renvoPut32At(out, start+80, base)
	renvoPut32At(out, start+88, base)
	if shoff != 0 {
		out[start+58] = 64
		out[start+60] = 7
		out[start+62] = 6
	}
	renvoPut32At(out, start+96, fileSize)
	renvoPut32At(out, start+104, fileSize)
	out = renvoAppendElf64LoadProgram(out, 6, bssOffset, base+bssOffset, 0, bssSize)
	return out
}

func renvoAppendElf64Program(out []byte, kind int, flags int, offset int, address int, fileSize int, memorySize int, alignment int) []byte {
	out = renvoAppend32(out, kind)
	out = renvoAppend32(out, flags)
	out = renvoAppend64(out, offset)
	out = renvoAppend64(out, address)
	out = renvoAppend64(out, address)
	out = renvoAppend64(out, fileSize)
	out = renvoAppend64(out, memorySize)
	return renvoAppend64(out, alignment)
}
