// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: target-projection/windows/386
// unit: native f0549659c43885e27ca718c0d8fb41e390ca75f6c9bbf9684815e2552d0b0059
package main


func renvoW386ExitSequence(out *renvoAsm, status int) {
	out.code = append(out.code, byte(0x50+status))
	renvoAsmEmit2(out, 0xff,0x15)
	at:=len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at,8,2)
}

func renvoW386CallImportSequence(out *renvoAsm, importID int, wordCount int) {
	renvoAsmEmit2(out, 0xff,0x15)
	at:=len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at,importID,2)
}

func renvoW386CallImport(out *renvoAsm, importID int) {
	renvoAsmEmit2(out, 0xff,0x15)
	at:=len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at,importID,2)
}

func renvoWin386EmitRuntimeChmod(out *renvoAsm) {
	eax:=0
	ecx:=1
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	renvoAsmEmit2(out, 0x6a,1)
	renvoAsmEmit2(out, 0x6a,0)
	renvoAsmEmit2(out, 0x6a,0)
	out.code = append(out.code, byte(0x53))
	renvoW386CallImport(out,5)
	renvo386TargetMoveImmediate(out,ecx,-1)
	renvo386TargetEncodeBinary(out,0x39,eax,ecx)
	renvo386AsmJccLabel(out,0x84,failed)
	renvo386TargetMoveImmediate(out,eax,0)
	renvo386TargetEncodeRelative(out,0xe9,done)
	renvoAsmMarkLabel(out, failed)
	renvo386TargetMoveImmediate(out,eax,-1)
	renvoAsmMarkLabel(out, done)
}

func renvoWin386EmitRuntimeClose(out *renvoAsm) {
	eax:=0
	failed:=renvoAsmNewLabel(out)
	done:=renvoAsmNewLabel(out)
	out.code = append(out.code, byte(0x53))
	renvoW386CallImport(out,2)
	renvo386TargetTest(out,eax,eax)
	renvo386AsmJccLabel(out,0x84,failed)
	renvo386TargetMoveImmediate(out,eax,0)
	renvo386TargetEncodeRelative(out,0xe9,done)
	renvoAsmMarkLabel(out, failed)
	renvo386TargetMoveImmediate(out,eax,-1)
	renvoAsmMarkLabel(out, done)
}

func renvoWin386EmitRuntimeOpen(out *renvoAsm) {
	renvoW386TranslateCreateFileFlags(out)
	renvoAsmEmit2(out, 0x6a,0)
	out.code = append(out.code, byte(0x68))
	renvoAsmEmit32(out, 0x80)
	out.code = append(out.code, byte(0x51))
	renvoAsmEmit2(out, 0x6a,0)
	renvoAsmEmit2(out, 0x6a,3)
	out.code = append(out.code, byte(0x52))
	out.code = append(out.code, byte(0x53))
	renvoW386CallImport(out,1)
}

func renvoW386TranslateCreateFileFlags(out *renvoAsm) {
	edx:=2
	ecx:=1
	notReadWrite:=renvoAsmNewLabel(out)
	accessDone:=renvoAsmNewLabel(out)
	noCreate:=renvoAsmNewLabel(out)
	createDone:=renvoAsmNewLabel(out)
	renvo386TargetMoveImmediate(out,edx,-2147483648)
	renvoAsmEmit2(out, 0xa8,2)
	renvo386AsmJccLabel(out,0x84,notReadWrite)
	renvo386TargetMoveImmediate(out,edx,-1073741824)
	renvo386TargetEncodeRelative(out,0xe9,accessDone)
	renvoAsmMarkLabel(out, notReadWrite)
	renvoAsmEmit2(out, 0xa8,1)
	renvo386AsmJccLabel(out,0x84,accessDone)
	renvo386TargetMoveImmediate(out,edx,0x40000000)
	renvoAsmMarkLabel(out, accessDone)
	renvo386TargetMoveImmediate(out,ecx,3)
	renvoAsmEmit2(out, 0xa8,64)
	renvo386AsmJccLabel(out,0x84,noCreate)
	renvo386TargetMoveImmediate(out,ecx,4)
	out.code = append(out.code, byte(0xa9))
	renvoAsmEmit32(out, 512)
	renvo386AsmJccLabel(out,0x84,createDone)
	renvo386TargetMoveImmediate(out,ecx,2)
	renvo386TargetEncodeRelative(out,0xe9,createDone)
	renvoAsmMarkLabel(out, noCreate)
	out.code = append(out.code, byte(0xa9))
	renvoAsmEmit32(out, 512)
	renvo386AsmJccLabel(out,0x84,createDone)
	renvo386TargetMoveImmediate(out,ecx,5)
	renvoAsmMarkLabel(out, createDone)
}

func renvoW386CompareImmediate(out *renvoAsm, register int, value int) {
	renvoAsmEmit8(out, 0x83)
	renvo386TargetEmitModRM(out,3,7,renvo386TargetRegisterLowBits(register))
	out.code = append(out.code, byte(int(value)))
}

func renvoW386PushRegister(out *renvoAsm, register int) {
	out.code = append(out.code, byte(0x50+register))
}

func renvoW386PopRegister(out *renvoAsm, register int) {
	out.code = append(out.code, byte(0x58+register))
}

func renvoW386PushImmediate(out *renvoAsm, value int) {
	renvoAsmEmit8(out, 0x6a)
	out.code = append(out.code, byte(int(value)))
}

func renvoW386PushBSSAddress(out *renvoAsm, offset int) {
	renvoAsmEmit8(out, 0x68)
	at:=len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at,offset,1)
}

func renvoW386StoreEAXBSS(out *renvoAsm, offset int) {
	renvoAsmEmit8(out, 0xa3)
	at:=len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at,offset,1)
}

func renvoW386LoadEAXBSS(out *renvoAsm, offset int) {
	renvoAsmEmit8(out, 0xa1)
	at:=len(out.code)
	renvoAsmEmit32(out, 0)
	renvoAsmAddAbsReloc(out, at,offset,1)
}

func renvoW386GetStandardHandle(out *renvoAsm, identifier int) {
	renvoW386PushImmediate(out,identifier)
	renvoW386CallImport(out,6)
	renvo386TargetMove(out,3,0)
}

func renvoW386ReadHandle(out *renvoAsm) {
	ready:=renvoAsmNewLabel(out)
	renvoW386CompareImmediate(out,3,0)
	renvo386AsmJccLabel(out,0x85,ready)
	renvoW386GetStandardHandle(out,-10)
	renvoAsmMarkLabel(out, ready)
}

func renvoW386WriteHandle(out *renvoAsm) {
	standardError:=renvoAsmNewLabel(out)
	ready:=renvoAsmNewLabel(out)
	renvoW386CompareImmediate(out,3,1)
	renvo386AsmJccLabel(out,0x85,standardError)
	renvoW386GetStandardHandle(out,-11)
	renvoAsmJmpLabel(out, ready)
	renvoAsmMarkLabel(out, standardError)
	renvoW386CompareImmediate(out,3,2)
	renvo386AsmJccLabel(out,0x85,ready)
	renvoW386GetStandardHandle(out,-12)
	renvoAsmMarkLabel(out, ready)
}

func renvoW386ReadWriteCall(out *renvoAsm, importID int, countOffset int) {
	renvoW386PushImmediate(out,0)
	renvoW386PushBSSAddress(out,countOffset)
	renvoW386PushRegister(out,2)
	renvoW386PushRegister(out,6)
	renvoW386PushRegister(out,3)
	renvoW386CallImport(out,importID)
}

func renvoW386RestorePosition(out *renvoAsm, countOffset int) {
	renvoW386PushImmediate(out,0)
	renvoW386PushImmediate(out,0)
	renvoW386LoadEAXBSS(out,countOffset+8)
	renvoW386PushRegister(out,0)
	renvoW386PushRegister(out,3)
	renvoW386CallImport(out,5)
}

func renvoW386RuntimeIOBody(out *renvoAsm, importID int, countOffset int) {
	sequential:=renvoAsmNewLabel(out)
	positionalFailed:=renvoAsmNewLabel(out)
	restore:=renvoAsmNewLabel(out)
	sequentialFailed:=renvoAsmNewLabel(out)
	renvoW386CompareImmediate(out,1,0)
	renvo386AsmJccLabel(out,0x8c,sequential)
	renvoW386PushRegister(out,1)
	renvoW386PushRegister(out,2)
	renvoW386PushImmediate(out,1)
	renvoW386PushImmediate(out,0)
	renvoW386PushImmediate(out,0)
	renvoW386PushRegister(out,3)
	renvoW386CallImport(out,5)
	renvoW386StoreEAXBSS(out,countOffset+8)
	renvoW386PopRegister(out,2)
	renvoW386PopRegister(out,1)
	renvoW386PushRegister(out,1)
	renvoW386PushRegister(out,2)
	renvoW386PushImmediate(out,0)
	renvoW386PushImmediate(out,0)
	renvoW386PushRegister(out,1)
	renvoW386PushRegister(out,3)
	renvoW386CallImport(out,5)
	renvoW386PopRegister(out,2)
	renvoW386PopRegister(out,1)
	renvoW386ReadWriteCall(out,importID,countOffset)
	renvoW386CompareImmediate(out,0,0)
	renvo386AsmJccLabel(out,0x84,positionalFailed)
	renvoW386LoadEAXBSS(out,countOffset)
	renvoAsmJmpLabel(out, restore)
	renvoAsmMarkLabel(out, positionalFailed)
	renvo386TargetMoveImmediate(out,0,-1)
	renvoAsmMarkLabel(out, restore)
	renvoW386StoreEAXBSS(out,countOffset)
	renvoW386RestorePosition(out,countOffset)
	renvoW386LoadEAXBSS(out,countOffset)
	renvoAsmEmit8(out, 0xc3)
	renvoAsmMarkLabel(out, sequential)
	renvoW386ReadWriteCall(out,importID,countOffset)
	renvoW386CompareImmediate(out,0,0)
	renvo386AsmJccLabel(out,0x84,sequentialFailed)
	renvoW386LoadEAXBSS(out,countOffset)
	renvoAsmEmit8(out, 0xc3)
	renvoAsmMarkLabel(out, sequentialFailed)
	renvo386TargetMoveImmediate(out,0,-1)
	renvoAsmEmit8(out, 0xc3)
}

func renvoW386ReadAtSequence(out *renvoAsm) {
	helper:=renvoAsmNewLabel(out)
	after:=renvoAsmNewLabel(out)
	countOffset:=renvoW386ReserveBSS(out,16,4)
	renvoAsmJmpLabel(out, after)
	renvoAsmMarkLabel(out, helper)
	renvoW386ReadHandle(out)
	renvoW386RuntimeIOBody(out,3,countOffset)
	renvoAsmMarkLabel(out, after)
	renvo386TargetCall(out,helper)
}

func renvoW386WriteAtSequence(out *renvoAsm) {
	helper:=renvoAsmNewLabel(out)
	after:=renvoAsmNewLabel(out)
	countOffset:=renvoW386ReserveBSS(out,16,4)
	renvoAsmJmpLabel(out, after)
	renvoAsmMarkLabel(out, helper)
	renvoW386WriteHandle(out)
	renvoW386RuntimeIOBody(out,4,countOffset)
	renvoAsmMarkLabel(out, after)
	renvo386TargetCall(out,helper)
}


func renvoW386ReserveBSS(a *renvoAsm, size int, alignment int) int {
	offset := renvoAlignValue(a.bssSize, alignment)
	a.bssSize = offset + size
	return offset
}

func renvoWin386EmitExit(a *renvoAsm) { renvoW386ExitSequence(a, 0) }

func renvoWin386CallImport(a *renvoAsm, importID int) {
	renvoW386CallImportSequence(a, importID, 0)
}

func renvoWin386EmitRuntimeReadAt(g *renvoLinearGen) {
	if g.winReadEmitted { renvoAsmCallLabel(&g.asm, g.winReadLabel); return }
	g.winReadEmitted = true
	g.winReadLabel = len(g.asm.labelPos)
	renvoW386ReadAtSequence(&g.asm)
}

func renvoWin386EmitRuntimeWriteAt(g *renvoLinearGen) {
	if g.winWriteEmitted { renvoAsmCallLabel(&g.asm, g.winWriteLabel); return }
	g.winWriteEmitted = true
	g.winWriteLabel = len(g.asm.labelPos)
	renvoW386WriteAtSequence(&g.asm)
}

func compileWindows386(input []int, output int) int {
	return compileWindows386Arena(input, output, 0)
}

func compileWindows386Arena(input []int, output int, arenaSize int) int {
	renvoSetTarget(renvoTargetWindows386)
	return renvoCompile386(input, output, arenaSize)
}

const renvoWindows386ArgsBSSSize = 32768
const renvoWindows386ArgsBSSAlignment = 16
const renvoWindows386ArgsTextBSSSize = 32768
const renvoWindows386ArgsTextBSSAlignment = 16
const renvoWindows386ArgsLengthBSSSize = 8
const renvoWindows386ArgsLengthBSSAlignment = 8
const renvoWindows386EnvironmentBSSSize = 32768
const renvoWindows386EnvironmentBSSAlignment = 16
const renvoWindows386EnvironmentLengthBSSSize = 8
const renvoWindows386EnvironmentLengthBSSAlignment = 8
func renvoAsmBuildWindowsArgvEnvSlices386(a *renvoAsm, argsOff int, argsTextOff int, argsLengthOff int, environmentOff int, environmentLengthOff int) {
	base := len(a.code)
	renvoAsmEmitText(a, "\xff\x15\x00\x00\x00\x00\x89\xc6\xbf\x00\x00\x00\x00\xb8\x00\x00\x00\x00\x89\xc2\x31\xdb\x80\x3e\x00\x0f\x84\x75\x00\x00\x00\x80\x3e\x20\x0f\x84\x09\x00\x00\x00\x80\x3e\x09\x0f\x85\x06\x00\x00\x00\x46\xe9\xdf\xff\xff\xff\x89\x17\x31\xc9\x31\xed\x8a\x06\x3c\x00\x0f\x84\x34\x00\x00\x00\x3c\x22\x0f\x85\x09\x00\x00\x00\x83\xf5\x01\x46\xe9\xe5\xff\xff\xff\x83\xfd\x00\x0f\x85\x10\x00\x00\x00\x3c\x20\x0f\x84\x12\x00\x00\x00\x3c\x09\x0f\x84\x0a\x00\x00\x00\x88\x02\x46\x42\x41\xe9\xc2\xff\xff\xff\xc6\x02\x00\x42\x89\x4f\x08\x83\xc7\x10\x43\x3c\x00\x0f\x84\x06\x00\x00\x00\x46\xe9\x82\xff\xff\xff\x89\xd8\xa3\x00\x00\x00\x00\xff\x15\x00\x00\x00\x00\x89\xc6\xbf\x00\x00\x00\x00\x31\xdb\x80\x3e\x00\x0f\x84\x23\x00\x00\x00\x89\x37\x31\xc9\x80\x3c\x0e\x00\x0f\x84\x06\x00\x00\x00\x41\xe9\xf0\xff\xff\xff\x89\x4f\x08\x01\xce\x46\x83\xc7\x10\x43\xe9\xd4\xff\xff\xff\x89\xd8\xa3\x00\x00\x00\x00\xbb\x00\x00\x00\x00\x8b\x35\x00\x00\x00\x00\x89\xf2\xb9\x00\x00\x00\x00\xa1\x00\x00\x00\x00\x89\xc7")
	renvoAsmAddWinImportReloc(a, base+2, 7)
	renvoAsmAddAbsReloc(a, base+9, argsOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+14, argsTextOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+151, argsLengthOff, renvoAbsBssReloc)
	renvoAsmAddWinImportReloc(a, base+157, 9)
	renvoAsmAddAbsReloc(a, base+164, environmentOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+217, environmentLengthOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+222, argsOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+228, argsLengthOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+235, environmentOff, renvoAbsBssReloc)
	renvoAsmAddAbsReloc(a, base+240, environmentLengthOff, renvoAbsBssReloc)
}


func renvoAsmImageWindows386(a *renvoAsm) []byte {
	for (a.codeOffset+len(a.code))%4 != 0 { a.code = append(a.code, 0) }
	textVirtualSize := len(a.code)
	textRawSize := renvoAlignValue(textVirtualSize, renvoWinFileAlign)
	dataRVA := renvoAlignValue(a.codeOffset+textVirtualSize, renvoWinSectionAlign)
	a.dataOffset = dataRVA
	var imports renvoWinImportLayout
	if renvoAsmHasWinImportRelocs(a) { renvoAppendWinImports(a, &imports) }
	renvoAsmPatchWindows(a, imports)
	dataRawSize := renvoAlignValue(len(a.data), renvoWinFileAlign)
	dataVirtualSize := len(a.data) + a.bssSize
	iatSize := 0
	if imports.kernelIATRVA != 0 { iatSize = (renvoWinImportFixedCount + 1) * imports.thunkSize }
	var out []byte
	out = renvoAppendPEHeader32WithContext(a.c, out, a.codeOffset, textRawSize, textVirtualSize, dataRVA, dataRawSize, dataVirtualSize, imports.importRVA, imports.importSize, imports.kernelIATRVA, iatSize)
	out = append(out, a.code...)
	out = renvoAppendUntil(out, renvoWinHeadersSize+textRawSize)
	out = append(out, a.data...)
	out = renvoAppendUntil(out, renvoWinHeadersSize+textRawSize+dataRawSize)
	if renvoFixedTarget == 0 && a.c.emitImage {
		for i := 0; i+2 < len(a.absRelocs); i += 3 {
			at := int(renvo_runtime_UnsafeInt32At(a.absRelocs, i)) & 2147483647
			out = renvoAppend32(out, a.codeOffset+at)
		}
		out = renvoAppend32(out, len(a.absRelocs)/3)
		out = append(out, 'R', 'B', 'R', '1')
		return renvoAppendReplLinkTable(out, a)
	}
	return out
}
