//go:build !renvo_prepared && !renvo_jvm_prepared

// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 2
// target: architecture-kernel
package main


type RTGRegister struct {
	Code int
	Valid bool
}

type RTGCondition struct {
	Code       int
	SetOpcode  byte
	JumpOpcode byte
}

type RTGSymbol struct {
	nameStart int
	nameEnd   int
	label     int
}

type RTGShiftDirection int

const (
	RTGShiftLeft RTGShiftDirection = 1
	RTGShiftRight RTGShiftDirection = 2
)

const RTGRelocationAbsoluteData = 0
const RTGRelocationAbsoluteBSS = 1
const RTGRelocationImport = 2
const RTGRelocationAbsoluteBSSEnd = 3
const RTGRuntimeRead = 1
const RTGRuntimeWrite = 2
const RTGRuntimeReadAt = 3
const RTGRuntimeWriteAt = 4
const RTGRuntimeOpen = 5
const RTGRuntimeClose = 6
const RTGRuntimeChmod = 7

const RTGScalarByte = 3
const RTGScalarInt8 = 7
const RTGScalarInt16 = 8
const RTGScalarInt32 = 9
const RTGScalarUint16 = 16
const RTGScalarUint32 = 17

var RTGNoRegister = RTGRegister{}

func renvoRTGLabelCode(code int) int {
	return code
}

func RTGSignedFits(value int64, bits int) bool {
	if bits <= 0 {
		return false
	}
	if bits >= 63 {
		return true
	}
	limit := int64(1) << (bits - 1)
	return value >= -limit && value < limit
}

func RTGUnsignedFits(value uint64, bits int) bool {
	if bits <= 0 {
		return false
	}
	if bits >= 63 {
		return true
	}
	return value < uint64(1)<<bits
}

func renvoRTGRel32(out *renvoAsm, label int) {
	at := len(out.code)
	renvoAsmEmit32(out, 0)
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2001
	}
}

func RTGLog2(value int) int {
	result := 0
	for value > 1 {
		value >>= 1
		result++
	}
	return result
}

type renvoRTGAddress struct {
	Target       int
	TargetValid  bool
	Kind         int
	Addend       int
	Base         RTGRegister
	Index        RTGRegister
	Displacement int
	Scale        int
}

func (out *renvoAsm) Byte(value byte) {
	renvoAsmEmit8(out, int(value))
}

func (out *renvoAsm) Uint32(value uint32) {
	renvoAsmEmit32(out, int(value))
}

func (out *renvoAsm) Uint64(value uint64) {
	renvoAsmEmit32(out, int(value))
	renvoAsmEmit32(out, int(value >> 32))
}

func (out *renvoAsm) PatchUint32(at int, value int) {
	renvoPut32At(out.code, at, value)
}

func (out *renvoAsm) NewLabel() int {
	return renvoAsmNewLabel(out)
}

func (out *renvoAsm) Mark(label int) {
	if label < 0 || label >= len(out.labelPos) || renvoAsmLabelPosition(out, label) >= 0 {
		if renvoRTGUnsupportedOperation == 0 {
			renvoRTGUnsupportedOperation = 2002
		}
		return
	}
	renvoAsmMarkLabel(out, label)
}

func (out *renvoAsm) Rel32(label int) {
	out.Rel32Addend(label, 0)
}

func (out *renvoAsm) Rel32Addend(label int, addend int) {
	at := len(out.code)
	renvoAsmEmit32(out, addend)
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2001
	}
}

func (out *renvoAsm) Reloc(label int) {
	if label >= 0 && len(out.code) >= 4 {
		renvoAsmAddReloc(out, len(out.code)-4, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2003
	}
}

func (out *renvoAsm) Patch() {
	renvoAsmPatch(out)
}

func (out *renvoAsm) Code() []byte {
	return out.code
}

func (out *renvoAsm) SetCode(value []byte) {
	out.code = value
}

func (out *renvoAsm) Data() []byte {
	return out.data
}

func (out *renvoAsm) SetData(value []byte) {
	out.data = value
}

func (out *renvoAsm) SetDataOffset(value int) {
	out.dataOffset = value
}

func (out *renvoAsm) BSSSize() int {
	return out.bssSize
}

func (out *renvoAsm) ReserveBSS(size int, alignment int) int {
	if alignment <= 0 {
		alignment = 1
	}
	offset := renvoAlignValue(out.bssSize, alignment)
	out.bssSize = offset + size
	return offset
}

func (out *renvoAsm) WindowsSubsystem() int {
	return out.c.windowsSubsystem
}

func (out *renvoAsm) StaticImportCount() int {
	return len(out.staticImports)
}

func (out *renvoAsm) StaticImportDLL(index int) string {
	return out.staticImports[index].dll
}

func (out *renvoAsm) StaticImportName(index int) string {
	return out.staticImports[index].name
}

func (out *renvoAsm) StaticCallParameterCount() int {
	return out.staticCallParamCount
}

func (out *renvoAsm) StaticCallParameterKind(index int) int {
	return int(out.staticCallParamKinds[index])
}

func (out *renvoAsm) StaticCallResultFloatRegister() int {
	return out.staticCallResultFloat
}

func (out *renvoAsm) DynamicImport(library string, name string) int {
	for i := 0; i < len(out.darwinImports); i++ {
		if out.darwinImports[i].dylib == library && out.darwinImports[i].name == name {
			out.darwinImports[i].used = true
			return i
		}
	}
	if renvoFixedTarget == 0 || renvoFixedTarget == renvoTargetDarwinArm64 {
		library = renvo_runtime_ArenaPersistString(library)
		name = renvo_runtime_ArenaPersistString(name)
	}
	label := renvoAsmNewLabel(out)
	out.darwinImports = append(out.darwinImports,
		renvoDarwinStaticImport{dylib: library, name: name, label: label, used: true})
	return len(out.darwinImports) - 1
}

func (out *renvoAsm) DynamicImportCount() int {
	return len(out.darwinImports)
}

func (out *renvoAsm) DynamicImportLibrary(index int) string {
	return out.darwinImports[index].dylib
}

func (out *renvoAsm) DynamicImportName(index int) string {
	return out.darwinImports[index].name
}

func (out *renvoAsm) DynamicImportLabel(index int) int {
	return out.darwinImports[index].label
}

func (out *renvoAsm) ExternalImport(name string) int {
	return renvoAsmAddExternalImportName(out, name)
}

func (out *renvoAsm) ExternalImportCount() int {
	return len(out.kernelImportOffsets) / 2
}

func (out *renvoAsm) ExternalImportName(index int) string {
	at := index * 2
	if at < 0 || at+1 >= len(out.kernelImportOffsets) {
		return ""
	}
	return string(out.kernelImportNames[
		out.kernelImportOffsets[at]:out.kernelImportOffsets[at+1]])
}

func (out *renvoAsm) KernelModuleName() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelModuleName
}

func (out *renvoAsm) KernelLicense() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelLicense
}

func (out *renvoAsm) KernelRelease() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelRelease
}

func (out *renvoAsm) KernelVersion() string {
	if out.c == nil || out.c.kernel == nil {
		return ""
	}
	return out.c.kernel.kernelVersion
}

func (out *renvoAsm) KernelBTF() []byte {
	if out.c == nil || out.c.kernel == nil {
		return nil
	}
	return out.c.kernel.kernelBTF
}

func (out *renvoAsm) KernelSymvers() []byte {
	if out.c == nil || out.c.kernel == nil {
		return nil
	}
	return out.c.kernel.kernelSymvers
}

func (out *renvoAsm) RelocationCount() int {
	return len(out.relocs) / 2
}

func (out *renvoAsm) RelocationAt(index int) (int, int) {
	at := index * 2
	return int(out.relocs[at]), int(out.relocs[at+1])
}

func (out *renvoAsm) RelocationOffset(index int) int {
	return int(out.relocs[index*2])
}

func (out *renvoAsm) RelocationLabel(index int) int {
	return int(out.relocs[index*2+1])
}

func (out *renvoAsm) RelocationWordCount() int {
	return len(out.relocs)
}

func (out *renvoAsm) RelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.relocs, index))
}

func (out *renvoAsm) AbsoluteRelocationCount() int {
	return len(out.absRelocs) / 3
}

func (out *renvoAsm) AbsoluteRelocationAt(index int) (int, int, int) {
	at := index * 3
	return int(out.absRelocs[at]), int(out.absRelocs[at+1]), int(out.absRelocs[at+2])
}

func (out *renvoAsm) AbsoluteRelocationOffset(index int) int {
	return int(out.absRelocs[index*3])
}

func (out *renvoAsm) AbsoluteRelocationAddend(index int) int {
	return int(out.absRelocs[index*3+1])
}

func (out *renvoAsm) AbsoluteRelocationKind(index int) int {
	return int(out.absRelocs[index*3+2])
}

func (out *renvoAsm) AbsoluteRelocationWordCount() int {
	return len(out.absRelocs)
}

func (out *renvoAsm) AbsoluteRelocationWord(index int) int {
	return int(renvo_runtime_UnsafeInt32At(out.absRelocs, index))
}

func (out *renvoAsm) LabelPosition(label int) int {
	return renvoAsmLabelPosition(out, label)
}

func (out *renvoAsm) SymbolCount() int {
	return len(out.symbols)
}

func (out *renvoAsm) SymbolPC(index int) int {
	return renvoAsmLabelPosition(out, out.symbols[index].label)
}

func (out *renvoAsm) SymbolNameEquals(index int, name string) bool {
	symbol := &out.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func (out *renvoAsm) SymbolNameLength(index int) int {
	symbol := &out.symbols[index]
	return symbol.nameEnd - symbol.nameStart
}

func (out *renvoAsm) SymbolNameByte(index int, offset int) byte {
	symbol := &out.symbols[index]
	return out.symbolName[symbol.nameStart+offset]
}

func (out *renvoAsm) Symbol(index int) *RTGSymbol {
	symbol := &out.symbols[index]
	return &RTGSymbol{nameStart: symbol.nameStart, nameEnd: symbol.nameEnd, label: symbol.label}
}

func (out *renvoAsm) SymbolNameByteAt(index int) byte {
	return out.symbolName[index]
}

func renvoRTGRelocationAt(out *renvoAsm, index int) (int, int) {
	at := index * 2
	return int(out.relocs[at]), int(out.relocs[at+1])
}

func renvoRTGAbsoluteRelocationAt(out *renvoAsm, index int) (int, int, int) {
	at := index * 3
	return int(out.absRelocs[at]), int(out.absRelocs[at+1]), int(out.absRelocs[at+2])
}

func renvoRTGSymbolPC(out *renvoAsm, index int) int {
	return renvoAsmLabelPosition(out, out.symbols[index].label)
}

func renvoRTGSymbolNameEquals(out *renvoAsm, index int, name string) bool {
	symbol := &out.symbols[index]
	if symbol.nameEnd-symbol.nameStart != len(name) {
		return false
	}
	for i := 0; i < len(name); i++ {
		if out.symbolName[symbol.nameStart+i] != name[i] {
			return false
		}
	}
	return true
}

func renvoRTGAddressValid(address renvoRTGAddress) bool {
	return address.TargetValid || address.Kind != 0
}

func renvoRTGAddressRel32Addend(out *renvoAsm, address renvoRTGAddress) {
	if address.Kind != 0 {
		at := len(out.code)
		renvoAsmEmit32(out, 0)
		renvoAsmAddAbsReloc(out, at, address.Addend, address.Kind-1)
		return
	}
	out.Rel32Addend(address.Target, address.Addend)
}

func renvoRTGAddressRelocAt(out *renvoAsm, address renvoRTGAddress, at int) {
	if address.Kind != 0 {
		renvoAsmAddAbsReloc(out, at, address.Addend, address.Kind-1)
		return
	}
	if address.TargetValid {
		renvoAsmAddReloc(out, at, address.Target)
	}
}

func renvoRTGLabelRelocAt(out *renvoAsm, label int, at int) {
	if label >= 0 {
		renvoAsmAddReloc(out, at, label)
	}
}

func renvoRTGDataAddress(offset int) renvoRTGAddress {
	return renvoRTGAddress{Kind: 1, Addend: offset}
}

func renvoRTGBSSAddress(offset int) renvoRTGAddress {
	return renvoRTGAddress{Kind: 2, Addend: offset}
}

func renvoRTGBSSEndAddress(alignment int) renvoRTGAddress {
	return renvoRTGAddress{Kind: 4, Addend: alignment}
}

func renvoRTGResolveAbsoluteRelocation(out *renvoAsm, kind int, addend int, dataAddress int, bssAddress int) (int, bool) {
	if kind == RTGRelocationAbsoluteData {
		return dataAddress + addend, true
	}
	if kind == RTGRelocationAbsoluteBSS {
		return bssAddress + addend, true
	}
	if kind == RTGRelocationAbsoluteBSSEnd {
		if addend <= 0 {
			addend = 1
		}
		return bssAddress + renvoAlignValue(out.bssSize, addend), true
	}
	return 0, false
}

func renvoRTGByte(out *renvoAsm, value byte) {
	renvoAsmEmit8(out, int(value))
}

func renvoRTGUint32(out *renvoAsm, value int) {
	renvoAsmEmit32(out, value)
}

func renvoRTGUint64(out *renvoAsm, value uint64) {
	renvoAsmEmit32(out, int(value))
	renvoAsmEmit32(out, int(value >> 32))
}

func renvoRTGPatchUint32(out *renvoAsm, at int, value int) {
	renvoPut32At(out.code, at, value)
}

func renvoRTGNewLabel(out *renvoAsm) int {
	return renvoAsmNewLabel(out)
}

func renvoRTGMark(out *renvoAsm, label int) {
	if label < 0 || label >= len(out.labelPos) || renvoAsmLabelPosition(out, label) >= 0 {
		if renvoRTGUnsupportedOperation == 0 {
			renvoRTGUnsupportedOperation = 2002
		}
		return
	}
	renvoAsmMarkLabel(out, label)
}

func renvoRTGReloc(out *renvoAsm, label int) {
	if label >= 0 && len(out.code) >= 4 {
		renvoAsmAddReloc(out, len(out.code)-4, label)
	} else if renvoRTGUnsupportedOperation == 0 {
		renvoRTGUnsupportedOperation = 2003
	}
}

var renvoRTGUnsupportedOperation int

func renvoRTGDirectMove(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 1 }
}

func renvoRTGDirectAddress(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 2 }
}

func renvoRTGDirectLoadNative(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 3 }
}

func renvoRTGDirectLoadI32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 4 }
}

func renvoRTGDirectLoadU32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 5 }
}

func renvoRTGDirectLoadI16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 6 }
}

func renvoRTGDirectLoadU16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 7 }
}

func renvoRTGDirectLoadI8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 8 }
}

func renvoRTGDirectLoadU8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 9 }
}

func renvoRTGDirectStoreNative(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 10 }
}

func renvoRTGDirectStoreU32(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 11 }
}

func renvoRTGDirectStoreU16(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 12 }
}

func renvoRTGDirectStoreU8(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 13 }
}

func renvoRTGDirectAdd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 14 }
}

func renvoRTGDirectSubtract(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 15 }
}

func renvoRTGDirectMultiply(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 16 }
}

func renvoRTGDirectBitAnd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 17 }
}

func renvoRTGDirectBitOr(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 18 }
}

func renvoRTGDirectBitXor(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 19 }
}

func renvoRTGDirectCompare(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 20 }
}

func renvoRTGDirectTest(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 21 }
}

func renvoRTGDirectIncrement(out *renvoAsm, operand RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 22 }
}

func renvoRTGDirectDecrement(out *renvoAsm, operand RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 23 }
}

func renvoRTGDirectShiftLeftImmediate(out *renvoAsm, destination RTGRegister, value byte) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 24 }
}

func renvoRTGDirectShiftRightUnsignedImmediate(out *renvoAsm, destination RTGRegister, value byte) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 25 }
}

func renvoRTGDirectShiftRightSignedImmediate(out *renvoAsm, destination RTGRegister, value byte) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 26 }
}

func renvoRTGDirectCall(out *renvoAsm, label int) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 27 }
}

func renvoRTGDirectCallIndirect(out *renvoAsm, operand RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 28 }
}

func renvoRTGDirectJump(out *renvoAsm, label int) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 29 }
}

func renvoRTGDirectJumpCondition(out *renvoAsm, condition RTGCondition, label int) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 30 }
}

func renvoRTGDirectSetCondition(out *renvoAsm, condition RTGCondition, source RTGRegister) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 31 }
}

func renvoRTGDirectReturn(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 32 }
}

func renvoRTGDirectLeave(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 33 }
}

func renvoRTGDirectHostSyscall(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 34 }
}

func renvoRTGDirectMoveImmediate(out *renvoAsm, destination RTGRegister, value int64) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 35 }
}

func renvoRTGDirectVariableShift(out *renvoAsm, direction RTGShiftDirection, signed bool) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 36 }
}

func renvoRTGDirectSignedDivide(out *renvoAsm, remainder bool) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 37 }
}

func renvoRTGDirectCopyBytes(out *renvoAsm) {
	if renvoRTGUnsupportedOperation == 0 { renvoRTGUnsupportedOperation = 38 }
}

var renvoRTGPrimary = RTGNoRegister
var renvoRTGSecondary = RTGNoRegister
var renvoRTGTertiary = RTGNoRegister
var renvoRTGScratch = RTGNoRegister
var renvoRTGCopyDestination = RTGNoRegister
var renvoRTGCopySource = RTGNoRegister
var renvoRTGCopyCount = RTGNoRegister
var renvoRTGStack = RTGNoRegister
var renvoRTGFrame = RTGNoRegister
var renvoRTGCallWord0 = RTGNoRegister
var renvoRTGCallWord1 = RTGNoRegister
var renvoRTGCallWord2 = RTGNoRegister
var renvoRTGCallWord3 = RTGNoRegister
var renvoRTGCallWord4 = RTGNoRegister
var renvoRTGCallWord5 = RTGNoRegister
var renvoRTGObjectArgument0 = RTGNoRegister
var renvoRTGObjectArgument1 = RTGNoRegister
var renvoRTGObjectArgument2 = RTGNoRegister
var renvoRTGObjectArgument3 = RTGNoRegister
var renvoRTGObjectArgument4 = RTGNoRegister
var renvoRTGObjectArgument5 = RTGNoRegister
var renvoRTGObjectArgument6 = RTGNoRegister
var renvoRTGObjectArgument7 = RTGNoRegister
var renvoRTGSyscallNumber = RTGNoRegister
var renvoRTGSyscallWord0 = RTGNoRegister
var renvoRTGSyscallWord1 = RTGNoRegister
var renvoRTGSyscallWord2 = RTGNoRegister
var renvoRTGSyscallWord3 = RTGNoRegister
var renvoRTGSyscallWord4 = RTGNoRegister
var renvoRTGSyscallWord5 = RTGNoRegister
var renvoRTGSyscallResult = RTGNoRegister
const renvoRTGStackWordBytes = 0
func renvoRTGConditionFromSetcc(setcc int) RTGCondition { return RTGCondition{} }
func renvoRTGPatchRelocations(out *renvoAsm) {}
func renvoRTGFrameStart(out *renvoAsm) int { return -1 }
func renvoRTGFrameFinish(out *renvoAsm, framePatch int, stackUsed int) {}
func renvoRTGABIPushRegister(out *renvoAsm, source RTGRegister) bool { return false }
func renvoRTGABIPushImmediate(out *renvoAsm, value int) bool { return false }
func renvoRTGABIPopRegister(out *renvoAsm, destination RTGRegister) bool { return false }
func renvoRTGABILoadFrame(out *renvoAsm, destination RTGRegister, offset int) bool { return false }
func renvoRTGABIStoreFrame(out *renvoAsm, offset int, source RTGRegister) bool { return false }
func renvoRTGABIAddressFrame(out *renvoAsm, destination RTGRegister, offset int) bool { return false }
func renvoRTGABIStoreParamWord(out *renvoAsm, word int, offset int) bool { return false }
func renvoRTGABICallWordCount(out *renvoAsm, label int, wordCount int) bool { return false }
func renvoRTGMarkLabel(out *renvoAsm, label int) {}
func renvoRTGFunctionStart(out *renvoAsm, label int) {}
func renvoRTGFunctionFinish(out *renvoAsm) {}
func renvoRTGEmitJITCall(out *renvoAsm, entry RTGRegister, stackTop RTGRegister, argsData RTGRegister, argsLen RTGRegister, envData RTGRegister, envLen RTGRegister) bool { return false }
func renvoRTGEmitUnsignedDivide(out *renvoAsm, remainder bool) bool { return false }
const renvoRTGCodeOffset = 0
func renvoRTGImage(out *renvoAsm) []byte { return nil }
func renvoRTGKernelImage(out *renvoAsm, initLabel int, exitLabel int) []byte { return nil }
const renvoRTGEntryStateBytes = 0
func renvoRTGEmitEntryStart(out *renvoAsm, stateOffset int) bool { return true }
func renvoRTGEmitEntry(out *renvoAsm, parameterCount int, stateOffset int) bool { return parameterCount == 0 }
func renvoRTGKernelEntryPrologue(out *renvoAsm) {}
func renvoRTGKernelEntryEpilogue(out *renvoAsm) {}
func renvoRTGKernelCallbackAddress(out *renvoAsm, label int) {}
func renvoRTGEmitExit(out *renvoAsm, status RTGRegister) bool { return false }
func renvoRTGEmitStaticCall(out *renvoAsm, importID int, wordCount int) bool { return false }
func renvoRTGEmitRuntimeOperation(out *renvoAsm, operation int) bool { return false }

const renvoRTGPreparedOS = 0
const renvoRTGPreparedIntBits = 0
const renvoRTGPreparedMaxAlign = 0
const renvoRTGPreparedKernelModule = 0
const renvoRTGPreparedObject = 0
const renvoRTGPreparedSysVX8664 = 0
const renvoRTGPreparedFunctionSymbols = 0
const renvoRTGPreparedIEEEFloat = 0

func renvoRTGParseTargetArg(name string) int {
return 0
}

func renvoRTGTargetValid(target int) bool {
return false
}
func renvoRTGTargetOS(target int) int {
return 0
}
func renvoRTGTargetIntBits(target int) int {
return 0
}

func renvoRTGTargetHasBuildTag(target int, tag string) bool {
return false
}

func renvoRTGTargetHasCapability(target int, capability string) bool {
return false
}

func renvoRTGProfileForTarget(target int) renvoTargetProfile {
return renvoTargetProfile{}
}

func renvoRTGDefaultArenaSize(target int) int {
return 0
}

func renvoRTGTargetBinding(target int) (string, string, int, bool) {
return renvoBuiltInTargetBinding(target)
}

func renvoAsmStoreByteMemSecondaryTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStoreByteMemSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStoreByteMemSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStoreByteMemSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStoreByteMemSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStoreByteMemSecondaryTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmIncTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerIncTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerIncTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerIncTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerIncTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerIncTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmIncPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerIncPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerIncPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerIncPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerIncPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerIncPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmRet(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerRet(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerRet(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerRet(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerRet(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerRet(a)
return
}
a.patchFailed = true
}

func renvoAsmLeave(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLeave(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLeave(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLeave(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLeave(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLeave(a)
return
}
a.patchFailed = true
}

func renvoAsmCopyPrimaryToCallWord0(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopyPrimaryToCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopyPrimaryToCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopyPrimaryToCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopyPrimaryToCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopyPrimaryToCallWord0(a)
return
}
a.patchFailed = true
}

func renvoAsmCopySecondaryToPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopySecondaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopySecondaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopySecondaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopySecondaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopySecondaryToPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmCopyPrimaryToCallWord1(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopyPrimaryToCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopyPrimaryToCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopyPrimaryToCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopyPrimaryToCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopyPrimaryToCallWord1(a)
return
}
a.patchFailed = true
}

func renvoAsmAddSecondaryTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerAddSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerAddSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerAddSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerAddSecondaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerAddSecondaryTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmLoadBytePrimaryIndexTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadBytePrimaryIndexTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadBytePrimaryIndexTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadBytePrimaryIndexTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadBytePrimaryIndexTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadBytePrimaryIndexTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmStorePrimaryMemSecondaryTertiary8(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStorePrimaryMemSecondaryTertiary8(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStorePrimaryMemSecondaryTertiary8(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStorePrimaryMemSecondaryTertiary8(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStorePrimaryMemSecondaryTertiary8(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStorePrimaryMemSecondaryTertiary8(a)
return
}
a.patchFailed = true
}

func renvoAsmIncMemSecondary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerIncMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerIncMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerIncMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerIncMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerIncMemSecondary(a)
return
}
a.patchFailed = true
}

func renvoAsmDecMemSecondary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerDecMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerDecMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerDecMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerDecMemSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerDecMemSecondary(a)
return
}
a.patchFailed = true
}

func renvoAsmBoolNotPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerBoolNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerBoolNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerBoolNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerBoolNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerBoolNotPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmBitwiseNotPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerBitwiseNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerBitwiseNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerBitwiseNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerBitwiseNotPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerBitwiseNotPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmAddPrimaryTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerAddPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerAddPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerAddPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerAddPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerAddPrimaryTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmSubPrimaryTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerSubPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerSubPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerSubPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerSubPrimaryTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerSubPrimaryTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmPopPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPopPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPopPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPopPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPopPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPopPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmPopSecondary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPopSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPopSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPopSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPopSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPopSecondary(a)
return
}
a.patchFailed = true
}

func renvoAsmPopTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPopTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPopTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPopTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPopTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPopTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmCopyPrimaryToSecondary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopyPrimaryToSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopyPrimaryToSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopyPrimaryToSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopyPrimaryToSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopyPrimaryToSecondary(a)
return
}
a.patchFailed = true
}

func renvoAsmCopyPrimaryToTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopyPrimaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopyPrimaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopyPrimaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopyPrimaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopyPrimaryToTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmCopySecondaryToTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopySecondaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopySecondaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopySecondaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopySecondaryToTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopySecondaryToTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmCopyTertiaryToPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCopyTertiaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCopyTertiaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCopyTertiaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCopyTertiaryToPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCopyTertiaryToPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmPushPrimary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPushPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPushPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPushPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPushPrimary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPushPrimary(a)
return
}
a.patchFailed = true
}

func renvoAsmPushSecondary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPushSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPushSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPushSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPushSecondary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPushSecondary(a)
return
}
a.patchFailed = true
}

func renvoAsmPushTertiary(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPushTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPushTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPushTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPushTertiary(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPushTertiary(a)
return
}
a.patchFailed = true
}

func renvoAsmPushImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPushImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPushImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPushImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPushImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPushImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmStorePrimaryStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStorePrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStorePrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStorePrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStorePrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStorePrimaryStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmStoreSecondaryStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStoreSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStoreSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStoreSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStoreSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStoreSecondaryStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmLoadPrimaryStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadPrimaryStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmIncStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerIncStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerIncStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerIncStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerIncStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerIncStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmDecStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerDecStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerDecStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerDecStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerDecStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerDecStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmAddressPrimaryStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerAddressPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerAddressPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerAddressPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerAddressPrimaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerAddressPrimaryStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmAddressCallWord0Stack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerAddressCallWord0Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerAddressCallWord0Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerAddressCallWord0Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerAddressCallWord0Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerAddressCallWord0Stack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmAddressCallWord1Stack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerAddressCallWord1Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerAddressCallWord1Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerAddressCallWord1Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerAddressCallWord1Stack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerAddressCallWord1Stack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmLoadSecondaryStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadSecondaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadSecondaryStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmLoadTertiaryStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadTertiaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadTertiaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadTertiaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadTertiaryStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadTertiaryStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmStoreSliceStack(a *renvoAsm, offset int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStoreSliceStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStoreSliceStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStoreSliceStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStoreSliceStack(a, offset)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStoreSliceStack(a, offset)
return
}
a.patchFailed = true
}

func renvoAsmMulTertiaryImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerMulTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerMulTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerMulTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerMulTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerMulTertiaryImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmCallLabel(a *renvoAsm, label int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCallLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCallLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCallLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCallLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCallLabel(a, label)
return
}
a.patchFailed = true
}

func renvoAsmJmpLabel(a *renvoAsm, label int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerJmpLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerJmpLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerJmpLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerJmpLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerJmpLabel(a, label)
return
}
a.patchFailed = true
}

func renvoAsmJzLabel(a *renvoAsm, label int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerJzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerJzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerJzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerJzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerJzLabel(a, label)
return
}
a.patchFailed = true
}

func renvoAsmJnzLabel(a *renvoAsm, label int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerJnzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerJnzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerJnzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerJnzLabel(a, label)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerJnzLabel(a, label)
return
}
a.patchFailed = true
}

func renvoAsmSecondaryImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerSecondaryImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmPrimaryDataAddr(a *renvoAsm, dataOff int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPrimaryDataAddr(a, dataOff)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPrimaryDataAddr(a, dataOff)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPrimaryDataAddr(a, dataOff)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPrimaryDataAddr(a, dataOff)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPrimaryDataAddr(a, dataOff)
return
}
a.patchFailed = true
}

func renvoAsmPrimaryBssAddr(a *renvoAsm, bssOff int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPrimaryBssAddr(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPrimaryBssAddr(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPrimaryBssAddr(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPrimaryBssAddr(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPrimaryBssAddr(a, bssOff)
return
}
a.patchFailed = true
}

func renvoAsmLoadPrimaryBss(a *renvoAsm, bssOff int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadPrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadPrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadPrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadPrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadPrimaryBss(a, bssOff)
return
}
a.patchFailed = true
}

func renvoAsmStorePrimaryBss(a *renvoAsm, bssOff int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStorePrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStorePrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStorePrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStorePrimaryBss(a, bssOff)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStorePrimaryBss(a, bssOff)
return
}
a.patchFailed = true
}

func renvoAsmPopCallWord0(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPopCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPopCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPopCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPopCallWord0(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPopCallWord0(a)
return
}
a.patchFailed = true
}

func renvoAsmPopCallWord1(a *renvoAsm) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerPopCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerPopCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerPopCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerPopCallWord1(a)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerPopCallWord1(a)
return
}
a.patchFailed = true
}

func renvoAsmAddSecondaryImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerAddSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerAddSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerAddSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerAddSecondaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerAddSecondaryImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmLoadQwordPrimaryIndexTertiaryDisp(a *renvoAsm, disp int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadQwordPrimaryIndexTertiaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadQwordPrimaryIndexTertiaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadQwordPrimaryIndexTertiaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadQwordPrimaryIndexTertiaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadQwordPrimaryIndexTertiaryDisp(a, disp)
return
}
a.patchFailed = true
}

func renvoAsmLoadPrimaryMemSecondaryDisp(a *renvoAsm, disp int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadPrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadPrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadPrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadPrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadPrimaryMemSecondaryDisp(a, disp)
return
}
a.patchFailed = true
}

func renvoAsmLoadPrimaryMemSecondaryDispSize(a *renvoAsm, disp int, size int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadPrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadPrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadPrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadPrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadPrimaryMemSecondaryDispSize(a, disp, size)
return
}
a.patchFailed = true
}

func renvoAsmLoadPrimaryIndexTertiarySize(a *renvoAsm, size int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerLoadPrimaryIndexTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerLoadPrimaryIndexTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerLoadPrimaryIndexTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerLoadPrimaryIndexTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerLoadPrimaryIndexTertiarySize(a, size)
return
}
a.patchFailed = true
}

func renvoAsmStorePrimaryMemSecondaryDisp(a *renvoAsm, disp int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStorePrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStorePrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStorePrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStorePrimaryMemSecondaryDisp(a, disp)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStorePrimaryMemSecondaryDisp(a, disp)
return
}
a.patchFailed = true
}

func renvoAsmStorePrimaryMemSecondaryDispSize(a *renvoAsm, disp int, size int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStorePrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStorePrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStorePrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStorePrimaryMemSecondaryDispSize(a, disp, size)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStorePrimaryMemSecondaryDispSize(a, disp, size)
return
}
a.patchFailed = true
}

func renvoAsmNormalizePrimaryForKind(a *renvoAsm, kind int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerNormalizePrimaryForKind(a, kind)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerNormalizePrimaryForKind(a, kind)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerNormalizePrimaryForKind(a, kind)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerNormalizePrimaryForKind(a, kind)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerNormalizePrimaryForKind(a, kind)
return
}
a.patchFailed = true
}

func renvoAsmCmpPrimaryImm8(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCmpPrimaryImm8(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCmpPrimaryImm8(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCmpPrimaryImm8(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCmpPrimaryImm8(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCmpPrimaryImm8(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmCmpPrimaryImm8Discard(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCmpPrimaryImm8Discard(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCmpPrimaryImm8Discard(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCmpPrimaryImm8Discard(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCmpPrimaryImm8Discard(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCmpPrimaryImm8Discard(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmShlTertiaryImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerShlTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerShlTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerShlTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerShlTertiaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerShlTertiaryImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmShlPrimaryImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerShlPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerShlPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerShlPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerShlPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerShlPrimaryImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmSarPrimaryImm(a *renvoAsm, imm int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerSarPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerSarPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerSarPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerSarPrimaryImm(a, imm)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerSarPrimaryImm(a, imm)
return
}
a.patchFailed = true
}

func renvoAsmDivLeftTertiaryRightPrimary(a *renvoAsm, mod bool) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerDivLeftTertiaryRightPrimary(a, mod)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerDivLeftTertiaryRightPrimary(a, mod)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerDivLeftTertiaryRightPrimary(a, mod)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerDivLeftTertiaryRightPrimary(a, mod)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerDivLeftTertiaryRightPrimary(a, mod)
return
}
a.patchFailed = true
}

func renvoAsmCmpTertiaryPrimarySet(a *renvoAsm, setcc int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCmpTertiaryPrimarySet(a, setcc)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCmpTertiaryPrimarySet(a, setcc)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCmpTertiaryPrimarySet(a, setcc)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCmpTertiaryPrimarySet(a, setcc)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCmpTertiaryPrimarySet(a, setcc)
return
}
a.patchFailed = true
}

func renvoAsmStorePrimaryMemSecondaryTertiarySize(a *renvoAsm, size int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerStorePrimaryMemSecondaryTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerStorePrimaryMemSecondaryTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerStorePrimaryMemSecondaryTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerStorePrimaryMemSecondaryTertiarySize(a, size)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerStorePrimaryMemSecondaryTertiarySize(a, size)
return
}
a.patchFailed = true
}

func renvoAsmCmpTertiaryPrimaryJump(a *renvoAsm, setcc int, label int) {
renvoNonNil(a)
if a.c.renvoTargetArch == renvoArchAmd64 {
renvoAmd64CompilerCmpTertiaryPrimaryJump(a, setcc, label)
return
}
if a.c.renvoTargetArch == renvoArch386 {
renvo386CompilerCmpTertiaryPrimaryJump(a, setcc, label)
return
}
if a.c.renvoTargetArch == renvoArchAarch64 {
renvoAarch64CompilerCmpTertiaryPrimaryJump(a, setcc, label)
return
}
if a.c.renvoTargetArch == renvoArchArm {
renvoArmCompilerCmpTertiaryPrimaryJump(a, setcc, label)
return
}
if a.c.renvoTargetArch == renvoArchWasm32 {
renvoWasm32CompilerCmpTertiaryPrimaryJump(a, setcc, label)
return
}
a.patchFailed = true
}
