// Code generated by go generate ./internal/targetinfo; DO NOT EDIT.

package main

const renvoSupportedTargets = "linux/amd64, linux/386, linux/aarch64, linux/arm, windows/amd64, windows/386, windows/arm64, darwin/arm64, wasi/wasm32, vm/vm32, freebsd/amd64, openbsd/amd64, netbsd/amd64"

func renvoParseTargetArg(target string) int {
	if target == "linux/amd64" {
		return renvoTargetLinuxAmd64
	}
	if target == "linux/386" {
		return renvoTargetLinux386
	}
	if target == "linux/aarch64" {
		return renvoTargetLinuxAarch64
	}
	if target == "linux/arm" {
		return renvoTargetLinuxArm
	}
	if target == "windows/amd64" {
		return renvoTargetWindowsAmd64
	}
	if target == "windows/386" {
		return renvoTargetWindows386
	}
	if target == "wasi/wasm32" {
		return renvoTargetWasiWasm32
	}
	if target == "darwin/arm64" {
		return renvoTargetDarwinArm64
	}
	if target == "linux-kernel/amd64" {
		return renvoTargetLinuxKernelAmd64
	}
	if target == "windows/arm64" {
		return renvoTargetWindowsArm64
	}
	if target == "vm/vm32" {
		return renvoTargetVM32
	}
	if target == "freebsd/amd64" {
		return renvoTargetFreeBSDAmd64
	}
	if target == "openbsd/amd64" {
		return renvoTargetOpenBSDAmd64
	}
	if target == "netbsd/amd64" {
		return renvoTargetNetBSDAmd64
	}
	return renvoRTGParseTargetArg(target)
}

func renvoBuiltInTargetBinding(target int) (string, string, int, bool) {
	if target == renvoTargetLinuxAmd64 {
		return "linux/amd64", "wӷUA65\v\xa9_\xf6\xe3\x86g\xd6UJp\x1cþ\x18\x1f\xb3\xe9\"7T\u0380#/", 3, true
	}
	if target == renvoTargetLinux386 {
		return "linux/386", "t\x9cx\xa5\x14\x03\xd8\x17#}L\xb1\v\x9f\x0eIr\x1b\x94\x12\x11=\x04\x00\x93\xc0|\xeac\x81\xcf\xd8", 3, true
	}
	if target == renvoTargetLinuxAarch64 {
		return "linux/aarch64", "\xed\x18,ԡ\x90\xd6\x12\xe4|1bp\xf3\xa9\xa8G\x99\x8b\xae\x8a=r\xa6k\xfc\x19\xf0H9\x8b\xc9", 3, true
	}
	if target == renvoTargetLinuxArm {
		return "linux/arm", "@l\xe0\x00\x18\xa6R9~\x94\xf7m\x19\xa8\xb68\x9f\xfb/,\xe59Z\b*\xb2N\x19\xe2\xe6\x16\x8b", 3, true
	}
	if target == renvoTargetWindowsAmd64 {
		return "windows/amd64", "\brl\x8fX\xa0\vOFa\xb4n¬\xa7\x1dSd\xc4\xc7\n`ޚp\x19Gh\x05\xa2\x95D", 3, true
	}
	if target == renvoTargetWindows386 {
		return "windows/386", "q\xf3\v\xf8\x94iN\x98\x11S\xbe\\g\xbe\xda\x18T\xe2\x0ev坘dϴí\xf8d\xf0\xed", 3, true
	}
	if target == renvoTargetWasiWasm32 {
		return "wasi/wasm32", "\xaa\x04J\xab}#\x99\nD\x93~\xd0\x12\r\xb2\xdfQ\xcd\xd5[(\r\xda_\xfe\x97\x8f\x88N\x8f\x1al", 3, true
	}
	if target == renvoTargetDarwinArm64 {
		return "darwin/arm64", "\x03%\xfd\x81\xb3\xa9\u2ef9\xefM\xc5u\xee#\x82=\x15\fJB\xe6z@n&3\xe3\xfb\xef;\x8f", 3, true
	}
	if target == renvoTargetLinuxKernelAmd64 {
		return "linux-kernel/amd64", ":\x03\x91\xe9,\xa4\x02\a\x05u\x89uI0\x9dC\xab\x8b\xf2\xc7/\xd0HlĴ\xbd\x19\xfa$\xbd\xf2", 3, true
	}
	if target == renvoTargetWindowsArm64 {
		return "windows/arm64", "\x8d\r\xe8\xa0ת>\xa4C6N\xde8X\xdb\xc0\x81>+\xa5\xdb\xcc3K\xb1\x9a\xaf\xb1\x85~\x18j", 3, true
	}
	if target == renvoTargetVM32 {
		return "vm/vm32", "\xd14\xe6\x10E\x15\x88\xc6\xc5F\x15D\x8d\x86RNo{Ke\x00\xa6\x7f\x8f\xdct\x17(\x95\xdb\xea\xc7", 3, true
	}
	if target == renvoTargetFreeBSDAmd64 {
		return "freebsd/amd64", "Gc\x90\xde\xec\xff樒\xa0\x12;\xa1k\x11\x1dkt-\vj\xf5\x15U2J\aH7\xc8\xf1\x8a", 3, true
	}
	if target == renvoTargetOpenBSDAmd64 {
		return "openbsd/amd64", "AF\xb94콵q\x01\xe2J\x98\xb2G\x84\xcdot\x97\xbf\xf3)\xf5\tGE\x90\xac\x0e\xd27\x9e", 3, true
	}
	if target == renvoTargetNetBSDAmd64 {
		return "netbsd/amd64", "\x04:܊\xef\x8c\x15n1\xbf])̆\xda\xf9i\x03\xebb\xcc?ݩ\x12\x9d\xe7\xf2\xe0O2\x13", 3, true
	}
	return "", "", 0, false
}
