//go:build !renvo

// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: contract/arm
// unit: arm 3afac86c26beca41e9b203ac6de4123c1ceaa3403c876bc65139dee8921decb6
package main


var rtgArmR0 = RTGRegister{Code:0, Valid:true}

var rtgArmR1 = RTGRegister{Code:1, Valid:true}

var rtgArmR2 = RTGRegister{Code:2, Valid:true}

var rtgArmR3 = RTGRegister{Code:3, Valid:true}

var rtgArmR4 = RTGRegister{Code:4, Valid:true}

var rtgArmR5 = RTGRegister{Code:5, Valid:true}

var rtgArmR6 = RTGRegister{Code:6, Valid:true}

var rtgArmR7 = RTGRegister{Code:7, Valid:true}

var rtgArmR8 = RTGRegister{Code:8, Valid:true}

var rtgArmR9 = RTGRegister{Code:9, Valid:true}

var rtgArmR10 = RTGRegister{Code:10, Valid:true}

var rtgArmR11 = RTGRegister{Code:11, Valid:true}

var rtgArmR12 = RTGRegister{Code:12, Valid:true}

var rtgArmR13 = RTGRegister{Code:13, Valid:true}

var rtgArmR14 = RTGRegister{Code:14, Valid:true}

var rtgArmR15 = RTGRegister{Code:15, Valid:true}
var rtgArmPrimary = rtgArmR0
var rtgArmSecondary = rtgArmR1
var rtgArmTertiary = rtgArmR2
var rtgArmSystem = rtgArmR7
var rtgArmScratch = rtgArmR9
var rtgArmScratch2 = rtgArmR10
var rtgArmAddress = rtgArmR12
var rtgArmCopyDestination = rtgArmR3
var rtgArmCopySource = rtgArmR4
var rtgArmCopyCount = rtgArmR1
var rtgArmFrame = rtgArmR11
var rtgArmStack = rtgArmR13
var rtgArmLink = rtgArmR14

var rtgArmEQ = RTGCondition{Code:0}

var rtgArmNE = RTGCondition{Code:1}

var rtgArmUGE = RTGCondition{Code:2}

var rtgArmULT = RTGCondition{Code:3}

var rtgArmUGT = RTGCondition{Code:8}

var rtgArmULE = RTGCondition{Code:9}

var rtgArmSGE = RTGCondition{Code:10}

var rtgArmSLT = RTGCondition{Code:11}

var rtgArmSGT = RTGCondition{Code:12}

var rtgArmSLE = RTGCondition{Code:13}

func rtgArmArmMove(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmMovRegReg(out, destination.Code, source.Code)
}
func rtgArmArmEmitAddress(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	if renvoRTGAddressValid(address) {
		part := address.Addend & 65535
		at := len(out.code)
		renvoArmAsmEmit(out,
			0xe3000000|((part&0xf000)<<4)|
				(destination.Code<<12)|(part&0x0fff))
		part = (address.Addend >> 16) & 65535
		renvoArmAsmEmit(out,
			0xe3400000|((part&0xf000)<<4)|
				(destination.Code<<12)|(part&0x0fff))
		renvoArmAsmEmit(out,
			0xe08f0000|(destination.Code<<12)|destination.Code)
		renvoRTGAddressRelocAt(out, address, at)
		return
	}
	base := address.Base.Code
	if address.Index.Valid {
		shift := 0
		if address.Scale == 2 {
			shift = 1
		} else if address.Scale == 4 {
			shift = 2
		} else if address.Scale == 8 {
			shift = 3
		}
		renvoArmAsmAddRegRegShift(
			out, destination.Code, base, address.Index.Code, shift)
		base = destination.Code
	}
	renvoArmAsmAddRegImm(
		out, destination.Code, base, address.Displacement)
}
func rtgArmArmMemoryAddress(
	out *renvoAsm, address renvoRTGAddress, size int,
) renvoRTGAddress {
	limit := 4095
	if size == 2 {
		limit = 255
	}
	if renvoRTGAddressValid(address) || address.Index.Valid ||
		address.Displacement < -limit ||
		address.Displacement > limit {
		rtgArmArmEmitAddress(out, rtgArmAddress, address)
		return renvoRTGAddress{Base: rtgArmAddress}
	}
	return address
}
func rtgArmArmLoadExtra(
	out *renvoAsm,
	destination RTGRegister,
	address renvoRTGAddress,
	opcode int,
) {
	address = rtgArmArmMemoryAddress(out, address, 2)
	displacement := address.Displacement
	up := 0x00800000
	if displacement < 0 {
		up = 0
		displacement = -displacement
	}
	renvoArmAsmEmit(out,
		opcode|up|(address.Base.Code<<16)|
			(destination.Code<<12)|
			((displacement&0xf0)<<4)|(displacement&0x0f))
}
func rtgArmArmLoadNative(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	address = rtgArmArmMemoryAddress(out, address, 4)
	renvoArmAsmLoadRegMem(out, destination.Code,
		address.Base.Code, address.Displacement, 4)
}
func rtgArmArmLoadI32(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	rtgArmArmLoadNative(out, destination, address)
}
func rtgArmArmLoadU32(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	rtgArmArmLoadNative(out, destination, address)
}
func rtgArmArmLoadI16(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	rtgArmArmLoadExtra(out, destination, address, 0xe15000f0)
}
func rtgArmArmLoadU16(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	rtgArmArmLoadExtra(out, destination, address, 0xe15000b0)
}
func rtgArmArmLoadI8(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	rtgArmArmLoadExtra(out, destination, address, 0xe15000d0)
}
func rtgArmArmLoadU8(
	out *renvoAsm, destination RTGRegister, address renvoRTGAddress,
) {
	address = rtgArmArmMemoryAddress(out, address, 1)
	renvoArmAsmLoadRegMem(out, destination.Code,
		address.Base.Code, address.Displacement, 1)
}
func rtgArmArmStoreWidth(
	out *renvoAsm,
	address renvoRTGAddress,
	source RTGRegister,
	size int,
) {
	address = rtgArmArmMemoryAddress(out, address, size)
	renvoArmAsmStoreRegMem(out, source.Code,
		address.Base.Code, address.Displacement, size)
}
func rtgArmArmStoreNative(
	out *renvoAsm, address renvoRTGAddress, source RTGRegister,
) {
	rtgArmArmStoreWidth(out, address, source, 4)
}
func rtgArmArmStoreU32(
	out *renvoAsm, address renvoRTGAddress, source RTGRegister,
) {
	rtgArmArmStoreWidth(out, address, source, 4)
}
func rtgArmArmStoreU16(
	out *renvoAsm, address renvoRTGAddress, source RTGRegister,
) {
	rtgArmArmStoreWidth(out, address, source, 2)
}
func rtgArmArmStoreU8(
	out *renvoAsm, address renvoRTGAddress, source RTGRegister,
) {
	rtgArmArmStoreWidth(out, address, source, 1)
}
func rtgArmArmAdd(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmAddRegReg(
		out, destination.Code, destination.Code, source.Code)
}
func rtgArmArmSubtract(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmSubRegReg(
		out, destination.Code, destination.Code, source.Code)
}
func rtgArmArmMultiply(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmMulRegReg(
		out, destination.Code, destination.Code, source.Code)
}
func rtgArmArmBitAnd(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmEmit(out,
		0xe0000000|(destination.Code<<16)|
			(destination.Code<<12)|source.Code)
}
func rtgArmArmBitOr(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmEmit(out,
		0xe1800000|(destination.Code<<16)|
			(destination.Code<<12)|source.Code)
}
func rtgArmArmBitXor(
	out *renvoAsm, destination RTGRegister, source RTGRegister,
) {
	renvoArmAsmEmit(out,
		0xe0200000|(destination.Code<<16)|
			(destination.Code<<12)|source.Code)
}
func rtgArmArmCompare(
	out *renvoAsm, left RTGRegister, right RTGRegister,
) {
	renvoArmAsmCmpRegReg(out, left.Code, right.Code)
}
func rtgArmArmTest(
	out *renvoAsm, left RTGRegister, right RTGRegister,
) {
	renvoArmAsmEmit(
		out, 0xe1100000|(left.Code<<16)|right.Code)
}
func rtgArmArmIncrement(out *renvoAsm, operand RTGRegister) {
	renvoArmAsmAddRegImm(out, operand.Code, operand.Code, 1)
}
func rtgArmArmDecrement(out *renvoAsm, operand RTGRegister) {
	renvoArmAsmAddRegImm(out, operand.Code, operand.Code, -1)
}
func rtgArmArmShiftImmediate(
	out *renvoAsm,
	operand RTGRegister,
	value byte,
	kind int,
) {
	renvoArmAsmEmit(out,
		0xe1a00000|(operand.Code<<12)|
			((int(value)&31)<<7)|kind|operand.Code)
}
func rtgArmArmShiftLeftImmediate(
	out *renvoAsm, operand RTGRegister, value byte,
) {
	rtgArmArmShiftImmediate(out, operand, value, 0)
}
func rtgArmArmShiftRightUnsignedImmediate(
	out *renvoAsm, operand RTGRegister, value byte,
) {
	rtgArmArmShiftImmediate(out, operand, value, 0x20)
}
func rtgArmArmShiftRightSignedImmediate(
	out *renvoAsm, operand RTGRegister, value byte,
) {
	rtgArmArmShiftImmediate(out, operand, value, 0x40)
}
func rtgArmArmCall(out *renvoAsm, label int) {
	renvoArmAsmEmit(out, 0xeb000000)
	renvoRTGReloc(out, label)
}
func rtgArmArmCallIndirect(out *renvoAsm, operand RTGRegister) {
	renvoArmAsmEmit(out, 0xe12fff30|operand.Code)
}
func rtgArmArmJump(out *renvoAsm, label int) {
	renvoArmAsmEmit(out, 0xea000000)
	renvoRTGReloc(out, label)
}
func rtgArmArmJumpCondition(
	out *renvoAsm, condition RTGCondition, label int,
) {
	renvoArmAsmEmit(
		out, (condition.Code<<28)|0x0a000000)
	renvoRTGReloc(out, label)
}
func rtgArmArmSetCondition(
	out *renvoAsm,
	condition RTGCondition,
	destination RTGRegister,
) {
	renvoArmAsmEmit(out, 0xe3a00000|(destination.Code<<12))
	renvoArmAsmEmit(out,
		(condition.Code<<28)|0x03a00001|
			(destination.Code<<12))
}
func rtgArmArmReturn(out *renvoAsm) {
	renvoArmAsmRet(out)
}
func rtgArmArmLeave(out *renvoAsm) {
	renvoArmAsmLeave(out)
}
func rtgArmArmHostSyscall(out *renvoAsm) {
	renvoArmAsmSyscall(out)
}
func rtgArmArmMoveImmediate(
	out *renvoAsm, destination RTGRegister, value int64,
) {
	renvoArmAsmMovRegImm(out, destination.Code, int(value))
}
func rtgArmArmVariableShift(
	out *renvoAsm, direction RTGShiftDirection, signed bool,
) {
	kind := 0x20
	if direction == RTGShiftLeft {
		kind = 0
	} else if signed {
		kind = 0x40
	}
	renvoArmAsmEmit(out,
		0xe1a00010|(0<<12)|
			(0<<8)|kind|2)
}
func rtgArmArmSignedDivide(out *renvoAsm, remainder bool) {
	renvoArmAsmMovRegReg(
		out, 9, 0)
	renvoArmAsmEmit(out,
		0xe710f010|(0<<16)|
			(0<<8)|2)
	if remainder {
		renvoArmAsmEmit(out,
			0xe0600090|(2<<12)|
				(9<<8)|0)
	}
}
func rtgArmArmCopyBytes(out *renvoAsm) {
	destination := rtgArmR3
	source := rtgArmR4
	count := rtgArmSecondary
	value := rtgArmScratch2
	forward := out.NewLabel()
	forwardLoop := out.NewLabel()
	backwardLoop := out.NewLabel()
	done := out.NewLabel()
	rtgArmArmCompare(out, destination, source)
	rtgArmArmJumpCondition(out, RTGCondition{Code: 9}, forward)
	rtgArmArmEmitAddress(out, rtgArmScratch, renvoRTGAddress{
		Base: source, Index: count, Scale: 1,
	})
	rtgArmArmCompare(out, destination, rtgArmScratch)
	rtgArmArmJumpCondition(out, RTGCondition{Code: 2}, forward)
	rtgArmArmEmitAddress(out, source, renvoRTGAddress{
		Base: source, Index: count, Scale: 1, Displacement: -1,
	})
	rtgArmArmEmitAddress(out, destination, renvoRTGAddress{
		Base: destination, Index: count, Scale: 1, Displacement: -1,
	})
	out.Mark(backwardLoop)
	renvoArmAsmCmpRegImm(out, count.Code, 0)
	rtgArmArmJumpCondition(out, RTGCondition{Code: 0}, done)
	rtgArmArmLoadU8(out, value, renvoRTGAddress{Base: source})
	rtgArmArmStoreU8(out, renvoRTGAddress{Base: destination}, value)
	rtgArmArmDecrement(out, source)
	rtgArmArmDecrement(out, destination)
	rtgArmArmDecrement(out, count)
	rtgArmArmJump(out, backwardLoop)
	out.Mark(forward)
	out.Mark(forwardLoop)
	renvoArmAsmCmpRegImm(out, count.Code, 0)
	rtgArmArmJumpCondition(out, RTGCondition{Code: 0}, done)
	rtgArmArmLoadU8(out, value, renvoRTGAddress{Base: source})
	rtgArmArmStoreU8(out, renvoRTGAddress{Base: destination}, value)
	rtgArmArmIncrement(out, source)
	rtgArmArmIncrement(out, destination)
	rtgArmArmDecrement(out, count)
	rtgArmArmJump(out, forwardLoop)
	out.Mark(done)
}
func rtgArmArmPatchRelocations(out *renvoAsm) {
	for i := 0; i < len(out.relocs) / 2; i++ {
		at := int(out.relocs[i*2])
		label := int(out.relocs[i*2+1])
		target := renvoAsmLabelPosition(out,label)
		if at < 0 || at+4 > len(out.code) || target < 0 {
			continue
		}
		insn := renvoGet32At(out.code, at)
		if (insn & 0x0e000000) == 0x0a000000 {
			displacement := target - (at + 8)
			renvoPut32At(out.code,at,
				(insn&0xff000000)|
					((displacement/4)&0x00ffffff))
		} else if (insn & 0xfff00000) == 0xe3000000 {
			highInsn := renvoGet32At(out.code, at+4)
			addend := insn & 0x0fff
			addend = addend | ((insn >> 4) & 0xf000)
			addend = addend | ((highInsn & 0x0fff) << 16)
			addend = addend | ((highInsn & 0x000f0000) << 12)
			if (addend & 0x80000000) != 0 {
				addend = addend - 4294967296
			}
			value := target + addend - (at + 16)
			low := value & 65535
			high := (value >> 16) & 65535
			renvoPut32At(out.code,at,
				(insn&0xfff0f000)|
					((low&0xf000)<<4)|(low&0x0fff))
			renvoPut32At(out.code,at+4,
				(highInsn&0xfff0f000)|
					((high&0xf000)<<4)|(high&0x0fff))
		}
	}
}

// Generated direct_emitter_v1 binding for move.
// Effects: reads=source; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgArmDirectMove(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmMove(out, destination, source)
}

// Generated direct_emitter_v1 binding for address.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough; relocation=address
func rtgArmDirectAddress(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmEmitAddress(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.native.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:native:target; control=fallthrough; relocation=address
func rtgArmDirectLoadNative(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadNative(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.i32.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:32:signed:target; control=fallthrough; relocation=address
func rtgArmDirectLoadI32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadI32(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.u32.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:32:unsigned:target; control=fallthrough; relocation=address
func rtgArmDirectLoadU32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadU32(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.i16.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:16:signed:target; control=fallthrough; relocation=address
func rtgArmDirectLoadI16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadI16(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.u16.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:16:unsigned:target; control=fallthrough; relocation=address
func rtgArmDirectLoadU16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadU16(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.i8.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:8:signed:1; control=fallthrough; relocation=address
func rtgArmDirectLoadI8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadI8(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.u8.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:8:unsigned:1; control=fallthrough; relocation=address
func rtgArmDirectLoadU8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgArmArmLoadU8(out, destination, address)
}

// Generated direct_emitter_v1 binding for store.native.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:native:target; control=fallthrough; relocation=address
func rtgArmDirectStoreNative(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgArmArmStoreNative(out, address, source)
}

// Generated direct_emitter_v1 binding for store.u32.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:32:target; control=fallthrough; relocation=address
func rtgArmDirectStoreU32(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgArmArmStoreU32(out, address, source)
}

// Generated direct_emitter_v1 binding for store.u16.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:16:target; control=fallthrough; relocation=address
func rtgArmDirectStoreU16(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgArmArmStoreU16(out, address, source)
}

// Generated direct_emitter_v1 binding for store.u8.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:8:1; control=fallthrough; relocation=address
func rtgArmDirectStoreU8(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgArmArmStoreU8(out, address, source)
}

// Generated direct_emitter_v1 binding for add.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectAdd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmAdd(out, destination, source)
}

// Generated direct_emitter_v1 binding for subtract.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectSubtract(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmSubtract(out, destination, source)
}

// Generated direct_emitter_v1 binding for multiply.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectMultiply(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmMultiply(out, destination, source)
}

// Generated direct_emitter_v1 binding for bit_and.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectBitAnd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmBitAnd(out, destination, source)
}

// Generated direct_emitter_v1 binding for bit_or.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectBitOr(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmBitOr(out, destination, source)
}

// Generated direct_emitter_v1 binding for bit_xor.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectBitXor(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgArmArmBitXor(out, destination, source)
}

// Generated direct_emitter_v1 binding for compare.
// Effects: reads=left,right; writes=flags; clobbers=flags; preserves=all_locations; control=fallthrough
func rtgArmDirectCompare(out *renvoAsm, left RTGRegister, right RTGRegister) {
	rtgArmArmCompare(out, left, right)
}

// Generated direct_emitter_v1 binding for test.
// Effects: reads=left,right; writes=flags; clobbers=flags; preserves=all_locations; control=fallthrough
func rtgArmDirectTest(out *renvoAsm, left RTGRegister, right RTGRegister) {
	rtgArmArmTest(out, left, right)
}

// Generated direct_emitter_v1 binding for increment.
// Effects: reads=operand; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectIncrement(out *renvoAsm, operand RTGRegister) {
	rtgArmArmIncrement(out, operand)
}

// Generated direct_emitter_v1 binding for decrement.
// Effects: reads=operand; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectDecrement(out *renvoAsm, operand RTGRegister) {
	rtgArmArmDecrement(out, operand)
}

// Generated direct_emitter_v1 binding for shift_left_immediate.
// Effects: reads=operand,value; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectShiftLeftImmediate(out *renvoAsm, operand RTGRegister, value byte) {
	rtgArmArmShiftLeftImmediate(out, operand, value)
}

// Generated direct_emitter_v1 binding for shift_right_unsigned_immediate.
// Effects: reads=operand,value; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectShiftRightUnsignedImmediate(out *renvoAsm, operand RTGRegister, value byte) {
	rtgArmArmShiftRightUnsignedImmediate(out, operand, value)
}

// Generated direct_emitter_v1 binding for shift_right_signed_immediate.
// Effects: reads=operand,value; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectShiftRightSignedImmediate(out *renvoAsm, operand RTGRegister, value byte) {
	rtgArmArmShiftRightSignedImmediate(out, operand, value)
}

// Generated direct_emitter_v1 binding for call.
// Effects: reads=label,call_words,stack; writes=primary,secondary,tertiary,stack; clobbers=call_clobbered,flags; preserves=callee_saved; control=call; relocation=label
func rtgArmDirectCall(out *renvoAsm, label int) {
	rtgArmArmCall(out, label)
}

// Generated direct_emitter_v1 binding for call_indirect.
// Effects: reads=operand,call_words,stack; writes=primary,secondary,tertiary,stack; clobbers=call_clobbered,flags; preserves=callee_saved; control=call_indirect; requires=indirect_call; rejection=permitted
func rtgArmDirectCallIndirect(out *renvoAsm, operand RTGRegister) {
	rtgArmArmCallIndirect(out, operand)
}

// Generated direct_emitter_v1 binding for jump.
// Effects: reads=label; writes=-; clobbers=-; preserves=all_locations; control=branch; relocation=label
func rtgArmDirectJump(out *renvoAsm, label int) {
	rtgArmArmJump(out, label)
}

// Generated direct_emitter_v1 binding for jump_condition.
// Effects: reads=condition,label; writes=-; clobbers=-; preserves=all_locations; control=conditional_branch; relocation=label
func rtgArmDirectJumpCondition(out *renvoAsm, condition RTGCondition, label int) {
	rtgArmArmJumpCondition(out, condition, label)
}

// Generated direct_emitter_v1 binding for set_condition.
// Effects: reads=condition,flags; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgArmDirectSetCondition(out *renvoAsm, condition RTGCondition, destination RTGRegister) {
	rtgArmArmSetCondition(out, condition, destination)
}

// Generated direct_emitter_v1 binding for return.
// Effects: reads=stack; writes=-; clobbers=-; preserves=all_locations; control=return
func rtgArmDirectReturn(out *renvoAsm) {
	rtgArmArmReturn(out)
}

// Generated direct_emitter_v1 binding for leave.
// Effects: reads=frame,stack; writes=frame,stack; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgArmDirectLeave(out *renvoAsm) {
	rtgArmArmLeave(out)
}

// Generated direct_emitter_v1 binding for host_syscall.
// Effects: reads=syscall_number,syscall_words; writes=syscall_result; clobbers=syscall_clobbered,flags; preserves=callee_saved; memory=host; control=call; requires=host_syscall
func rtgArmDirectHostSyscall(out *renvoAsm) {
	rtgArmArmHostSyscall(out)
}

// Generated direct_emitter_v1 binding for move_immediate.
// Effects: reads=value; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgArmDirectMoveImmediate(out *renvoAsm, destination RTGRegister, value int64) {
	rtgArmArmMoveImmediate(out, destination, value)
}

// Generated direct_emitter_v1 binding for variable_shift.
// Effects: reads=primary,tertiary; writes=primary; clobbers=tertiary,flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectVariableShift(out *renvoAsm, direction RTGShiftDirection, signed bool) {
	rtgArmArmVariableShift(out, direction, signed)
}

// Generated direct_emitter_v1 binding for signed_divide.
// Effects: reads=primary,tertiary; writes=primary; clobbers=secondary,flags; preserves=all_except_writes; control=fallthrough
func rtgArmDirectSignedDivide(out *renvoAsm, remainder bool) {
	rtgArmArmSignedDivide(out, remainder)
}

// Generated direct_emitter_v1 binding for copy_bytes.
// Effects: reads=copy_destination,copy_source,copy_count,memory; writes=memory; clobbers=copy_destination,copy_source,copy_count,flags; preserves=other_locations; memory=read_write:8:1; control=fallthrough
func rtgArmDirectCopyBytes(out *renvoAsm) {
	rtgArmArmCopyBytes(out)
}

// Generated definition-owned relocation finalizer.
func rtgArmPatchRelocations(out *renvoAsm) {
	rtgArmArmPatchRelocations(out)
}
