//go:build !renvo

// Code generated by Renvo RTG; DO NOT EDIT.
// generator: 1
// target: contract/x86_64
// unit: x86_64 d704a8b62791f9b43ba1f8b67631d3d9abad19d49ccc49ad7533d0d20ca1f514
package main


var rtgX8664RAX = RTGRegister{Code:0, Valid:true}

var rtgX8664RCX = RTGRegister{Code:1, Valid:true}

var rtgX8664RDX = RTGRegister{Code:2, Valid:true}

var rtgX8664RBX = RTGRegister{Code:3, Valid:true}

var rtgX8664RSP = RTGRegister{Code:4, Valid:true}

var rtgX8664RBP = RTGRegister{Code:5, Valid:true}

var rtgX8664RSI = RTGRegister{Code:6, Valid:true}

var rtgX8664RDI = RTGRegister{Code:7, Valid:true}

var rtgX8664R8 = RTGRegister{Code:8, Valid:true}

var rtgX8664R9 = RTGRegister{Code:9, Valid:true}

var rtgX8664R10 = RTGRegister{Code:10, Valid:true}

var rtgX8664R11 = RTGRegister{Code:11, Valid:true}

var rtgX8664R12 = RTGRegister{Code:12, Valid:true}

var rtgX8664R13 = RTGRegister{Code:13, Valid:true}

var rtgX8664R14 = RTGRegister{Code:14, Valid:true}

var rtgX8664R15 = RTGRegister{Code:15, Valid:true}
var rtgX8664Primary = rtgX8664RAX
var rtgX8664Secondary = rtgX8664RDX
var rtgX8664Tertiary = rtgX8664RCX
var rtgX8664Scratch = rtgX8664R10
var rtgX8664DivisionScratch = rtgX8664RBX
var rtgX8664CopyDestination = rtgX8664RDI
var rtgX8664CopySource = rtgX8664RSI
var rtgX8664CopyCount = rtgX8664RCX
var rtgX8664Stack = rtgX8664RSP
var rtgX8664Frame = rtgX8664RBP

var rtgX8664EQ = RTGCondition{Code:0x94, SetOpcode:0x94, JumpOpcode:0x84}

var rtgX8664NE = RTGCondition{Code:0x95, SetOpcode:0x95, JumpOpcode:0x85}

var rtgX8664SLT = RTGCondition{Code:0x9c, SetOpcode:0x9c, JumpOpcode:0x8c}

var rtgX8664SGE = RTGCondition{Code:0x9d, SetOpcode:0x9d, JumpOpcode:0x8d}

var rtgX8664SLE = RTGCondition{Code:0x9e, SetOpcode:0x9e, JumpOpcode:0x8e}

var rtgX8664SGT = RTGCondition{Code:0x9f, SetOpcode:0x9f, JumpOpcode:0x8f}

var rtgX8664ULT = RTGCondition{Code:0x92, SetOpcode:0x92, JumpOpcode:0x82}

var rtgX8664UGE = RTGCondition{Code:0x93, SetOpcode:0x93, JumpOpcode:0x83}

var rtgX8664ULE = RTGCondition{Code:0x96, SetOpcode:0x96, JumpOpcode:0x86}

var rtgX8664UGT = RTGCondition{Code:0x97, SetOpcode:0x97, JumpOpcode:0x87}

func rtgX8664X86Low3(reg RTGRegister) byte {
	return byte(reg.Code & 7)
}
func rtgX8664X86High(reg RTGRegister) byte {
	return byte(reg.Code>>3) & 1
}
func rtgX8664X86Opcode(out *renvoAsm, opcode uint32) {
	if opcode > 0xff {
		out.code = append(out.code, byte(int(opcode >> 8)))
	}
	out.code = append(out.code, byte(int(opcode)))
}
func rtgX8664X86REX(out *renvoAsm, wide bool, reg RTGRegister, index RTGRegister, base RTGRegister, byteRegister RTGRegister) {
	w := byte(0)
	if wide {
		w = 1
	}
	r := rtgX8664X86High(reg)
	x := byte(0)
	if index.Valid {
		x = rtgX8664X86High(index)
	}
	b := byte(0)
	if base.Valid {
		b = rtgX8664X86High(base)
	}
	needsByteREX := byteRegister.Valid && byteRegister.Code >= 4
	if w != 0 || r != 0 || x != 0 || b != 0 || needsByteREX {
		out.code = append(out.code, byte(int(0x40 | w<<3 | r<<2 | x<<1 | b)))
	}
}
func rtgX8664X86ModRM(out *renvoAsm, mode byte, reg byte, rm byte) {
	out.code = append(out.code, byte(int(mode<<6 | (reg&7)<<3 | rm&7)))
}
func rtgX8664X86Memory(out *renvoAsm, reg byte, address renvoRTGAddress) {
	if renvoRTGAddressValid(address) {
		rtgX8664X86ModRM(out, 0, reg, 5)
		renvoRTGAddressRel32Addend(out, address)
		return
	}
	base := address.Base
	index := address.Index
	displacement := address.Displacement
	needsSIB := index.Valid || rtgX8664X86Low3(base) == 4
	mode := byte(0)
	if displacement != 0 || rtgX8664X86Low3(base) == 5 {
		mode = 2
		if RTGSignedFits(int64(displacement), 8) {
			mode = 1
		}
	}
	if needsSIB {
		rtgX8664X86ModRM(out, mode, reg, 4)
		indexCode := byte(4)
		if index.Valid {
			indexCode = rtgX8664X86Low3(index)
		}
		out.code = append(out.code, byte(int(byte(RTGLog2(address.Scale))<<6 | indexCode<<3 | rtgX8664X86Low3(base))))
	} else {
		rtgX8664X86ModRM(out, mode, reg, rtgX8664X86Low3(base))
	}
	if mode == 1 {
		out.code = append(out.code, byte(displacement))
	} else if mode == 2 {
		renvoAsmEmit32(out, displacement)
	}
}
func rtgX8664X86RRRM(out *renvoAsm, opcode uint32, destination RTGRegister, source RTGRegister, width int) {
	if width == 16 {
		renvoAsmEmit8(out,0x66)
	}
	byteRegister := RTGNoRegister
	if width == 8 {
		byteRegister = source
	}
	rtgX8664X86REX(out, width == 64, source, RTGNoRegister, destination, byteRegister)
	rtgX8664X86Opcode(out, opcode)
	rtgX8664X86ModRM(out, 3, rtgX8664X86Low3(source), rtgX8664X86Low3(destination))
}
func rtgX8664X86RR(out *renvoAsm, opcode uint32, destination RTGRegister, source RTGRegister, width int) {
	rtgX8664X86REX(out, width == 64, destination, RTGNoRegister, source, RTGNoRegister)
	rtgX8664X86Opcode(out, opcode)
	rtgX8664X86ModRM(out, 3, rtgX8664X86Low3(destination), rtgX8664X86Low3(source))
}
func rtgX8664X86RMR(out *renvoAsm, opcode uint32, destination RTGRegister, address renvoRTGAddress, width int) {
	if width == 16 {
		renvoAsmEmit8(out,0x66)
	}
	rtgX8664X86REX(out, width == 64, destination, address.Index, address.Base, RTGNoRegister)
	rtgX8664X86Opcode(out, opcode)
	rtgX8664X86Memory(out, rtgX8664X86Low3(destination), address)
}
func rtgX8664X86RRM(out *renvoAsm, opcode uint32, address renvoRTGAddress, source RTGRegister, width int) {
	if width == 16 {
		renvoAsmEmit8(out,0x66)
	}
	byteRegister := RTGNoRegister
	if width == 8 {
		byteRegister = source
	}
	rtgX8664X86REX(out, width == 64, source, address.Index, address.Base, byteRegister)
	rtgX8664X86Opcode(out, opcode)
	rtgX8664X86Memory(out, rtgX8664X86Low3(source), address)
}
func rtgX8664X86Group(out *renvoAsm, opcode uint32, selector byte, operand RTGRegister, width int) {
	rtgX8664X86REX(out, width == 64, RTGNoRegister, RTGNoRegister, operand, RTGNoRegister)
	rtgX8664X86Opcode(out, opcode)
	rtgX8664X86ModRM(out, 3, selector, rtgX8664X86Low3(operand))
}
func rtgX8664X86GroupImmediate8(out *renvoAsm, opcode uint32, selector byte, operand RTGRegister, value byte, width int) {
	rtgX8664X86Group(out, opcode, selector, operand, width)
	out.code = append(out.code, byte(int(value)))
}
func rtgX8664X86Relative(out *renvoAsm, opcode uint32, label int) {
	rtgX8664X86Opcode(out, opcode)
	out.Rel32(label)
}
func rtgX8664X86SetCondition(out *renvoAsm, condition RTGCondition, destination RTGRegister) {
	rtgX8664X86REX(out, false, RTGNoRegister, RTGNoRegister, destination, destination)
	renvoAsmEmit8(out,0x0f)
	out.code = append(out.code, byte(int(condition.SetOpcode)))
	rtgX8664X86ModRM(out, 3, 0, rtgX8664X86Low3(destination))
}
func rtgX8664X86JumpCondition(out *renvoAsm, condition RTGCondition, label int) {
	renvoAsmEmit8(out,0x0f)
	out.code = append(out.code, byte(int(condition.JumpOpcode)))
	out.Rel32(label)
}
func rtgX8664X86MoveImmediate(out *renvoAsm, destination RTGRegister, value int64) {
	if destination.Code == 0 && value == 0 {
		renvoAsmEmit2(out,0x31, 0xc0)
	} else if destination.Code != 4 && RTGSignedFits(value, 8) {
		renvoAsmEmit2(out,0x6a, int(value))
		rtgX8664X86OpcodeRegister(out, 0x58, destination)
	} else if value >= 0 && RTGUnsignedFits(uint64(value), 32) {
		rtgX8664X86OpcodeRegister(out, 0xb8, destination)
		renvoAsmEmit32(out, int(value))
	} else if RTGSignedFits(value, 32) {
		renvoAsmEmit8(out,0x68)
		renvoAsmEmit32(out, int(value))
		rtgX8664X86OpcodeRegister(out, 0x58, destination)
	} else {
		rtgX8664X86REX(out, true, RTGNoRegister, RTGNoRegister, destination, RTGNoRegister)
		out.code = append(out.code, byte(int(0xb8 + rtgX8664X86Low3(destination))))
		out.Uint64(uint64(value))
	}
}
func rtgX8664X86OpcodeRegister(out *renvoAsm, opcode byte, operand RTGRegister) {
	if rtgX8664X86High(operand) != 0 {
		renvoAsmEmit8(out,0x41)
	}
	out.code = append(out.code, byte(int(opcode + rtgX8664X86Low3(operand))))
}
func rtgX8664X86VariableShift(out *renvoAsm, direction RTGShiftDirection, signed bool) {
	rtgX8664Xchg64(out, RTGRegister{Code: 0, Valid: true}, RTGRegister{Code: 1, Valid: true})
	if direction == RTGShiftLeft {
		rtgX8664ShlCL64(out, RTGRegister{Code: 0, Valid: true})
	} else if signed {
		rtgX8664SarCL64(out, RTGRegister{Code: 0, Valid: true})
	} else {
		rtgX8664ShrCL64(out, RTGRegister{Code: 0, Valid: true})
	}
}
func rtgX8664X86SignedDivide(out *renvoAsm, remainder bool) {
	primary := RTGRegister{Code: 0, Valid: true}
	secondary := RTGRegister{Code: 2, Valid: true}
	tertiary := RTGRegister{Code: 1, Valid: true}
	scratch := RTGRegister{Code: 3, Valid: true}
	ordinary := out.NewLabel()
	done := out.NewLabel()
	rtgX8664X86MoveImmediate(out, secondary, -1)
	rtgX8664X86RRRM(out, 0x39, primary, secondary, 64)
	rtgX8664X86JumpCondition(out, RTGCondition{JumpOpcode: 0x85}, ordinary)
	rtgX8664X86MoveImmediate(out, secondary, 1)
	rtgX8664X86GroupImmediate8(out, 0xc1, 4, secondary, 63, 64)
	rtgX8664X86RRRM(out, 0x39, tertiary, secondary, 64)
	rtgX8664X86JumpCondition(out, RTGCondition{JumpOpcode: 0x85}, ordinary)
	if remainder {
		rtgX8664X86MoveImmediate(out, primary, 0)
	} else {
		rtgX8664X86RRRM(out, 0x89, primary, tertiary, 64)
	}
	rtgX8664X86Relative(out, 0xe9, done)
	out.Mark(ordinary)
	rtgX8664X86OpcodeRegister(out, 0x50, scratch)
	rtgX8664X86RRRM(out, 0x89, scratch, primary, 64)
	rtgX8664X86RRRM(out, 0x89, primary, tertiary, 64)
	renvoAsmEmit2(out,0x48, 0x99)
	rtgX8664X86Group(out, 0xf7, 7, scratch, 64)
	if remainder {
		rtgX8664X86RRRM(out, 0x89, primary, secondary, 64)
	}
	rtgX8664X86OpcodeRegister(out, 0x58, scratch)
	out.Mark(done)
}
func rtgX8664X86CopyBytes(out *renvoAsm) {
	destination := RTGRegister{Code: 7, Valid: true}
	source := RTGRegister{Code: 6, Valid: true}
	count := RTGRegister{Code: 1, Valid: true}
	scratch := RTGRegister{Code: 10, Valid: true}
	forward := out.NewLabel()
	done := out.NewLabel()
	rtgX8664X86RRRM(out, 0x39, destination, source, 64)
	rtgX8664X86JumpCondition(out, RTGCondition{JumpOpcode: 0x86}, forward)
	rtgX8664X86RMR(out, 0x8d, scratch, renvoRTGAddress{Base: source, Index: count, Scale: 1}, 64)
	rtgX8664X86RRRM(out, 0x39, destination, scratch, 64)
	rtgX8664X86JumpCondition(out, RTGCondition{JumpOpcode: 0x83}, forward)
	rtgX8664X86RMR(out, 0x8d, source, renvoRTGAddress{Base: source, Index: count, Scale: 1, Displacement: -1}, 64)
	rtgX8664X86RMR(out, 0x8d, destination, renvoRTGAddress{Base: destination, Index: count, Scale: 1, Displacement: -1}, 64)
	renvoAsmEmit4(out,0xfd, 0xf3, 0xa4, 0xfc)
	rtgX8664X86Relative(out, 0xe9, done)
	out.Mark(forward)
	renvoAsmEmit3(out,0xfc, 0xf3, 0xa4)
	out.Mark(done)
}
func rtgX8664X86PatchRelocations(out *renvoAsm) {
	for i := 0; i < len(out.relocs) / 2; i++ {
		at := int(out.relocs[i*2])
		label := int(out.relocs[i*2+1])
		target := renvoAsmLabelPosition(out,label)
		if at < 0 || at+4 > len(out.code) || target < 0 {
			continue
		}
		addend := renvoGet32At(out.code, at)
		renvoPut32At(out.code,at, target+addend-(at+4))
	}
}

// Generated from instruction mov64.
func rtgX8664Mov64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x89, destination, source, 64)
}

// Generated from instruction load64.
func rtgX8664Load64(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x8b, destination, address, 64)
}

// Generated from instruction lea64.
func rtgX8664Lea64(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x8d, destination, address, 64)
}

// Generated from instruction load_i32.
func rtgX8664LoadI32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x63, destination, address, 32)
}

// Generated from instruction load_u32.
func rtgX8664LoadU32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x8b, destination, address, 32)
}

// Generated from instruction load_i16.
func rtgX8664LoadI16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x0fbf, destination, address, 16)
}

// Generated from instruction load_u16.
func rtgX8664LoadU16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x0fb7, destination, address, 16)
}

// Generated from instruction load_i8.
func rtgX8664LoadI8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x0fbe, destination, address, 8)
}

// Generated from instruction load_u8.
func rtgX8664LoadU8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664X86RMR(out, 0x0fb6, destination, address, 8)
}

// Generated from instruction store64.
func rtgX8664Store64(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x89, address, source, 64)
}

// Generated from instruction store32.
func rtgX8664Store32(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x89, address, source, 32)
}

// Generated from instruction store16.
func rtgX8664Store16(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x89, address, source, 16)
}

// Generated from instruction store8.
func rtgX8664Store8(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664X86RRM(out, 0x88, address, source, 8)
}

// Generated from instruction add64.
func rtgX8664Add64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x01, destination, source, 64)
}

// Generated from instruction sub64.
func rtgX8664Sub64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x29, destination, source, 64)
}

// Generated from instruction and64.
func rtgX8664And64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x21, destination, source, 64)
}

// Generated from instruction or64.
func rtgX8664Or64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x09, destination, source, 64)
}

// Generated from instruction xor64.
func rtgX8664Xor64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x31, destination, source, 64)
}

// Generated from instruction cmp64.
func rtgX8664Cmp64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x39, destination, source, 64)
}

// Generated from instruction test64.
func rtgX8664Test64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x85, destination, source, 64)
}

// Generated from instruction imul64.
func rtgX8664Imul64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RR(out, 0x0faf, destination, source, 64)
}

// Generated from instruction xchg64.
func rtgX8664Xchg64(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664X86RRRM(out, 0x87, destination, source, 64)
}

// Generated from instruction inc64.
func rtgX8664Inc64(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86Group(out, 0xff, 0, operand, 64)
}

// Generated from instruction dec64.
func rtgX8664Dec64(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86Group(out, 0xff, 1, operand, 64)
}

// Generated from instruction shl_imm64.
func rtgX8664ShlImmediate64(out *renvoAsm, operand RTGRegister, value byte) {
	rtgX8664X86GroupImmediate8(out, 0xc1, 4, operand, value, 64)
}

// Generated from instruction shr_imm64.
func rtgX8664ShrImmediate64(out *renvoAsm, operand RTGRegister, value byte) {
	rtgX8664X86GroupImmediate8(out, 0xc1, 5, operand, value, 64)
}

// Generated from instruction sar_imm64.
func rtgX8664SarImmediate64(out *renvoAsm, operand RTGRegister, value byte) {
	rtgX8664X86GroupImmediate8(out, 0xc1, 7, operand, value, 64)
}

// Generated from instruction shl_cl64.
func rtgX8664ShlCL64(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86Group(out, 0xd3, 4, operand, 64)
}

// Generated from instruction shr_cl64.
func rtgX8664ShrCL64(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86Group(out, 0xd3, 5, operand, 64)
}

// Generated from instruction sar_cl64.
func rtgX8664SarCL64(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86Group(out, 0xd3, 7, operand, 64)
}

// Generated from instruction call_reg.
func rtgX8664CallRegister(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86Group(out, 0xff, 2, operand, 64)
}

// Generated from instruction push_reg.
func rtgX8664PushRegister(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86OpcodeRegister(out, 0x50, operand)
}

// Generated from instruction pop_reg.
func rtgX8664PopRegister(out *renvoAsm, operand RTGRegister) {
	rtgX8664X86OpcodeRegister(out, 0x58, operand)
}

// Generated from instruction setcc.
func rtgX8664Setcc(out *renvoAsm, condition RTGCondition, destination RTGRegister) {
	rtgX8664X86SetCondition(out, condition, destination)
}

// Generated from instruction jcc_rel32.
func rtgX8664JccRel32(out *renvoAsm, condition RTGCondition, label int) {
	rtgX8664X86JumpCondition(out, condition, label)
}

// Generated from instruction call_rel32.
func rtgX8664CallRel32(out *renvoAsm, label int) {
	rtgX8664X86Relative(out, 0xe8, label)
}

// Generated from instruction jump_rel32.
func rtgX8664JumpRel32(out *renvoAsm, label int) {
	rtgX8664X86Relative(out, 0xe9, label)
}

// Generated from instruction ret.
func rtgX8664Ret(out *renvoAsm) {
	renvoRTGByte(out, 0xc3)
}

// Generated from instruction leave.
func rtgX8664Leave(out *renvoAsm) {
	renvoRTGByte(out, 0xc9)
}

// Generated from instruction syscall.
func rtgX8664Syscall(out *renvoAsm) {
	renvoRTGByte(out, 0x0f)
	renvoRTGByte(out, 0x05)
}

// Generated direct_emitter_v1 binding for move.
// Effects: reads=source; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectMove(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Mov64(out, destination, source)
}

// Generated direct_emitter_v1 binding for address.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough; relocation=address
func rtgX8664DirectAddress(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664Lea64(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.native.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:native:target; control=fallthrough; relocation=address
func rtgX8664DirectLoadNative(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664Load64(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.i32.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:32:signed:target; control=fallthrough; relocation=address
func rtgX8664DirectLoadI32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664LoadI32(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.u32.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:32:unsigned:target; control=fallthrough; relocation=address
func rtgX8664DirectLoadU32(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664LoadU32(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.i16.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:16:signed:target; control=fallthrough; relocation=address
func rtgX8664DirectLoadI16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664LoadI16(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.u16.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:16:unsigned:target; control=fallthrough; relocation=address
func rtgX8664DirectLoadU16(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664LoadU16(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.i8.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:8:signed:1; control=fallthrough; relocation=address
func rtgX8664DirectLoadI8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664LoadI8(out, destination, address)
}

// Generated direct_emitter_v1 binding for load.u8.
// Effects: reads=address; writes=destination; clobbers=-; preserves=all_except_writes; memory=read:8:unsigned:1; control=fallthrough; relocation=address
func rtgX8664DirectLoadU8(out *renvoAsm, destination RTGRegister, address renvoRTGAddress) {
	rtgX8664LoadU8(out, destination, address)
}

// Generated direct_emitter_v1 binding for store.native.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:native:target; control=fallthrough; relocation=address
func rtgX8664DirectStoreNative(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664Store64(out, address, source)
}

// Generated direct_emitter_v1 binding for store.u32.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:32:target; control=fallthrough; relocation=address
func rtgX8664DirectStoreU32(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664Store32(out, address, source)
}

// Generated direct_emitter_v1 binding for store.u16.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:16:target; control=fallthrough; relocation=address
func rtgX8664DirectStoreU16(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664Store16(out, address, source)
}

// Generated direct_emitter_v1 binding for store.u8.
// Effects: reads=address,source; writes=memory; clobbers=-; preserves=all_locations; memory=write:8:1; control=fallthrough; relocation=address
func rtgX8664DirectStoreU8(out *renvoAsm, address renvoRTGAddress, source RTGRegister) {
	rtgX8664Store8(out, address, source)
}

// Generated direct_emitter_v1 binding for add.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectAdd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Add64(out, destination, source)
}

// Generated direct_emitter_v1 binding for subtract.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectSubtract(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Sub64(out, destination, source)
}

// Generated direct_emitter_v1 binding for multiply.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectMultiply(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Imul64(out, destination, source)
}

// Generated direct_emitter_v1 binding for bit_and.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectBitAnd(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664And64(out, destination, source)
}

// Generated direct_emitter_v1 binding for bit_or.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectBitOr(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Or64(out, destination, source)
}

// Generated direct_emitter_v1 binding for bit_xor.
// Effects: reads=destination,source; writes=destination,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectBitXor(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Xor64(out, destination, source)
}

// Generated direct_emitter_v1 binding for compare.
// Effects: reads=left,right; writes=flags; clobbers=flags; preserves=all_locations; control=fallthrough
func rtgX8664DirectCompare(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Cmp64(out, destination, source)
}

// Generated direct_emitter_v1 binding for test.
// Effects: reads=left,right; writes=flags; clobbers=flags; preserves=all_locations; control=fallthrough
func rtgX8664DirectTest(out *renvoAsm, destination RTGRegister, source RTGRegister) {
	rtgX8664Test64(out, destination, source)
}

// Generated direct_emitter_v1 binding for increment.
// Effects: reads=operand; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectIncrement(out *renvoAsm, operand RTGRegister) {
	rtgX8664Inc64(out, operand)
}

// Generated direct_emitter_v1 binding for decrement.
// Effects: reads=operand; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectDecrement(out *renvoAsm, operand RTGRegister) {
	rtgX8664Dec64(out, operand)
}

// Generated direct_emitter_v1 binding for shift_left_immediate.
// Effects: reads=operand,value; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectShiftLeftImmediate(out *renvoAsm, operand RTGRegister, value byte) {
	rtgX8664ShlImmediate64(out, operand, value)
}

// Generated direct_emitter_v1 binding for shift_right_unsigned_immediate.
// Effects: reads=operand,value; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectShiftRightUnsignedImmediate(out *renvoAsm, operand RTGRegister, value byte) {
	rtgX8664ShrImmediate64(out, operand, value)
}

// Generated direct_emitter_v1 binding for shift_right_signed_immediate.
// Effects: reads=operand,value; writes=operand,flags; clobbers=flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectShiftRightSignedImmediate(out *renvoAsm, operand RTGRegister, value byte) {
	rtgX8664SarImmediate64(out, operand, value)
}

// Generated direct_emitter_v1 binding for call.
// Effects: reads=label,call_words,stack; writes=primary,secondary,tertiary,stack; clobbers=call_clobbered,flags; preserves=callee_saved; control=call; relocation=label
func rtgX8664DirectCall(out *renvoAsm, label int) {
	rtgX8664CallRel32(out, label)
}

// Generated direct_emitter_v1 binding for call_indirect.
// Effects: reads=operand,call_words,stack; writes=primary,secondary,tertiary,stack; clobbers=call_clobbered,flags; preserves=callee_saved; control=call_indirect; requires=indirect_call; rejection=permitted
func rtgX8664DirectCallIndirect(out *renvoAsm, operand RTGRegister) {
	rtgX8664CallRegister(out, operand)
}

// Generated direct_emitter_v1 binding for jump.
// Effects: reads=label; writes=-; clobbers=-; preserves=all_locations; control=branch; relocation=label
func rtgX8664DirectJump(out *renvoAsm, label int) {
	rtgX8664JumpRel32(out, label)
}

// Generated direct_emitter_v1 binding for jump_condition.
// Effects: reads=condition,label; writes=-; clobbers=-; preserves=all_locations; control=conditional_branch; relocation=label
func rtgX8664DirectJumpCondition(out *renvoAsm, condition RTGCondition, label int) {
	rtgX8664JccRel32(out, condition, label)
}

// Generated direct_emitter_v1 binding for set_condition.
// Effects: reads=condition,flags; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectSetCondition(out *renvoAsm, condition RTGCondition, destination RTGRegister) {
	rtgX8664Setcc(out, condition, destination)
}

// Generated direct_emitter_v1 binding for return.
// Effects: reads=stack; writes=-; clobbers=-; preserves=all_locations; control=return
func rtgX8664DirectReturn(out *renvoAsm) {
	rtgX8664Ret(out)
}

// Generated direct_emitter_v1 binding for leave.
// Effects: reads=frame,stack; writes=frame,stack; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectLeave(out *renvoAsm) {
	rtgX8664Leave(out)
}

// Generated direct_emitter_v1 binding for host_syscall.
// Effects: reads=syscall_number,syscall_words; writes=syscall_result; clobbers=syscall_clobbered,flags; preserves=callee_saved; memory=host; control=call; requires=host_syscall
func rtgX8664DirectHostSyscall(out *renvoAsm) {
	rtgX8664Syscall(out)
}

// Generated direct_emitter_v1 binding for move_immediate.
// Effects: reads=value; writes=destination; clobbers=-; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectMoveImmediate(out *renvoAsm, destination RTGRegister, value int64) {
	rtgX8664X86MoveImmediate(out, destination, value)
}

// Generated direct_emitter_v1 binding for variable_shift.
// Effects: reads=primary,tertiary; writes=primary; clobbers=tertiary,flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectVariableShift(out *renvoAsm, direction RTGShiftDirection, signed bool) {
	rtgX8664X86VariableShift(out, direction, signed)
}

// Generated direct_emitter_v1 binding for signed_divide.
// Effects: reads=primary,tertiary; writes=primary; clobbers=secondary,flags; preserves=all_except_writes; control=fallthrough
func rtgX8664DirectSignedDivide(out *renvoAsm, remainder bool) {
	rtgX8664X86SignedDivide(out, remainder)
}

// Generated direct_emitter_v1 binding for copy_bytes.
// Effects: reads=copy_destination,copy_source,copy_count,memory; writes=memory; clobbers=copy_destination,copy_source,copy_count,flags; preserves=other_locations; memory=read_write:8:1; control=fallthrough
func rtgX8664DirectCopyBytes(out *renvoAsm) {
	rtgX8664X86CopyBytes(out)
}

// Generated definition-owned relocation finalizer.
func rtgX8664PatchRelocations(out *renvoAsm) {
	rtgX8664X86PatchRelocations(out)
}
