// Command genunicode prints the Unicode tables used by the portable scanner.
package main

import (
	"fmt"
	"unicode"
)

func main() {
	fmt.Println("// Code generated by go run ./internal/syntax/cmd/genunicode; DO NOT EDIT.")
	fmt.Printf("// Unicode version %s.\npackage syntax\n", unicode.Version)
	for _, item := range []struct {
		name  string
		table *unicode.RangeTable
	}{
		{"unicodeLetterRanges", unicode.L},
		{"unicodeDigitRanges", unicode.Nd},
		{"unicodeUpperRanges", unicode.Lu},
	} {
		fmt.Printf("var %s = []int{\n", item.name)
		for _, r := range item.table.R16 {
			fmt.Printf("%d, %d, %d,\n", r.Lo, r.Hi, r.Stride)
		}
		for _, r := range item.table.R32 {
			fmt.Printf("%d, %d, %d,\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Println("}")
	}
}
