// Command genunicode prints the Unicode tables used by the portable scanner.
package main

import (
	"fmt"
	"unicode"
)

func main() {
	fmt.Println("// Code generated by go run ./internal/syntax/cmd/genunicode; DO NOT EDIT.")
	fmt.Printf("// Unicode version %s.\npackage syntax\n", unicode.Version)
	for _, item := range []struct {
		name  string
		table *unicode.RangeTable
	}{
		{"unicodeLetterRanges", unicode.L},
		{"unicodeDigitRanges", unicode.Nd},
		{"unicodeUpperRanges", unicode.Lu},
	} {
		var packed []byte
		for _, r := range item.table.R16 {
			packed = appendRange(packed, uint32(r.Lo), uint32(r.Hi), uint32(r.Stride))
		}
		for _, r := range item.table.R32 {
			packed = appendRange(packed, r.Lo, r.Hi, r.Stride)
		}
		fmt.Printf("var %s = %q\n", item.name, string(packed))
	}
}

// Three 24-bit values per range, encoded with four printable six-bit bytes
// each. This avoids thousands of initializer expressions and verbose byte
// escapes in the source that the compiler must retain during self-hosting.
func appendRange(out []byte, lo, hi, stride uint32) []byte {
	for _, value := range []uint32{lo, hi, stride} {
		for shift := 18; shift >= 0; shift -= 6 {
			out = append(out, byte(value>>uint(shift)&63)+32)
		}
	}
	return out
}
