// Command genstdunicode generates portable Unicode data, not runtime wrappers
// around the host library. Run from the Renvo repository root.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"unicode"
)

func main() {
	check := flag.Bool("check", false, "verify the checked-in Unicode snapshot")
	flag.Parse()
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go run ./cmd/genstdunicode; DO NOT EDIT.\npackage unicode")
	fmt.Fprintf(&out, "const Version = %q\n", unicode.Version)
	for _, item := range []struct {
		name  string
		table *unicode.RangeTable
	}{
		{"letterRanges", unicode.Letter}, {"digitRanges", unicode.Digit}, {"spaceRanges", unicode.White_Space},
		{"upperRanges", unicode.Upper}, {"lowerRanges", unicode.Lower}, {"titleRanges", unicode.Title},
	} {
		fmt.Fprintf(&out, "var %s = []int{\n", item.name)
		for _, r := range item.table.R16 {
			fmt.Fprintf(&out, "%d,%d,%d,\n", r.Lo, r.Hi, r.Stride)
		}
		for _, r := range item.table.R32 {
			fmt.Fprintf(&out, "%d,%d,%d,\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Fprintln(&out, "}")
	}
	fmt.Fprintln(&out, "var caseRanges = []int{")
	for _, r := range unicode.CaseRanges {
		fmt.Fprintf(&out, "%d,%d,%d,%d,%d,\n", r.Lo, r.Hi, r.Delta[0], r.Delta[1], r.Delta[2])
	}
	fmt.Fprintln(&out, "}\nvar foldPairs = []int{")
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if next := unicode.SimpleFold(r); next != r {
			fmt.Fprintf(&out, "%d,%d,\n", r, next)
		}
	}
	fmt.Fprintln(&out, "}")
	data, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	const path = "std/unicode/tables.go"
	if *check {
		existing, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(existing, data) {
			panic("Unicode snapshot differs; regenerate with the intended Go Unicode version")
		}
		return
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		panic(err)
	}
}
