package load

import (
	"renvo.dev/internal/c11"
	"renvo.dev/internal/syntax"
)

type goExportDefinition struct {
	Mapping c11.GoExport
	File    int
	Func    int
}

type cgoTypeSpan struct {
	Start int
	End   int
}

func cgoExportMappings(definitions []goExportDefinition) []c11.GoExport {
	if len(definitions) == 0 {
		return nil
	}
	out := make([]c11.GoExport, len(definitions))
	for i := 0; i < len(definitions); i++ {
		out[i] = definitions[i].Mapping
	}
	return out
}

func cgoExportHeader(files []syntax.File, definitions []goExportDefinition, dataModel int) ([]byte, bool) {
	if len(definitions) == 0 {
		return []byte("/* Code generated by Renvo cgo; DO NOT EDIT. */\n"), true
	}
	out := []byte("/* Code generated by Renvo cgo; DO NOT EDIT. */\n")
	for i := 0; i < len(files); i++ {
		for j := 0; j < len(files[i].Imports); j++ {
			preamble, _, cgoImport := syntax.CgoPreamble(files[i], files[i].Imports[j])
			if cgoImport && len(preamble) > 0 {
				out = append(out, preamble...)
				if out[len(out)-1] != '\n' {
					out = append(out, '\n')
				}
			}
		}
	}
	for i := 0; i < len(definitions); i++ {
		definition := definitions[i]
		if definition.File < 0 || definition.File >= len(files) || definition.Func < 0 || definition.Func >= len(files[definition.File].Funcs) {
			return nil, false
		}
		file := files[definition.File]
		fn := file.Funcs[definition.Func]
		params, ok := cgoFunctionFieldTypes(file, fn.ParamsStart+1, fn.ParamsEnd-1)
		if !ok {
			return nil, false
		}
		results, ok := cgoFunctionResultTypes(file, fn)
		if !ok || len(results) > 1 {
			return nil, false
		}
		resultType := "void"
		if len(results) == 1 {
			resultType, ok = cgoCType(file, results[0], dataModel)
			if !ok {
				return nil, false
			}
		}
		out = append(out, "extern "...)
		out = append(out, resultType...)
		out = append(out, ' ')
		out = append(out, definition.Mapping.CName...)
		out = append(out, '(')
		if len(params) == 0 {
			out = append(out, "void"...)
		}
		for j := 0; j < len(params); j++ {
			if j > 0 {
				out = append(out, ',', ' ')
			}
			typeName, valid := cgoCType(file, params[j], dataModel)
			if !valid {
				return nil, false
			}
			out = append(out, typeName...)
			out = append(out, ' ')
			out = append(out, 'p')
			out = appendDecimalCgo(out, j)
		}
		out = append(out, ')', ';', '\n')
	}
	return out, true
}

func cgoFunctionResultTypes(file syntax.File, fn syntax.FuncDecl) ([]cgoTypeSpan, bool) {
	if fn.ResultStart < 0 || fn.ResultEnd <= fn.ResultStart {
		return nil, true
	}
	if cgoTokenIs(file, fn.ResultStart, "(") && cgoTokenIs(file, fn.ResultEnd-1, ")") {
		return cgoFunctionFieldTypes(file, fn.ResultStart+1, fn.ResultEnd-1)
	}
	return []cgoTypeSpan{{Start: fn.ResultStart, End: fn.ResultEnd}}, true
}

func cgoFunctionFieldTypes(file syntax.File, start int, end int) ([]cgoTypeSpan, bool) {
	if start < 0 || end < start || end > len(file.Tokens) {
		return nil, false
	}
	var out []cgoTypeSpan
	var pending []int
	for i := start; i < end; {
		segmentEnd := cgoNextTopLevelComma(file, i, end)
		first, last := i, segmentEnd
		if first >= last {
			i = segmentEnd + 1
			continue
		}
		if last-first == 1 && file.Tokens[first].KindLine&255 == syntax.TokenIdent {
			pending = append(pending, first)
			i = segmentEnd + 1
			continue
		}
		if file.Tokens[first].KindLine&255 == syntax.TokenIdent && first+1 < last && !cgoTokenIs(file, first+1, ".") {
			for j := 0; j < len(pending)+1; j++ {
				out = append(out, cgoTypeSpan{Start: first + 1, End: last})
			}
			pending = pending[:0]
		} else {
			for j := 0; j < len(pending); j++ {
				out = append(out, cgoTypeSpan{Start: pending[j], End: pending[j] + 1})
			}
			pending = pending[:0]
			out = append(out, cgoTypeSpan{Start: first, End: last})
		}
		i = segmentEnd + 1
	}
	for i := 0; i < len(pending); i++ {
		out = append(out, cgoTypeSpan{Start: pending[i], End: pending[i] + 1})
	}
	return out, true
}

func cgoNextTopLevelComma(file syntax.File, start int, end int) int {
	paren, bracket, brace := 0, 0, 0
	for i := start; i < end; i++ {
		switch {
		case cgoTokenIs(file, i, "("):
			paren++
		case cgoTokenIs(file, i, ")"):
			paren--
		case cgoTokenIs(file, i, "["):
			bracket++
		case cgoTokenIs(file, i, "]"):
			bracket--
		case cgoTokenIs(file, i, "{"):
			brace++
		case cgoTokenIs(file, i, "}"):
			brace--
		case paren == 0 && bracket == 0 && brace == 0 && cgoTokenIs(file, i, ","):
			return i
		}
	}
	return end
}

func cgoCType(file syntax.File, span cgoTypeSpan, dataModel int) (string, bool) {
	if span.Start < 0 || span.End <= span.Start || span.End > len(file.Tokens) {
		return "", false
	}
	if cgoTokenIs(file, span.Start, "*") {
		base, ok := cgoCType(file, cgoTypeSpan{Start: span.Start + 1, End: span.End}, dataModel)
		if !ok {
			return "", false
		}
		return base + " *", true
	}
	if span.End-span.Start == 3 && cgoTokenIs(file, span.Start, "C") && cgoTokenIs(file, span.Start+1, ".") {
		return string(syntax.TokenText(file.Src, file.Tokens[span.Start+2])), true
	}
	if span.End-span.Start == 3 && cgoTokenIs(file, span.Start, "unsafe") && cgoTokenIs(file, span.Start+1, ".") && cgoTokenIs(file, span.Start+2, "Pointer") {
		return "void *", true
	}
	if span.End-span.Start != 1 {
		return "", false
	}
	name := string(syntax.TokenText(file.Src, file.Tokens[span.Start]))
	switch name {
	case "bool":
		return "_Bool", true
	case "byte", "uint8":
		return "unsigned char", true
	case "int8":
		return "signed char", true
	case "int16":
		return "short", true
	case "uint16":
		return "unsigned short", true
	case "int32", "rune":
		return "int", true
	case "uint32":
		return "unsigned int", true
	case "int64":
		return "long long", true
	case "uint64":
		return "unsigned long long", true
	case "float32":
		return "float", true
	case "float64":
		return "double", true
	case "int":
		if dataModel == c11.DataModelILP32 {
			return "int", true
		}
		return "long long", true
	case "uint", "uintptr":
		if dataModel == c11.DataModelILP32 {
			return "unsigned int", true
		}
		return "unsigned long long", true
	}
	return "", false
}

func cgoTokenIs(file syntax.File, tok int, text string) bool {
	if tok < 0 || tok >= len(file.Tokens) {
		return false
	}
	value := syntax.TokenText(file.Src, file.Tokens[tok])
	if len(value) != len(text) {
		return false
	}
	for i := 0; i < len(value); i++ {
		if value[i] != text[i] {
			return false
		}
	}
	return true
}

func appendDecimalCgo(out []byte, value int) []byte {
	if value == 0 {
		return append(out, '0')
	}
	var digits [20]byte
	count := 0
	for value > 0 {
		digits[count] = byte('0' + value%10)
		count++
		value /= 10
	}
	for i := count - 1; i >= 0; i-- {
		out = append(out, digits[i])
	}
	return out
}

func cgoSourceIncludesExportHeader(src []byte) bool {
	for i := 0; i < len(src); {
		end := i
		for end < len(src) && src[end] != '\n' {
			end++
		}
		if cgoExportHeaderIncludeLine(src[i:end]) {
			return true
		}
		i = end + 1
	}
	return false
}

func cgoExportHeaderIncludeLine(line []byte) bool {
	i := 0
	for i < len(line) && (line[i] == ' ' || line[i] == '\t') {
		i++
	}
	if i >= len(line) || line[i] != '#' {
		return false
	}
	i++
	for i < len(line) && (line[i] == ' ' || line[i] == '\t') {
		i++
	}
	const include = "include"
	for j := 0; j < len(include); j++ {
		if i+j >= len(line) || line[i+j] != include[j] {
			return false
		}
	}
	i += len(include)
	for i < len(line) && (line[i] == ' ' || line[i] == '\t') {
		i++
	}
	const name = "_cgo_export.h"
	if i >= len(line) || line[i] != '"' && line[i] != '<' {
		return false
	}
	close := byte('"')
	if line[i] == '<' {
		close = '>'
	}
	i++
	for j := 0; j < len(name); j++ {
		if i+j >= len(line) || line[i+j] != name[j] {
			return false
		}
	}
	i += len(name)
	return i < len(line) && line[i] == close
}
